### ISSUE TITLE
Documentation regarding templates directory

### ISSUE THREAD

**Issue by rittelle** [CrowCpp/crow#100]
https://crowcpp.org/guides/templating/ states:

> The HTML page (including the mustache tags). It is usually loaded into crow::mustache::template_t. It needs to be placed in templates directory (relative to where the crow executable is).

This seems to be incorrect on version 0.2 at least, where it seems that the `templates/` folder needs to be in the current working directory.
So it should state:

> The HTML page (including the mustache tags). It is usually loaded into crow::mustache::template_t. It needs to be placed **in the templates directory which should be in the current working directory of the crow executable**.

Missing template files get silently ignored (even on the debug log level), too. This should not be the case...

**Comment by The-EDev** [comment]
Thanks a lot for the info, I'll update the documentation and add a log line for templates ASAP.

**Comment by rittelle** [comment]
Wow, thanks for the fast response (and for maintaining this project, too)!
