### ISSUE TITLE
Websites with images are (sometimes) broken on localhost

### ISSUE THREAD

**Issue by rittelle** [CrowCpp/crow#104]
# Introduction

Im building a website based on crow that features HTML pages that include linked images.
Here is a "minimum breaking example": <https://github.com/rittelle/test-crow-race-condition>

# Expected behavior

<http://localhost:8080> should show a very simple webpage with an image.

# Actual behavior

Sometimes some XML code appears instead of the webpage. A look at the requests in the developer tools reveals that crow seems to sometimes respond with the content of `static/image.svg` instead of the intended content of `/` from `main.cc`. This is not happening every time (but most of the time for me, which is quite annoying), so it's maybe something like a race condition between the routes when both are requested?

The error also does not occur, when:
- the page is refreshed with <key>CTRL-F5</key> instead of <key>F5</key>
    - maybe Firefox makes requests in parallel, when the page is in its cache and <key>CTRL-F5</key> prevents that?
- the html page also resides in the `static` folder
    - testable using the link on the main page
    - maybe it's a race condition between the `static/` routes in general and the other routes?
- accessing the site from another computer (in the same network)

# Test setup

- using `crow_all.h` from 4e801d085ae1f1ab72d1ee080796b2241f01cd0b
- gcc 10.2.0, Firefox 85.0.1 on Arch

# Final note

I didn't try other browser / OSes, yet. I may find the time to further investigate in the next days, but I don't know the codebase; any pointers would be appreciated ;) .

**Comment by rittelle** [comment]
I added another testcase to my test repo where I explicitly serve `static/image.svg` using `crow::response::set_static_file_info()`. This also leads to broken behaviour, but the resulting page is empty instead of the svg content.

As a summary:
- <localhost:8080/>: sometimes broken; `static/image.svg` instead of the HTML
- <localhost:8080/route/site.html>: sometimes broken; blank page instead of the HTML
- <localhost:8080/static/site.html>: works

**Comment by The-EDev** [comment]
This is weird, because the `static/` route literally uses `set_static_file_info()`, and I'm not sure how there can be a race between `/` and `/static/image.svg`.

I'll check the example you gave and get back to you ASAP

**Comment by rittelle** [comment]
You mean sending an template via the `template/` directory and moustache by "the correct way of serving a template“?
I found this issue by doing exactly that, the repository is just a minimal example, after I found out, that using templates or not doesn't change the symptoms.

**Comment by rittelle** [comment]
After poking around with the debugger for a while, I found the issue:

Crow reuses the `crow::response` object for each request, but it does not get cleared properly [here](https://github.com/CrowCpp/crow/blob/1c505df69fffc3951af6af1fa2121801b6b87a51/include/crow/http_response.h#L94) because the member [`file_info`](https://github.com/CrowCpp/crow/blob/1c505df69fffc3951af6af1fa2121801b6b87a51/include/crow/http_response.h#L239) does not get cleared. So any request after serving a static file may still have parts of the previous response set, and this leads to the observed "Frankenresponse".

Does Crow only keep the response object around while the connection is kept alive? This would be an explanation why it only happened sometimes.
