### ISSUE TITLE
Configuring Crow installation with Microsoft Visual Studio

### ISSUE THREAD

**Issue by ayaankhan98** [CrowCpp/crow#108]
On getting started page currently we don't have instructions for the configuration of Crow with Microsoft Visual Studio.

**Comment by The-EDev** [comment]
The reason behind this is because neither myself no @mrozigor uses windows. And I'm not sure I can give good instructions on an OS I haven't used for work since 2018. if anyone uses Crow on windows help would be very appreciated.

**Comment by ayaankhan98** [comment]
Crow codebase is not compatible with Microsoft Visual Studio. I faced many problems in setting it up with Visual Studio.

Soon i will be making a PR, adding windows configuration steps.

**Comment by The-EDev** [comment]
If anyone else is working with windows and would like to contribute to this issue feel free to.

**Comment by thinking-tower** [comment]
@ayaankhan98 If you've got some time, could you try my instructions for getting `crow` running on `Windows`?

**Comment by ayaankhan98** [comment]
> @ayaankhan98 If you've got some time, could you try my instructions for getting `crow` running on `Windows`?

yes for sure, will review your instructions soon.

**Comment by The-EDev** [comment]
Technically this issue is resolved with #137. 

If you're reading this after the fact and don't want to use vcpkg, feel free to either open an issue or a PR with instructions on installing Zlib and Boost and using them with crow in visual studio.
