### ISSUE TITLE
Splitting a server into multiple source files does not work

### ISSUE THREAD

**Issue by rittelle** [CrowCpp/crow#110]
# The problem
I'm trying to split my server code into multiple source files to improve readability and compilation times.
Crow, being a header only library, defines some global symbols inside its headers, which makes it impossible to include some of them in multiple translation units. For example:
```c++
// main.cc
#include <crow.h>

int main() { return 0; }
```

```c++
// settings.cc
#include <crow/http_response.h>
```

Compiling and linking both files should result a linker error (I did not test this example) like:
```
/usr/bin/ld: CMakeFiles/server.dir/main.cc.o:(.bss+0x0): multiple definition of `crow::mime_types[abi:cxx11]'; CMakeFiles/server.dir/routes/settings.cc.o:(.bss+0x0): first defined here
```

# The issue

At least the map in `mime_types.h` gets defined multiple times:
https://github.com/CrowCpp/crow/blob/51a8a977d936902be859d80ccdf3217d15905f2e/include/crow/mime_types.h#L6

# Possible solutions

My solution would be to introduce a Macro, which defines globals, like the map mentioned above, as extern, when it is not defined and let the user of the library define it in exact one translation unit. Similar to [catch2](https://github.com/catchorg/Catch2) with its `CATCH_CONFIG_MAIN`.
This is a breaking change, though. But inverting the macro (making the globals `extern` whenever defined), is not. I may look into this, if I find the time in the next days.

**Comment by The-EDev** [comment]
I don't exactly understand this issue. correct me if I'm wrong, but wouldn't `#pragma once` solve this?

Also wouldn't this issue affect every single class in crow. Since `crow.h` includes every crow class name.

**Comment by rittelle** [comment]
Sry for the late response.
`#pragma once` only affects the current translation unit (e.g. .cc/.cpp-file) like the include guards.

If you build both files from the minimal examples like
``` bash
$ gcc -c main.cc -o main.o
$ gcc -c settings.cc -o settings.o
```
then both `main.o` and `settings.o` contain a copy of `mime_types`. The linker will not be able to link those objects into one binary because it can't resolve the symbol conflict. `#pragma once` ensures that `mime_types` is only defined once per object file, but not once in the whole program.

**Comment by The-EDev** [comment]
Understood, Thanks for the explanation.
