### ISSUE TITLE
Use port 0 to get random port for testing

### ISSUE THREAD

**Issue by ChoppinBlockParty** [CrowCpp/crow#113]
I think it would be a good idea to be able to use port 0 to get a random port from os. The current problem is I do not see a way how I can get the socket port number from the server.

**Comment by The-EDev** [comment]
hmmm, the server does tell you `server is running at 0.0.0.0:18080` when you start it, as for getting random ports, I'm not sure how this can be useful.

**Comment by ChoppinBlockParty** [comment]
When you start server in your test with `*:0`, you do not know which port the server has actually taken within the test. Thus, you cannot actually send a test request anywhere.

As a work around right now before, starting the server I have to

```c++
uint16_t getFreePort() {
    asio::io_service is;
    asio::io_service service;
    asio::ip::tcp::acceptor acceptor(service);
    asio::ip::tcp::endpoint endpoint(asio::ip::address::from_string(address), 0);
    acceptor.open(endpoint.protocol());
    acceptor.bind(endpoint);
    return acceptor.local_endpoint().port();
}
```
To get a free port and be able to send test requests. If the server had  a function `getServerPort`, then this could be avoided (and be more robust).

Cheers,

**Comment by The-EDev** [comment]
sorry for the late response, so the way I understand it when you set the port to 0, and the OS will give you a free port. if that is correct then I should change the terminal report to use ASIO's port rather than the user input
