### ISSUE TITLE
Add a catch-all handler as an alternative to returning 404

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/crow#123]
pretty self explanatory. based on #121 #122.

**Comment by Tibbel** [comment]
thanks for your fast reply and the adding it into a new branch.
i just needed this feature for own routing functions and error pages, so coding style wasn't a point for me.
but when i saw somebody is maintaining the old repo, i was thinking it's a nice feature also others could be interested in
and merging it into the main branch reduce the need for me patching it by every release.
feel free to modify it and bring it into a uniform coding style to crow, but please keep it as simple as the example shows.

THANKS

**Comment by The-EDev** [comment]
if anyone knows ho to use references instead of pointers in lines `34` and `72` [here](https://gist.github.com/The-EDev/740d85d23da2e30480b5a5fc9357b999) without getting a `bad_function_call` on execution I would be very thankful.

**Comment by mrozigor** [comment]
It looks like in 'reference version' `handler_` in line `12` lambda is created locally and assigned. Then it is destroyed - at least it looks like this is the problem.

**Comment by The-EDev** [comment]
> It looks like in 'reference version' `handler_` in line `12` lambda is created locally and assigned. Then it is destroyed - at least it looks like this is the problem.

Yeah I figured as much, not sure how to fix it though

**Comment by mrozigor** [comment]
Something like this - https://gist.github.com/mrozigor/69be5e9fa2a1fa6ce62bfac976e6c564 ?

**Comment by The-EDev** [comment]
wow, that works, thanks!
