### ISSUE TITLE
JavaScript Fetch() not working witch Crow on Firefox

### ISSUE THREAD

**Issue by dspverden** [CrowCpp/crow#131]
Hello,

I have the following issue:

My Crow app delivers a website that contains the following JavaScript code:
`function onLoad() {
  console.log("onLoad");
  fetch("/gui").then(function(response) {
    return response.text();
  }).then(function(res) {
    console.log(res);

  }).catch(function(err) { console.log(err); });
}  `

called by
`<body onload="onLoad()">`

For my crow app I have defined the following:
`  crow::SimpleApp app;

  CROW_ROUTE(app, "/") ([](const crow::request&, crow::response& res)
  {
    res.set_static_file_info("test.html");
    res.end();
  });
   

  CROW_ROUTE(app, "/gui")
    ([]() {
        return "Hello world!";
    });

  app.port(8080).run();`

When I type 0.0.0.0:8080 in Safari on macOS everything seems to be fine. I see my test page and in the console I read "Hello world".
But with firefox it does not work. There I read non-sense in the console. Things like: "function onL" at the same place where Safari show "Hello world!".
Any idea what could be wrong?
I guess something with the request response that Firefox cannot handle correctly...

Raphael

**Comment by The-EDev** [comment]
I hate to give a "Works on my machine" response...
![image](https://user-images.githubusercontent.com/60552923/115410900-b4603800-a1fb-11eb-860f-50d4b9e52dfe.png)

I got this by doing the following:

Created an empty `main.cpp` and `test.html`

Added `crow_all.h` file to the folder

added this to `main.cpp`:
```cpp
#define CROW_MAIN
#include "crow_all.h"

int main()
{
crow::SimpleApp app;

CROW_ROUTE(app, "/") ([](const crow::request&, crow::response& res)
{
res.set_static_file_info("test.html");
res.end();
});

CROW_ROUTE(app, "/gui")
([](){
return "Hello world!";
});

app.port(8080).run();
}

```

Added this to `test.html`:
```html
 <html>
 <head>
 <script>function onLoad() {
console.log("onLoad");
fetch("/gui").then(function(response) {
return response.text();
}).then(function(res) {
console.log(res);

}).catch(function(err) { console.log(err); });
}</script>
 </head>
<body onload="onLoad()">


</html>
```

Compiled with `g++ main.cpp -lpthread -lboost_system -lz`

Ran `./a.out`

Opened `http://localhost:8080/` in firefox (87.0 (64-bit) for Manjaro Linux).

I'm not sure what's causing your issue, but check the `Network` tab out, see if firefox is requesting `/gui`

**Comment by dspverden** [comment]
Hm, I tried your code, sometimes it works but it is not stable. Pressing reload button a few times makes it fail in 80% of all tries.

**Comment by dspverden** [comment]
A few more infos: When it fails the network tab of firefox reports "html" for the type in the line of the request.
If it goes fine it reports "plain".
So I gutes something is going wrong with the type of the response crow is sending.

**Comment by The-EDev** [comment]
might be related to #104, are you using `v0.2` or did you pull from master?

**Comment by dspverden** [comment]
Ah, I used release 0.2 let me just pull master, build crow_all.h and see what's happening then.

**Comment by dspverden** [comment]
Too bad after switching to master branch, I am now getting linker errors:
crow::mime_types and crow::detail::dumb_timer_queue::tick are unknown symbols now. So I have to see how to fix this now.

**Comment by The-EDev** [comment]
oh that's simple, just add `#define CROW_MAIN` at the top of your cpp file

**Comment by dspverden** [comment]
great now it is working stable with firefox. I will repeat the test then with sending a json object (because that is, was I finally want to do) and close the issue if that works, too. Thank you so far!

**Comment by The-EDev** [comment]
No problem, Let me know if you have any problems along the way.

**Comment by dspverden** [comment]
JSON response is now working, too. Thanks for the support!
