### ISSUE TITLE
json::rvalue dump constness

### ISSUE THREAD

**Issue by belugum** [CrowCpp/crow#133]
Hi!

I'm wondering why the crow::json::rvalue::dump method is not `const`. I'm trying to use it on a `crow::json::rvalue const &` and it can't compile. That method shouldn't modify my object so I don't understand.
I changed the constness of the related methods in my `crow_all.h` file (dump, dump_internal, dump_string, trim, pad), and it compiles and works well.

If there is no particular reason for that I can open a pull request correcting that. 

Thanks!

**Comment by The-EDev** [comment]
Hello, Thanks a lot for pointing out the issue.. It's most likely me not being used to C++, as a rule of thumb, make your change then build the tests and examples and run the tests, if there's no problem, open a PR.
