### ISSUE TITLE
Possible make uninstall rule for CMake?

### ISSUE THREAD

**Issue by ayaankhan98** [CrowCpp/Crow#138]
In #80 CMake install rules were merged. Should we also support `make unistall` to remove those files (in case if required).

**Comment by The-EDev** [comment]
Sure, feel free to open a PR making the rule. Thanks!

**Comment by ayaankhan98** [comment]
As far as i know, :thinking:  CMake does not offer any direct feature to write unistall rules (Unlike the case of install rules). Therefore, we have to choose someother way to achieve this.

**Comment by The-EDev** [comment]
perhaps take a look at https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake

**Comment by ayaankhan98** [comment]
> perhaps take a look at https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake

Thanks :+1:  , i had seen that earlier. I just mentioned that point because in case if someone else is going to take this issue then that information will help.
