### ISSUE TITLE
Using different JSON parser?

### ISSUE THREAD

**Issue by alejandroarmas** [CrowCpp/crow#146]
Hello again!

I believe I saw in the original repo for crow that crow was interoperable with different json parser/generator libraries, is there a recommended way of integrating something like rapidjson in a crow endpoint? I couldn't find any documentation about this topic. 

Is it simply a matter of using the `body` public member of a request object? and then throwing a generated json into the `response (int code, std::string body)`?

Thanks in advance!

**Comment by alejandroarmas** [comment]
This ended up working fine with RapidJson, think I answered my own question

```c++
 CROW_ROUTE(app, "/issueTransactionRJ")
    .methods(crow::HTTPMethod::PUT)
    ([](const crow::request& req)
    {
        
        Document document, tx_json;

        tx_json.Parse(req.body.c_str());


        if (tx_json.HasMember("transactions")) {
            const Value& tx_array = document["transactions"];

            for (auto& t : tx_array.GetArray()) {
                for (auto& op : t.GetObject()) {
                    operations.emplace_back(op.value.GetInt());                    
                }
                transactions.emplace_back(operations);
                operations.clear();
            }

        }
        Document::AllocatorType& a = document.GetAllocator();
        Value status;
        status.SetObject();
        status.AddMember("status", "Ok", a);
        
        document.Swap(status);
        StringBuffer buffer;
        PrettyWriter<StringBuffer> writer(buffer);
        document.Accept(writer);

        return crow::response(200, buffer.GetString() + std::string("\n"));
    });
    app.port(18001).run();

```

**Comment by The-EDev** [comment]
Hi.
If you're looking for just a quick and dirty solution, then all you need to do is set `response.body` to the output json string, and set the header `Content-Type` to `application/json`.

The above method is how the old repo worked. With Crow v0.3 a new class named `crow::returnable` was added. 
The idea is for you to write your own class extending `returnable`, add your favorite json class as a variable, assign the `content-type` variable and finally override the `dump()` method (by inserting your json library's `JSON -> String` method in there).
This will allow you to write `return my_returnable_class;` inside your `CROW_ROUTE`

The Crow guide does contain a section on [Returning Custom Classes](https://crowcpp.org/guides/routes/#returning-custom-classes).

**Comment by The-EDev** [comment]
> This ended up working fine with RapidJson, think I answered my own question
> 
> ```c++
>  CROW_ROUTE(app, "/issueTransactionRJ")
>     .methods(crow::HTTPMethod::PUT)
>     ([](const crow::request& req)
>     {
>         
>         Document document, tx_json;
> 
>         tx_json.Parse(req.body.c_str());
> 
> 
>         if (tx_json.HasMember("transactions")) {
>             const Value& tx_array = document["transactions"];
> 
>             for (auto& t : tx_array.GetArray()) {
>                 for (auto& op : t.GetObject()) {
>                     operations.emplace_back(op.value.GetInt());                    
>                 }
>                 transactions.emplace_back(operations);
>                 operations.clear();
>             }
> 
>         }
>         Document::AllocatorType& a = document.GetAllocator();
>         Value status;
>         status.SetObject();
>         status.AddMember("status", "Ok", a);
>         
>         document.Swap(status);
>         StringBuffer buffer;
>         PrettyWriter<StringBuffer> writer(buffer);
>         document.Accept(writer);
> 
>         return crow::response(200, buffer.GetString() + std::string("\n"));
>     });
>     app.port(18001).run();
> ```

Your code doesn't set the `Content-Type` header, which might cause clients to interpret your response as text rather than JSON.

**Comment by alejandroarmas** [comment]
> > This ended up working fine with RapidJson, think I answered my own question
> > ```c++
> >  CROW_ROUTE(app, "/issueTransactionRJ")
> >     .methods(crow::HTTPMethod::PUT)
> >     ([](const crow::request& req)
> >     {
> >         
> >         Document document, tx_json;
> > 
> >         tx_json.Parse(req.body.c_str());
> > 
> > 
> >         if (tx_json.HasMember("transactions")) {
> >             const Value& tx_array = document["transactions"];
> > 
> >             for (auto& t : tx_array.GetArray()) {
> >                 for (auto& op : t.GetObject()) {
> >                     operations.emplace_back(op.value.GetInt());                    
> >                 }
> >                 transactions.emplace_back(operations);
> >                 operations.clear();
> >             }
> > 
> >         }
> >         Document::AllocatorType& a = document.GetAllocator();
> >         Value status;
> >         status.SetObject();
> >         status.AddMember("status", "Ok", a);
> >         
> >         document.Swap(status);
> >         StringBuffer buffer;
> >         PrettyWriter<StringBuffer> writer(buffer);
> >         document.Accept(writer);
> > 
> >         return crow::response(200, buffer.GetString() + std::string("\n"));
> >     });
> >     app.port(18001).run();
> > ```
> 
> Your code doesn't set the `Content-Type` header, which might cause clients to interpret your response as text rather than JSON.

Thank you so much I didn't realize that could be problematic! I'll edit the code above in case anybody else stumbles upon this same question. I'll definitely check out the custom class too thanks man!

**Comment by The-EDev** [comment]
No problem, let me know if there's anything else you need help with, or if you have any suggestions to improve Crow.
