### ISSUE TITLE
Accessing the first Request on a WebSocket Connection

### ISSUE THREAD

**Issue by ArthoPacini** [CrowCpp/crow#148]
First of all I want to thank those involved in this project for keeping it alive, it's one of the best tools for C++ in terms of simplicity to enable HTTP/WebSockets connections.

I'm building a Rest API and a WebSockets API for my website, the problem I am facing is authentication
I already have the authentication system working, when someone successfully logs in, the server reply with headers like:

`res.set_header("Set-Cookie", "Auth=123; Secure; HttpOnly");`

and some more stuff like Max-Age etc.. so this sets a cookie on the client browser, so all next requests will automatically sent this cookie with it for authentication

But the client can connect into the API using a WebSocket connection, and perform the same actions that would need authentication.

Because of the 'HttpOnly' cookie flag, the cookie cannot be read by Javascript and be sent as the first message to the server, this would be necessary to identify the client on the server side.

The WebSocket connection starts with an HTTP request and gets upgraded to a WebSocket connection, but it isn't exposed by `crow::websocket::connection `, so there's no way to access the first request that got upgraded to a WebSocket connection, if this could be possible, it would make easy for the server to identify WebSocket connections and make it secure by not necessarily having to pass it as a message (so cookie would need to be accessible by Javascript).

I've got a temporary solution, to save the first request as member function and make it accessible.

I've added this virtual function `get_open_connection_request()` at the connection struct

![image](https://user-images.githubusercontent.com/22568556/121842140-3168d480-ccb6-11eb-97cc-8664ef5443ab.png)

On the constructor i've added this line `open_connection_request = req;`, just copying the request;

![image](https://user-images.githubusercontent.com/22568556/121842422-c53aa080-ccb6-11eb-8492-11b0ef911d3c.png)

Then just a function override to get a reference to it 

![image](https://user-images.githubusercontent.com/22568556/121842540-f4511200-ccb6-11eb-8257-bdd6475d2e72.png)

And just declare the member

![image](https://user-images.githubusercontent.com/22568556/121842678-2c585500-ccb7-11eb-9c75-02fe375f8037.png)

Now I can get the auth cookie on the `onopen()` function and store the connection with the authentication, so I know who this client is now, the downside is that the entire request object stays with it.. (i am using the websocket example)

![image](https://user-images.githubusercontent.com/22568556/121842740-50b43180-ccb7-11eb-9386-ac924834c02b.png)

How could this be improved?

Thank you very much!!

**Comment by The-EDev** [comment]
Hi, Thanks for your work. This unfortunately seems to be a documentation problem but the initial HTTP request you're looking for is available in the `onaccept` handler. Which executes before the handshake even starts. here's an example:
```cpp
CROW_ROUTE(app, "/ws").websocket()
.onaccept([&](crow::request req)
{
    return true; //returning false would cause the connection to close
});
```
While this handler is mentioned [here](https://crowcpp.org/guides/websockets), I'm guessing it needs more detail.

I'm sorry you went through the trouble of making your own implementation. I'll try to make the documentation more clear on this.

I'll close this issue, feel free to reopen it if I got it all wrong and your problem isn't solved.
