### ISSUE TITLE
Basic Authentication?

### ISSUE THREAD

**Issue by codic12** [CrowCpp/crow#154]
Maybe I'm blind but I can't see how to do simple basic authentication in Crow, are there any examples?

Thanks for forking & maintaining crow!

**Comment by The-EDev** [comment]
Hi, please take a look at #144. I've mentioned there my own token based authentication, and how it can be modified for basic HTTP authentication. Another member Also posted about using session tokens and provided his way of doing so.

Let me know if you need anything else.

**Comment by The-EDev** [comment]
Maybe adding a guide on how this can be done would be a good idea, if anyone is interested in taking the code from #144 and adding a bit of description in MarkDown format I would happily add it to the guide :)

**Comment by codic12** [comment]
Got it, thanks for your quick reply!
