### ISSUE TITLE
response from another function other than CROW_ROUTE

### ISSUE THREAD

**Issue by gsp26** [CrowCpp/crow#167]
want to break the chain before sending response..how can i send response to a http req from another thread or method other than CROW_ROUTE.

**Comment by The-EDev** [comment]
The request object contains a pointer to an `asio::io_service` which can be used, there's a version in branch res-push whose request contains the adaptor object as well. But you'll still need some hacking into the code to get things done.

Could you explain what you're trying to do? maybe there's a different approach to get it done.

**Comment by gsp26** [comment]
what i mean is i want to send response of any HTTP req asynchronously. save the resp object and do return from some another function other than from CROW_ROUTE(app, "/"){} method.

**Comment by The-EDev** [comment]
I would suggest blocking the thread running `CROW_ROUTE` until data is asynchronously retrieved and then just simply returning it. saving the response for later could introduce problems specifically with timeouts and how they're executed.

You could get what you want exactly with res-push (specifically the part where requests contain the tcp adapter where data is transferred) but supporting it officially would require a lot of work and rule breaking, and is quite unlike to happen.

**Comment by gsp26** [comment]
Thanks will try that

**Comment by The-EDev** [comment]
Let me know how it goes, feel free to reopen this issue if you have any more questions or something else is up and the suggestion is incomplete or doesn't work.
