### ISSUE TITLE
utf8 support?

### ISSUE THREAD

**Issue by crisclacerda** [CrowCpp/crow#168]
I am getting started with crow but I am missing utf8 support.
Here is the simplest example..
```
int main() {
    crow::SimpleApp app;
    CROW_ROUTE(app, "/")
    ([](){
        return crow::response("á â ã ç");
    });
    app.port(18080).multithreaded().run();
}
```
On browser it shows:
Ã¡ Ã¢ Ã£ Ã§

**Comment by The-EDev** [comment]
Crow by default doesn't use utf-8, this is how you can enable it:
```cpp
crow::response res ("á â ã ç");
res.set_header("Content-Type", "text/plain; charset=utf-8");
return res;
```
@mrozigor do you think we should change the default response to support utf8 or keep it as is?

**Comment by crisclacerda** [comment]
Awesome, thanks for the quick reply!
Is there a way to change this configuration globally so I don't have to set it for every response?

**Comment by The-EDev** [comment]
You could add the following lines to `crow::response::end()`:
```cpp
if (get_header_value("Content-Type") == "")
    add_header("Content-Type", "text/plain; charset=utf-8");
```
(I haven't tested it but it should work)
It's line 156 in `http_response.h` or 3012 in `crow_all.h` for `v0.3+2`

I'm gonna look into supporting this officially. Thanks for pointing it out!

**Comment by crisclacerda** [comment]
Awesome thanks.

**Comment by mrozigor** [comment]
> Crow by default doesn't use utf-8, this is how you can enable it:
> 
> ```c++
> crow::response res ("á â ã ç");
> res.set_header("Content-Type", "text/plain; charset=utf-8");
> return res;
> ```
> 
> @mrozigor do you think we should change the default response to support utf8 or keep it as is?

I think it is a good idea to make utf8 default.
