### ISSUE TITLE
Support UTF-8 through a middleware

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#169]
as mentioned in #168, set a default content type of `text/plain; charset=utf-8`

**Comment by crisclacerda** [comment]
I could tackle this as a good first issue, is the suggestion you made on [here](https://github.com/CrowCpp/crow/issues/168#issuecomment-882910442 ) the only thing that needs to be changed, or is there something else?

**Comment by The-EDev** [comment]
Thanks a lot, it should just be the suggestion I made

**Comment by The-EDev** [comment]
I've given this some thought. it might be best to create a middleware instead of just adding it to crow proper since some people might not want `content-type` to be populated
