### ISSUE TITLE
HTTP server not recieving any messages after some time

### ISSUE THREAD

**Issue by gsp26** [CrowCpp/Crow#182]
I have implemented a HTTP server with single POST method handling. testing the same with jmeter with 600 users.

after some time the server does not receive any requests, kind of gets stuck. the maximum connection limit on my server is host is good enough. and after restarting the jmeter it again kind of stops after some time. 

when its not receiving any messages i see i have 600 connections in established state( as testing with 600 users from jmeter)

Any idea what I could be missing?

**Comment by The-EDev** [comment]
Hi @gsp26, Thanks a lot for finding out about this. I'll investigate it right now. But could you tell me which version of Crow you're using?

Thanks.

**Comment by gsp26** [comment]
i am using crow_all.h

**Comment by The-EDev** [comment]
from a release? or master branch?

**Comment by gsp26** [comment]
from releases , I think I have an old one its 309 KB. now trying with complete crow repo

**Comment by The-EDev** [comment]
The only release I can see that comes close is `v0.1`. which was made before this repo

**Comment by gsp26** [comment]
does it matter if I have only one Route for POST method ..and I am also sending that one only.
let me try with latest v0.3+2 hotfix

**Comment by The-EDev** [comment]
after 35 minutes of load testing, I got a max of 2 second response time, which was likely caused by my CPU core being occupied since the logging text was freezing along with the program, here are the results from wrk (I cut it after 35 minutes because I needed to use the workstation):
```
Running 120m test @ http://0.0.0.0:18080/
  10 threads and 600 connections
 Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   111.84ms  276.42ms   2.00s    90.67%
    Req/Sec     2.81k   621.96    11.44k    88.94%
  49261310 requests in 35.42m, 5.00GB read
  Socket errors: connect 0, read 0, write 0, timeout 13342
Requests/sec:  23179.91
Transfer/sec:      2.41MB

```

**Comment by gsp26** [comment]
can you test it with 600 threads..1 thread each connection .. what does this mean 10 threads 600 conections ? 
i got issues even with simple echo http server. 

do i need more handling other than only POST route ?

**Comment by gsp26** [comment]
also if possible check from different machines ..i.e client on different machine

**Comment by The-EDev** [comment]
>  can you test it with 600 threads..1 thread each connection

I actually can't, I got an error when attempting it, in addition to the fact that you don't want to have more threads created than your cpu can support (12 in my case).

> what does this mean 10 threads 600 conections ?

wrk can do more than 1 connection per thread, so in this case it was running 600 connections on 10 threads, 60 per thread.

> do i need more handling other than only POST route ?

You shouldn't..

**Comment by belugum** [comment]
I have the same issue. It turns out sometimes one request is stuck in an infinite loop (on my side). 

When that happens some requests are not received on the server. I am testing that with `while true; do time curl --location --request GET 'localhost:18080/'; done`: it gets stuck ramdomly after less than 20 requests with the server not showing any log of the last request (that route only returns Hello World so it can't get stuck on my side). Also the program does not close on SIGTERM, it waits for all requests to end apparentely, I have to kill it using SIGKILL.

I understand that I should find and fix my infinite loop / deadlock, but what can we do to make sure the server receives all requests even when a thread is stuck?

I am currentely testing with crow commit e87ec70179bd88f34a031b23420efcc8bc84124f (last week).

Thanks!

**Comment by The-EDev** [comment]
@belugum your issue seems to align more with #258 than this one

**Comment by The-EDev** [comment]
@gsp26 Could you run your test again? I'll run my own tests and check if the rare 2 second delay is resolved.

**Comment by The-EDev** [comment]
New test results, using 12 threads and for 30 minutes this time instead:
```
Running 30m test @ http://0.0.0.0:18080
  12 threads and 600 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    35.42ms    3.95ms  89.41ms   72.17%
    Req/Sec     1.42k    33.18     3.13k    69.31%
  30488858 requests in 30.00m, 3.12GB read
Requests/sec:  16937.51
Transfer/sec:      1.78MB
```
While the request time is still a bit long, especially the max time. it is much lower on all measurements. (`89.41ms` while a bit long, is nowhere near `2000ms`). It seems that #289 did the trick, or at least is a step towards getting this whole thing solved.

One other thing to mention is that my machine only has 6 cores. And while yes it does support hyper-threading, 6 threads is still the optimum number. And I was running 24 (25 if you count the acceptor thread)

**Comment by The-EDev** [comment]
I'll be closing the issue for now due to a lack of response, and since the problem I was facing was fixed.

If anyone else is facing the issue described please comment here so it can be reopened.

**Comment by Borwe** [comment]
Not reporting problem, but would like to know what you are using for testing?

**Comment by The-EDev** [comment]
@Borwe I'm using [`wrk`](https://github.com/wg/wrk/)
