### ISSUE TITLE
regarding websockets 

### ISSUE THREAD

**Issue by chromafunk** [CrowCpp/Crow#183]
I am developing an app that receives a data through a ZMQ socket every second, then processes it and prepares it in JSON format, and my goal was to be able to stream this real time data contiguously serving it through websockets, so a React app can grab it and make visuals with it.

My questions:

is it possible to stream JSON data regardless of if a client is connected to the endpoint, and once the client connects, it starts doing something with the data the server is streaming ?

Since there is no example, could you roughly point out to a basic example where I simply stream the results of socket read / parse to a websocket that will later be queried by a client ? ( the client will be the react app so it's just the server that I need to figure out )

Thanks !

**Comment by The-EDev** [comment]
> is it possible to stream JSON data regardless of if a client is connected to the endpoint

No, ASIO (The TCP library Crow uses) can only read from / write to an endpoint. What you can do however is process the data into JSON, store it either in memory or storage, and then begin streaming it once a client connects.

To do that all you really need to do is save the `crow::websocket::connection` object once the client connects and then simply use the connection's `send_text()` method to send your json data whenever updated.

Currently the guide only talks about websocket routes. but you can find documentation on websocket connections in the API reference.

Let me know if this answers your question.

**Comment by The-EDev** [comment]
Closing this issue for now, feel free to reopen if your question wasn't answered.
