### ISSUE TITLE
crow::json::wvalue lacks an 'object' initialization and assignment.

### ISSUE THREAD

**Issue by lcsdavid** [CrowCpp/Crow#189]
## `crow::json::wvalue` lacks an explicit `object` initialization and assignment.

Currently to initialize a `crow::json:wvalue` we need to default construct the object and then populate values, hence some trivial operations are needlessly more wordy, or can be more straightforward and might be even more efficient (in-place construction optimisation, ...).

##### Classic object initialization
```cpp
/* let's suppose that mentionned variables exist in this scope. */
crow::json::wvalue result;
result["username"] = username;
result["email"] = email;
result["firstname"] = firstname;
result["lastname"] = lastname;
return result;
```

##### Empty object initialization (`{}`)
```cpp
crow::json::wvalue result = crow::json::load("{}");
```

#### Proposals

By adding those proposals, object constructor can be more explicit and semantically accurate regarding to syntax.

##### `std::unordered_map<std::string, wvalue>` or `std::map<std::string, wvalue>`, `const&` and `&&`, constructors and assignements.
```cpp
/* let's assume that mentionned variables exist in this scope. */
std::unordered_map<std::string, crow::json::wvalue> map =  {
/* might need to explicitly use std::pair here. */
  {"username", username},
  {"email", email},
  {"firstname", firstname},
  {"lastname", lastname}
};

crow::json::wvalue result = map;
crow::json::wvalue result =  std::move(map); 

/* let's ignore that map as been moved. */
result = map;
result = std::move(map);

/* can now create an empty object like this. */
/* rvalue constructor is called here so map construction is certainly in-placed if well done. */
crow::json::wvalue result = std::unordered_map<std::string, crow::json::walue>(); 
```

##### `std::initializer_list<std::pair, wvalue>` contructor and assignment.

```cpp
/* let's assume that mentionned variables exist in this scope. */
crow::json::wvalue result =  {
/* might need to explicitly use std::pair here. */
  {"username", username},
  {"email", email},
  {"firstname", firstname},
  {"lastname", lastname}
};

result = {
/* might need to explicitly use std::pair here. */
  {"username", username},
  {"email", email},
  {"firstname", firstname},
  {"lastname", lastname}
};
```

Is there an interest into those proposals ? May I PR sometime soon ?

**Comment by The-EDev** [comment]
Hi @lcsdavid, There absolutely is interest in every new addition or improvement. Thanks for pointing this out and proposing a solution. A PR would be great, and if you want to go the extra mile you can add to the existing examples and unit tests. Though it's not strictly necessary.

Thanks again for pointing out both the problem and a solution.

**Comment by lcsdavid** [comment]
I'll do a PR probably this week-end so. Thanks for your feedback.
