### ISSUE TITLE
Returning basic types: int,float,double, etc?

### ISSUE THREAD

**Issue by Iuliean** [CrowCpp/Crow#193]
Is this something that can be done ?
i've stripped my code down to this: 
`
CROW_ROUTE(this->app, "/getTemp").methods(crow::HTTPMethod::GET)([](){return 23.3f;});
` 
and  get  500 error everytime i access the endpoint

**Comment by The-EDev** [comment]
Your response body has to be string, in this case something like `return "23.3"` would work, if you want to return another type, you just have to turn it to string first (you can use `returnable` class for complex types)

**Comment by Iuliean** [comment]
well yeah but if i have something like `float value = 23.4;` if i do `return std::to_string(value);` it get's converted to `23.40000` or something like that i solved it by returning a json but that's a bit annoying

**Comment by The-EDev** [comment]
crow::json just uses `sprintf` to format the number, here's practically what it does:
```cpp
    double num = 23.3;
    char outbuf[128];
    sprintf(outbuf, "%g", num);
```
outbuf should contain the string `23.3` instead of `23.30000`.

I hope this helps

**Comment by Iuliean** [comment]
it's ok i can use json too

**Comment by The-EDev** [comment]
Alright, I'll close this issue since the question is answered :)
