### ISSUE TITLE
How am i supposed to handle cookies? 

### ISSUE THREAD

**Issue by Iuliean** [CrowCpp/Crow#194]
Am i supposed to parse them myself with `req.get_header_value()` ? From what i could gather from the ref page it seems like there is a middleware `CookieParser` and after a quick glance at the source it seems that it does parse the cookies but how do i access that if that's the case ?

**Comment by The-EDev** [comment]
in your handler (`CROW_ROUTE` function) you can use `auto& ctx = app.get_context<CookieParser>(req);` to get the middleware context then use `ctx.get_cookie("key1");`, this will return a string with the value of your cookie, you can also use `ctx.set_cookie("Key", "value");` to send a cookie to the client.

Let me know if something isn't working or if your question is unanswered.

**Comment by Iuliean** [comment]
I think i am doing something wrong
```cpp
CROW_ROUTE(this->app, "/dashboard").methods(crow::HTTPMethod::GET, crow::HTTPMethod::POST)
                            ([this](const crow::request req){
                                auto& ctx = app.get_context<CookieParser>();
                                return this->dashboard(req);});
``` 
code tells me that `identifier CookieParser is undefined`

**Comment by Iuliean** [comment]
Ops i am dumb it is `crow::CookieParser`.
Also just so i don't open up another issue.
I have a `/auth` endpoint where i make `POST` request and i send a password and if it's correct i return a cookie that has an authentification token and then i redirect to `/dashboard` but it redirects with a `POST` request am i doing something wrong in the response or is this because my form sends a `POST` request

**Comment by The-EDev** [comment]
>  but it redirects with a POST request am i doing something wrong in the response or is this because my form sends a POST request

You want your response code to be 303 and you want to set the Location header to "/dashboard", this will tell the client to use a GET request, I'll later add it as a redirection method to make things easier.

**Comment by Iuliean** [comment]
Ok thanks again

**Comment by The-EDev** [comment]
No problem :)
