### ISSUE TITLE
`remoteIpAddress` in `http_request.h` uses camel case instead of snake case

### ISSUE THREAD

**Issue by NoorWachid** [CrowCpp/Crow#199]
I read the code and saw `url_params` then `remoteIpAddress` as public API (not internal code) are you planning on refactoring the code?

**Comment by The-EDev** [comment]
The convention for variable names is snake case, the `remoteIpAddress` slipped through the cracks. Thanks for finding it, feel free to open a PR fixing it or find others to fix. We'll fix it as soon as we can now that we know of it :)

**Comment by himanshu007-creator** [comment]
hi i  would like to work on this issue!

**Comment by The-EDev** [comment]
sure thing @himanshu007-creator, go ahead and open a PR, I'll look into it and merge it :)
