### ISSUE TITLE
Detach this fork?

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#204]
Here's my thought process, we have our own logo, site, documentation, and a significant amount of original code. I would go as far as say it's a different framework with the same base. Maybe it's time to detach from ipkn's original repository.

I'm not aware of any disadvantages to this step, but I'm absolutely open to discussion and won't move forward without a second or third opinion, especially @mrozigor's.

**Comment by mrozigor** [comment]
I think that this shouldn't be a problem for us. You mentioned a lot of times about this fork on MRs in original repo. This fork is probably the most up-to-date and could continue as separate project. I think that this is a good idea :)
