### ISSUE TITLE
Better docs readability

### ISSUE THREAD

**Issue by ayaankhan98** [CrowCpp/Crow#214]
Any thoughts on changing the colorscheme of code sections to make it more readable? With current color scheme it is not comfortable to read.
![Screenshot_20210830_161404](https://user-images.githubusercontent.com/43348292/131327842-8eb979a4-cfe6-42f4-ade8-68ea77eb65ea.png)

**Comment by The-EDev** [comment]
I'm pretty sure that's not the current scheme, this is:

![image](https://user-images.githubusercontent.com/60552923/131328332-97877612-0f05-4c95-8bfe-bd54a89cdaf1.png)

**Comment by ayaankhan98** [comment]
I think both images are same? isn't? see the comments, aren't they less readable? black text over dark gray?

**Comment by The-EDev** [comment]
I'm guessing it's about the code comments, I already fixed this in my local repo, I'll update it on the next PR
