### ISSUE TITLE
application/x-www-form-urlencoded support?

### ISSUE THREAD

**Issue by mihdim777** [CrowCpp/Crow#215]
Hello!

Is there any support for this type of post? (`x-www-form-urlencoded`). 

I am trying to add this support in `multipart.h` but not success yet.
Here is some info about the request I am working with:

`Header: User-Agent : python-requests/2.22.0`
`Header: Accept-Encoding : gzip, deflate`
`Header: Accept : */*`
`Header: Connection : keep-alive`
`Header: Content-Length : 15`
`Header: Content-Type : application/x-www-form-urlencoded`
`Body: dirpath=C%3A%2F`

Thank you!

**Comment by The-EDev** [comment]
`x-www-form-urlencoded` places the data inside `crow::request::url_params`, multipart only deals with the `multipart` request body structure. They're very different from each other.

Crow does support URL encoded form submissions (even though it doesn't explicitly say so). All you need to do is run `req.url_params.get("form_field_name")` to get the values for the individual entries. Please go [here](https://crowcpp.org/guides/query-string/) for more information on url_params. And let me know if this answer solves your problem.

**Comment by mihdim777** [comment]
Hello!

Unfortunately it doesn't work. Here is a test method. 
It prints no keys. Also when I try to use .get method, it returns null.
Am I doing something wrong?


`
CROW_ROUTE(app, "/test").methods("POST"_method) ([](const crow::request& req, crow::response& res) {
		auto url_params = req.url_params;
		
		for (auto i : url_params.keys()) {
			std::cout << i << "\n";
		}

		res.body = "OK";
		res.end();
		return;
		});
`
 And here is a print screen from postman: 
![image](https://user-images.githubusercontent.com/81242256/132083607-82267a69-7860-473e-aa25-af6cb5e1e74e.png)

**Comment by The-EDev** [comment]
Hmmm, Alright this is my fault. It seems the way this works is that the request **body** contains the data, it's just formatted in a way similar to how `url_params` works. Crow doesn't directly support this at the moment. But as a workaround you can modify the request body as such:
```cpp
CROW_ROUTE(app, "/test").methods("POST"_method) ([](const crow::request& req, crow::response& res) {
		auto url_params = crow::query_string("?" + req.body);
		
		for (auto i : url_params.keys()) {
			//it is preferable to use CROW_LOG instead of std::cout, since the former contains date and time data, and automatically adds a newline
			CROW_LOG_INFO << "Key is - " << i; 
		}

		res.body = "OK";
		res.end();
		return;
		});
```
Might be worth adding a parameter to the query string constructor that does this automatically.

**Comment by mihdim777** [comment]
Noo, you don't have to apologize. Thank you again for your time and support!

I have tried this workaround with concatenating ?, and it works seamless. 
This methods also works if in body I have files? For example the json is something like this:

{'data': {param1=key1, param2=key2}, 'files': 'string of bytes'} 

Like `'/0x10/0x1A/0x2A/0x3A'`

**Comment by The-EDev** [comment]
This is very interesting, I'll take a look at files and see what format they're being sent in (and how `query_string` is detecting them). Thanks for letting me know

**Comment by SSIvanov19** [comment]
Hello,
 I just want to ask if this is still the way to access values ​​from the x-www-form-urlencoded body of the request?

**Comment by The-EDev** [comment]
Hi @SSIvanov19.
AFAIK this method is still valid
