### ISSUE TITLE
CrowCpp Sidebar broken

### ISSUE THREAD

**Issue by luca-schlecker** [CrowCpp/Crow#219]
I haven't extensively tested it, but it seems like the sidebar of [CrowCpp.org](https://CrowCpp.org) is broken.

![crowcpp org](https://user-images.githubusercontent.com/66110953/132860746-fb9f48a7-b798-4e16-b048-485101ce84c8.gif)

**Comment by The-EDev** [comment]
That's true, it does work on the other pages, only problem is that to have the front page occupy the full screen space, I had to disable the sidebar (`site_nav` in mkdocs), which from what I can see doesn't disable the sidebar button

**Comment by luca-schlecker** [comment]
Well, the navbar pops up horizontally and statically if the window is wide enough. But on a mobile, shouldn't there slide in a sidebar with the links to `API Reference` and so?

**Comment by The-EDev** [comment]
That would probably be Ideal, I just have to figure out how to completely hide the sidebar when the window is wide

**Comment by The-EDev** [comment]
I've just managed to fix the issue, I'll include it in the next change to `revamped_setup`
