### ISSUE TITLE
Return response from different thread?

### ISSUE THREAD

**Issue by tavoki2875** [CrowCpp/Crow#221]
Is it safe to pass the request/response to another thread and respond from there or must the request/response be accommodated within the scope of the CROW_ROUTE callback?

I saw advice elsewhere recommending someone with a similar question to use boost asio io_service/io_context but I'm not very familiar with boost and it's unclear to me how that would work with my own managed thread and while I can communicate data to my other thread via a queue I don't really have a mechanism to get data back out.

I have a multithreaded app with my own managed thread that owns certain data/resources. Rather than use locks to safely populate my response, I was wondering if it's possible to pass the request and/or response pointer to my own managed thread and have it produce the response and call `response::end()`? It's unclear to me if this is possible with respect to lifetime and threading within crow.

**Comment by The-EDev** [comment]
The problem is that internally Crow calls `response::end()` once the handler returns, so your best bet is to block the handler until the data is prepared, another problem is even if you disable the internal call, the timeout counter might also have undefined behavior because of this.

**Comment by tavoki2875** [comment]
Thanks for your response and that makes sense. I'll have to think about this some more then.

**Comment by luca-schlecker** [comment]
Maybe [std::promise](https://en.cppreference.com/w/cpp/thread/promise) can help you. Crow can be multithreaded, so waiting on the result shouldn't be a problem.

The promise should help you to safely get the response out of your thread and automatically wait until it has arrived.

**Comment by tavoki2875** [comment]
Thanks @luca-schlecker. std::promise has me up and running.
