### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by baylf2000** [CrowCpp/Crow#223]
I'm having a small issue with the latest project using vcpkg on windows. I get the following compilation errors.

`1>I:\vcpkg\installed\x64-windows\include\crow\json.h(749,47): error C2059: syntax error: '{'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(749,1): error C2143: syntax error: missing ';' before '{'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(749,1): error C2143: syntax error: missing ')' before ';'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(749,64): error C2059: syntax error: '&&'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(750,1): error C2143: syntax error: missing ';' before '{'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(750,62): error C2059: syntax error: '&&'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(751,1): error C2143: syntax error: missing ';' before '{'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(751,62): error C2059: syntax error: '&&'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(752,1): error C2143: syntax error: missing ';' before '{'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(752,1): error C2059: syntax error: ')'`

Any help would be much appreciated.

**Comment by The-EDev** [comment]
Are you using VCPKG download Crow itself or just to install the dependencies, if it's the second, which version of Crow did you get?

**Comment by baylf2000** [comment]
I just ran the single command `vcpkg install crow`.

`PS I:\vcpkg> ./vcpkg install crow
Computing installation plan...
The following packages will be built and installed:
    crow[core]:x64-windows -> 0.1-1
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\xyz\AppData\Local\vcpkg\archives\7a\7a59540e7c2cd0013fa1d18c3d4884952cd3e8c5.zip
Starting package 1/1: crow:x64-windows
Building package crow[core]:x64-windows...
-- Using cached I:/vcpkg/downloads/ipkn-crow-v0.1.tar.gz
-- Cleaning sources at I:/vcpkg/buildtrees/crow/src/v0.1-8ff486eabf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source I:/vcpkg/downloads/ipkn-crow-v0.1.tar.gz
-- Using source at I:/vcpkg/buildtrees/crow/src/v0.1-8ff486eabf.clean
-- Up-to-date: I:/vcpkg/packages/crow_x64-windows/include
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/app.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/ci_map.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/common.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/dumb_timer_queue.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/http_connection.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/http_parser_merged.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/http_request.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/http_response.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/http_server.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/json.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/logging.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/middleware.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/middleware_context.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/mustache.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/parser.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/query_string.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/routing.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/settings.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/socket_adaptors.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/TinySHA1.hpp
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/utility.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/websocket.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/share/crow/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\xyz\AppData\Local\vcpkg\archives\7a\7a59540e7c2cd0013fa1d18c3d4884952cd3e8c5.zip
Building package crow[core]:x64-windows... done
Installing package crow[core]:x64-windows...
Installing package crow[core]:x64-windows... done
Elapsed time for package crow:x64-windows: 401.8 ms

Total elapsed time: 2.158 s`

**Comment by The-EDev** [comment]
well it seems like you're getting the wrong version, it says `Using cached I:/vcpkg/downloads/ipkn-crow-v0.1.tar.gz`. Let me look further into it

**Comment by The-EDev** [comment]
Something doesn't add up, vcpkg.io refers to this repository with version `0.3.2`. Did you attempt to install an older version of Crow with vcpkg? maybe before this version got added to vcpkg?

I'm not 100% sure how to deal with this, but clearing some cache for vcpkg might solve the problem.

**Comment by baylf2000** [comment]
Yes I must have installed the original version a long time ago. I've tried clearing the vcpkg cache and download directories but it still pulls in ` https://github.com/ipkn/crow/archive/v0.1.tar.gz`.

Thanks for the help. It's obviously an issue with vcpkg caching the version to download somewhere. I'll keep looking. Thanks for the help.

**Comment by The-EDev** [comment]
Sorry I couldn't help enough. Maybe @luca-schlecker can help you more. He's the one maintaining the vcpkg package.

**Comment by baylf2000** [comment]
Ok, I upgrade vcpkg, and now its installing the correct version.

`PS I:\vcpkg> ./vcpkg install crow
Computing installation plan...
The following packages will be built and installed:
    crow[core]:x64-windows -> 0.3.2#1
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\xyz\AppData\Local\vcpkg\archives in 122 us. Use --debug to see more details.
Starting package 1/1: crow:x64-windows
Building package crow[core]:x64-windows...
-- Downloading https://github.com/CrowCpp/crow/archive/7e47d4c7ee548c5fd954efd82cfeed330a7823ea.tar.gz -> CrowCpp-crow-7e47d4c7ee548c5fd954efd82cfeed330a7823ea-1.tar.gz...
-- Cleaning sources at I:/vcpkg/buildtrees/crow/src/330a7823ea-7b949701b1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source I:/vcpkg/downloads/CrowCpp-crow-7e47d4c7ee548c5fd954efd82cfeed330a7823ea-1.tar.gz
-- Using source at I:/vcpkg/buildtrees/crow/src/330a7823ea-7b949701b1.clean
-- Up-to-date: I:/vcpkg/packages/crow_x64-windows/include
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/app.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/ci_map.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/common.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/compression.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/dumb_timer_queue.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/http_connection.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/http_parser_merged.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/http_request.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/http_response.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/http_server.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/json.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/logging.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/middlewares
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/middlewares/cookie_parser.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/middleware_context.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/mime_types.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/multipart.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/mustache.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/parser.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/query_string.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/returnable.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/routing.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/settings.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/socket_adaptors.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/TinySHA1.hpp
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/utility.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow/websocket.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/include/crow.h
-- Installing: I:/vcpkg/packages/crow_x64-windows/share/crow/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\xyz\AppData\Local\vcpkg\archives\62\62e2229663721c42e60c1e3e9aadc25e3d22b45dfeb405c1a14fe3dcb9dc2dce.zip
Installing package crow[core]:x64-windows...
Elapsed time for package crow:x64-windows: 1.464 s

Total elapsed time: 3.225 s`

However I'm still getting similar errors :(

`1>I:\vcpkg\installed\x64-windows\include\crow\json.h(879,47): error C2059: syntax error: '{'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(879,1): error C2143: syntax error: missing ';' before '{'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(879,1): error C2143: syntax error: missing ')' before ';'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(879,64): error C2059: syntax error: '&&'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(880,1): error C2143: syntax error: missing ';' before '{'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(880,62): error C2059: syntax error: '&&'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(881,1): error C2143: syntax error: missing ';' before '{'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(881,62): error C2059: syntax error: '&&'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(882,1): error C2143: syntax error: missing ';' before '{'
1>I:\vcpkg\installed\x64-windows\include\crow\json.h(882,1): error C2059: syntax error: ')'`

**Comment by luca-schlecker** [comment]
I will look into this. I'll report back on how it compiled for myself.

Meanwhile you can try the following:
- 1. Uninstall Crow. (`vcpkg remove crow`)
- 2. Delete every crow-related download in `${VCPKG ROOT}/downloads` (Files starting with `crow`)
- 3. Install Crow again. (`vcpkg install crow`)

**Comment by baylf2000** [comment]
> 
> 
> I will look into this. I'll report back on how it compiled for myself.
> 
> Meanwhile you can try the following:
> 
>     1. Uninstall Crow. (`vcpkg remove crow`)
> 
>     2. Delete every crow-related download in `${VCPKG ROOT}/downloads` (Files starting with `crow`)
> 
>     3. Install Crow again. (`vcpkg install crow`)

Yes I did this already, which didn't help. The thing that fixed the version problem, and allowed the correct crow version to download, was to run `git pull` in the vcpkg directory. I don't know why.

Unfortunately those errors above remain even with the latest version of crow.

**Comment by baylf2000** [comment]
Also, if I just download the "crow_all.h" file and use that, then it compiles successfully.

**Comment by luca-schlecker** [comment]
> > 
> > 
> > I will look into this. I'll report back on how it compiled for myself.
> > 
> > Meanwhile you can try the following:
> > 
> >     1. Uninstall Crow. (`vcpkg remove crow`)
> > 
> >     2. Delete every crow-related download in `${VCPKG ROOT}/downloads` (Files starting with `crow`)
> > 
> >     3. Install Crow again. (`vcpkg install crow`)
> 
> Yes I did this already, which didn't help. The thing that fixed the version problem, and allowed the correct crow version to download, was to run `git pull` in the vcpkg directory. I don't know why.
> 
> Unfortunately those compile errors above remain even with the latest version of crow.
> 

That's because crow stores its packages locally in the `ports` directory. By pulling the newest changes, this folder gets updated and with that the crow port.

**Comment by mrozigor** [comment]
On `vcpkg` output I see paths like this `I:/vcpkg/packages/crow_x64-windows/include/crow/json.h` and from your error it looks like other path `I:\vcpkg\installed\x64-windows\include\crow\json.h`. Are you sure that you are using version actually installed by `vcpkg`? Which version of compiler and standard are you using?

**Comment by luca-schlecker** [comment]
I couldn't reproduce your errors. I tried installing it and everything worked. Even after first installing v0.1 and then upgrading, I didn't run into any problems...

**Comment by luca-schlecker** [comment]
I agree with @mrozigor.

Your log of `vcpkg install crow` states, that the header files got installed to `I:/vcpkg/packages/crow_x64-windows/include/crow` while your compilation error occures in a file in `I:/vcpkg/installed/x64-windows/include/crow`.
The latter of which is what I would expect to be used, as vcpkg usually installs its ports to `${VCPKG_ROOT}/installed/<triplet>/`.

In theorie, if my assumption is right, if you'd copy every file from `I:/vcpkg/packages/crow_x64-windows/include/crow` to `I:/vcpkg/installed/x64-windows/include/crow`, your compile error should be disappearing...

Could you test that and report back?

**Comment by luca-schlecker** [comment]
Could you please upload the file (`I:\vcpkg\installed\x64-windows\include\crow\json.h`) leading to the compile error?

**Comment by luca-schlecker** [comment]
> On `vcpkg` output I see paths like this `I:/vcpkg/packages/crow_x64-windows/include/crow/json.h` and from your error it looks like other path `I:\vcpkg\installed\x64-windows\include\crow\json.h`. Are you sure that you are using version actually installed by `vcpkg`? Which version of compiler and standard are you using?

@mrozigor This is actually fine. I see the same path when I install Crow via vcpkg. But in the end, it all goes where it should (`I:\vcpkg\installed\x64-windows\include`).

**Comment by The-EDev** [comment]
Closing this issue for a lack of response, feel free to reopen it @baylf2000 if the issue isn't resolved.
