### ISSUE TITLE
Requests by Javascript client are blocked by CORS policy

### ISSUE THREAD

**Issue by lucadvp** [CrowCpp/Crow#224]
API requests received from Javascript client running in a modern browser, for example using standard fetch API, are subjected to CORS policy "access control" checks, which fail with the current default handling of OPTIONS requests (preflight). In Chrome development mode, some error similar to the following example may be logged:

_Access to fetch at 'http://myserver:5000/api/v2/some/endpoint' from origin 'http://myclient:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
MySource.js:53 PATCH http://myserver:5000/api/v2/some/endpoint net::ERR_FAILED_

This is observed using the current CrowCpp master commit cf864709c06ff19f7f219c9f2e933921c3003597. As a work-around, one can add a couple of wildcard CORS permission headers to the Crow internal OPTIONS request handling (CORS pre-flight), in the include/crow/routing.h, line 1590

res.set_header("Access-Control-Allow-Origin", "*");
res.set_header("Access-Control-Allow-Headers", "Content-Type");
res.set_header("Access-Control-Allow-Methods", "PUT,POST,GET,DELETE,OPTIONS,PATCH");

**Comment by The-EDev** [comment]
While the workaround works, I would much prefer something like being able to modify the OPTIONS and HEAD headers initially, followed by proper CORS support either in the core, or through a middleware.

**Comment by dranikpg** [comment]
This should be a perfect fit for local middleware if we adopt it.
We could have middleware for setting the global CORS policy and local middleware for overriding it for handlers.

**Comment by The-EDev** [comment]
@dranikpg I agree, proper middleware support will open the door for supporting a lot of grey area features, where they're not part of HTTP but are still quite important for a server's functionality.

**Comment by dranikpg** [comment]
@The-EDev Hi! I've marked my PR to be ready for review a few days ago. No reason to hurry, just a friendly ping in case you missed it 😅
