### ISSUE TITLE
Need a suitable ORM

### ISSUE THREAD

**Issue by evilprince2009** [CrowCpp/Crow#235]
Don't know which is the most suitable ORM for Crow. It would be nice if Crow has something similar to Entity Framework.

**Comment by The-EDev** [comment]
I don't have as much experience in this as I would like to. But the original Crow project suggests [sqlpp11](https://github.com/rbock/sqlpp11). It's also what I personally use in my Crow project.

**Comment by The-EDev** [comment]
Closing this issue for now, please let me know if the answer was Inadequate and I'll reopen the issue.
