### ISSUE TITLE
websocket.h warnings with MSVC

### ISSUE THREAD

**Issue by Majestro000** [CrowCpp/Crow#236]
C:\Users\Megaport\Downloads\vcpkg-master\installed\x86-windows\include\crow\websocket.h(197): warning C4267: '+=': conversion from 'size_t' to 'char', possible loss of data

![image](https://user-images.githubusercontent.com/87878818/136101709-6b8c7b0a-e762-459c-8458-d7044b1c1f7d.png)

C:\Users\Megaport\Downloads\vcpkg-master\installed\x86-windows\include\crow\websocket.h(413): warning C4244: '=': conversion from 'uint64_t' to 'size_t', possible loss of data

![image](https://user-images.githubusercontent.com/87878818/136101819-13dee1ad-7495-4487-a1ee-c0fbd7165470.png)

Bye

**Comment by The-EDev** [comment]
> It is already fixed in source. Only vcpkg has old version.

Then I guess there's no reason for this issue to stay open.
