### ISSUE TITLE
v0.3+3 Release

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#244]
Cherrypick the fixes for #195 (#196), #236 (#174), ~and possibly #240 (#241)~ into branch v0.3 and make a release.

**Edit**: #240 isn't needed for `v0.3` since it works as intended

**Comment by luca-schlecker** [comment]
Will do. 👍

**Comment by luca-schlecker** [comment]
> Release made, DEB and AUR packages updated, only Conan and VCPKG are left. I'll submit an issue for Conan, @luca-schlecker could you please update VCPKG?
> 
> **Edit**: Issue made ([conan-io/conan-center-index#7687](https://github.com/conan-io/conan-center-index/issues/7687))

Vcpkg port update for `v0.3+3` was merged. 👍
