### ISSUE TITLE
Moving crowcpp.org to a VPS

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#259]
It might be a good idea to move crowcpp.org from gh-pages to its own server, this will allow a few things:
- Run web applications instead of plain html documents.
- Set up other services (like video chatting, analytics, etc..) to ease with development.
- Proper HTTPS support since github's is quite broken ATM.

This will require us to modify `generateDocumentationAndDeploy.sh` to upload the results to the server rather than github, which will probably also require a webhook to update the data.

This issue is open for discussion.

**Comment by The-EDev** [comment]
@mrozigor @luca-schlecker What are your opinions on this?

**Comment by luca-schlecker** [comment]
On first thought, it adds a constant cost. Video chatting could be handled through a community discord (by the way, that could be generally something interesting to look into). I can't really make a decision on it, as you will be the one looking after it (at least I guess so). The decision is yours. I personally don't quite see the specific need for it, but I could be easily wrong.

**Comment by The-EDev** [comment]
My rationale is that I'm already hosting the analytics for crowcpp.org on my server, using my domain currently, moving the actual site over would let me use the crowcpp.org instead of my own, plus other potential things in the future. I am also looking at separating the documentation into its own repository, and using a VPS would help with that since we'd be off the github infrastructure already.

You are correct in that there isn't a need for it, it's more of a setup for when there might be a need.

**Comment by Leon0402** [comment]
> Video chatting could be handled through a community discord (by the way, that could be generally something interesting to look into)

I wouldn't choose discord as it's the worst regarding data protection. It reads **all** data and can use them however they like. 

Instead, one of the plenty alternatives should be considered. Most interesting might be Matrix. Gitter is basically already matrix and in fact the current room works perfectly well with matrix. Matrix provides things like video chatting and was used for Fosdem for example. Nevertheless, it has some problems and is not as stable / good as alternatives, it is actively developed and probably needs more time to be a full replacement for things like discord. 
If functionality is more important than Telegram might be an option as well. Not perfect either regarding data protection, but still way better than discord. It doesn't have the concept of a "server" though. 
It can also be used a combination, for example gitter / matrix with jitsi for some calls or something like that. 

Personally, I think matrix should be chosen even if it doesn't offer everything discord might have and have some bugs. A great open source library shouldn't use closed source data selling discord in my opinion :-) 


> I am also looking at separating the documentation into its own repository

You're sure about this? I think the burden to do documentation properly is a lot lower if it's in the same repo. Say I'm a new developer or just want to open a PR for my one cool new thing. It would really suck to have to open a second PR for documentation. In my experience separation will lead to an out of date documentation. 
Also it's not possible or a lot harder to have documentation for a specific branch / git tag

Except from that I think using a separate server is fine as long as it's really necessary. The contra has already been said regarding costs. You already have a server currently, so no additional costs, right now, but what's about the future? Also the site will then be on a server nobody, except you perhaps, has control over. That might be fine as you're the maintainer of the project, but presumably it's still not ideal.

**Comment by The-EDev** [comment]
I fully agree with the points about discord, I personally like Matrix/Jitsi.

Regarding the separate repos, My concern is the project size, as someone cloning Crow will also have to clone the documentation (and all the associated assets) which make it considerably larger than it needs to be. Though your points are still valid.

I also agree with your points about future proofing the site, but it's worth stating why I thought of it to begin with,it seems that Github keeps some form of record / tracks users who visit the site, though none of that information is made available to the developers, the only info I have access to is the weekly visits to the repository, which is nowhere near what is being collected. I obviously don't like that and want things to be transparent. Hence why I set up Matomo to begin with.

**Comment by The-EDev** [comment]
Closing this issue until Crow is on more stable footing. Stable enough to where it's almost inconceivable to meet a fate similar to the original repository.
