### ISSUE TITLE
Apps are not independent of each other due to `dumb_timer_queue`.

### ISSUE THREAD

**Issue by luca-schlecker** [CrowCpp/Crow#264]
`dumb_timer_queue::tick` is shared between all apps, leading them to influence each other.
https://github.com/CrowCpp/Crow/blob/6f2eedaf9bcae84c91a419b0c86d87284235d982/include/crow/dumb_timer_queue.h#L17-L20
https://github.com/CrowCpp/Crow/blob/6f2eedaf9bcae84c91a419b0c86d87284235d982/include/crow/app.h#L120-L125

`dumb_timer_queue` notably appears in the following files:
- [http_server.h](https://github.com/CrowCpp/Crow/blob/6f2eedaf9bcae84c91a419b0c86d87284235d982/include/crow/http_server.h)
- [http_connection.h](https://github.com/CrowCpp/Crow/blob/6f2eedaf9bcae84c91a419b0c86d87284235d982/include/crow/http_connection.h)
- [app.h](https://github.com/CrowCpp/Crow/blob/6f2eedaf9bcae84c91a419b0c86d87284235d982/include/crow/app.h)

**Comment by The-EDev** [comment]
I know this might be outside this issue, but modifying `dumb_timer_queue::tick` in a way that allows each function to have its own time would set the stage to solving #257
