### ISSUE TITLE
How to upload files?

### ISSUE THREAD

**Issue by mochechan** [CrowCpp/Crow#267]
I attempted to use the [multipart example](https://github.com/CrowCpp/Crow/blob/b5137c52a1323fb4793bbebf4a48b528c939bc98/examples/example.cpp#L199) to upload files, no luck so far.

For example, the file is uploaded by using curl, and gets the response "405 Method Not Allowed".

```
$ curl --verbose -F "file=@../dog.jpg" http://localhost:18080/multipart 
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 18080 (#0)
> POST /multipart HTTP/1.1
> Host: localhost:18080
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 163944
> Content-Type: multipart/form-data; boundary=------------------------89159528dce5db9d
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 405 Method Not Allowed
< Content-Length: 24
< Server: Crow/0.3
< Date: Thu, 04 Nov 2021 08:23:41 GMT
* HTTP error before end of send, stop sending
< 
405 Method Not Allowed
* Closing connection 0
```

How to solve this problem. Is any workable example with a curl command?

**Comment by The-EDev** [comment]
You're making a `POST` request in curl, the example defines the route for `GET` requests

**Comment by The-EDev** [comment]
was your issue resolved? Please let me know so I can help you further or close the issue.

**Comment by mochechan** [comment]
Yes, my file uploading is good now.
I just don't understand why the example uses GET method.
AFAIK, file uploading should be POST. 
Thank you.

**Comment by The-EDev** [comment]
`multipart` isn't exactly used for file uploading only, regardless you are correct, data sent from the client normally use `POST`. The reason it is this way is because at the time I just wanted to get something that worked, my HTTP client (Insomnia REST) sets methods manually so that wasn't a problem for me.
Thank you for the suggestion, I"ll update the example ASAP.
