### ISSUE TITLE
crow::json::dump does not exist?

### ISSUE THREAD

**Issue by FryingDutch** [CrowCpp/Crow#271]
Hi,

Have been using your lib for a while now, never had any issues.
However, when I want to get the string from a crow::json::wvalue, I receive this error.

#13 19.77 error: 'dump' is not a member of 'crow::json'
#13 19.77 34 | std::string jsonBody = crow::json::dump(x);

All other functions seem to work.

**Comment by luca-schlecker** [comment]
Isn't the dump function a member of `crow::json::wvalue`?
https://github.com/CrowCpp/Crow/blob/4ac58921603e36a606edc0ceb5ad04855868b6f4/include/crow/json.h#L1811-L1818

**Comment by FryingDutch** [comment]
You are correct! Doing x.dump() works. 
Funny thing is, wherever I look for an example, crow::json::dump(x) is being used, which confused me.

**Comment by luca-schlecker** [comment]
Interesting, are these external or are they official Crow documentation? If they're from Crow, could you please link the faulty examples so we can get them fixed?

**Comment by The-EDev** [comment]
@luca-schlecker `ipkn/crow` had it as `crow::json::dump`. I had to change it when I added the `returnable` class. The related PR is https://github.com/CrowCpp/Crow/pull/84
