### ISSUE TITLE
How can I get a stringstream from a `crow::json::rvalue`?

### ISSUE THREAD

**Issue by dsimog01** [CrowCpp/Crow#283]
I receive a JSON in my CROW server and I want to get each of the values inside it as a stringstream, how can I do that?

**Comment by The-EDev** [comment]
IIRC you could use the `<<` operator with `crow::json::rvalue`. Have you tried that? if you did and it didn't work, in what way was the result different from your expectation?

**Comment by dsimog01** [comment]
I do not really know how to use that operator, I am not very used to programming in C++...

**Comment by dsimog01** [comment]
stringstream tmp;
tmp << json[i];

Like this?

**Comment by The-EDev** [comment]
yeah either `tmp << json[i];` or `tmp << json;`, both should work.

**Comment by dsimog01** [comment]
```
try {
    tmp << json[i];
} catch (std::exception &e) {
    cout << "ERROR -->" << e.what() << endl;
}
```

Using this, I get the following error:
ERROR -->value is not a list

The stringstream is a serialized Microsoft SEAL Ciphertext object.

**Comment by The-EDev** [comment]
This means that `json` is not a list so you can't use an `int` inside the square brackets

**Comment by dsimog01** [comment]
It is true... I did not notice. Thanks!
