### ISSUE TITLE
A blog for the project

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#284]
Currently the only place for us to inform people about project updates is through [OpenCollective](https://opencollective.com/crow). I think it will be better to have a project blog for updates / plans.

One problem is gh-pages makes this quite a bit more difficult. So I'm open to suggestions on implementation ideas and whether or not a blog is useful for the project.

**Comment by Leon0402** [comment]
Personally I would appreciate: 
- A Roadmap (Github Projects / Milestones, Wiki or whatever)
- Regular Releases with a nice description

I have no need for additional blog posts. It would also be too much to keep up with blog posts for every single library I use.

Also I would keep the Roadmap and release descriptions rather high level. I'm mostly interested in important and relevant changes for me (for example that using the crow macro is not necessary, but not too much into internal refactorings / more test coverage / more tooling )

Everyone more interested into details can look at the issues, pull requsts, matrix channel ...

**Comment by luca-schlecker** [comment]
I guess the kanban board from GitHub Projects could be interesting. An extra blog seems impractical, I can't remember reading a blog about a project, I do remember looking at some GitHub Projects though. The changelog can be found as the description of each release, I think it'll be enough if structured right (emphasis on important and breaking changes).

**Comment by The-EDev** [comment]
My concern when suggesting a blog is primarily me trying to find ways to keep the project in the public eye, an easy way to share news and updates to people who may not be following the project very closely. It also makes sharing news on social media much easier (rather than having to copy the same text over multiple platforms).

We're technically using milestones (though admittedly not as much as I would like). And to be completely honest I don't currently see a use for projects. As far as I could tell they're a way to group different issues that work towards a single goal. Which isn't very common in this case, as most features don't span more than 1 issue.

Please keep in mind I'm just sharing my opinion and not asserting anything

**Comment by luca-schlecker** [comment]
Maybe publications and articles in already established magazines/blogs like [Medium](https://medium.com) could help pull attention towards Crow.

**Comment by The-EDev** [comment]
I've considered a personal Medium account before, but never considered it for promoting Crow and publishing news about it.. this could be interesting.

**Comment by kassane** [comment]
A free Medium alternative would be [dev.to](dev.to)

**Comment by The-EDev** [comment]
Looking at the issue once again, I think the name blog isn't applicable here. What I'm looking to add is a section where news about the project can be shared, new releases, planned features, etc.. The goal is **not** for people to follow developments in the project bit by bit, but rather be able to generally understand where it is and where it's going (without diving through issues).
