### ISSUE TITLE
#define CROW_MAIN required?

### ISSUE THREAD

**Issue by RKolla99** [CrowCpp/Crow#300]
I was unable to get the server up and running until I added #define CROW_MAIN. However, a few previous updates have removed the need for it and the examples have been updated accordingly. I do not think I'm on a older version of crow.
I installed crow by downloading the .deb file and used apt to get the dependencies. I was running the Hello World example provided in the README.

**Comment by luca-schlecker** [comment]
There has been no release including the removal of `CROW_MAIN` yet. This change is currently only in master.
