### ISSUE TITLE
JSON example failing

### ISSUE THREAD

**Issue by RKolla99** [CrowCpp/Crow#301]
I was trying the JSON example mentioned in the README.

I run into the following error when executing this line: `crow::json::wvalue x({{"message", "Hello, World!"}});`
`error: no matching function for call to 'wvalue(<brace-enclosed initializer list>)'` 

There's also an error when I attempt to return a JSON using `crow::json::wvalue`. The return type is not acceptable.
` error: inconsistent types 'crow::response' and 'crow::json::wvalue' deduced for lambda return type`

**Comment by The-EDev** [comment]
Using JSON initializer list isn't supported in Crow `v0.3`. You should use the version in `master` branch
