### ISSUE TITLE
Not able to compile example.cpp with crow_all.h

### ISSUE THREAD

**Issue by beevatsyu** [CrowCpp/Crow#309]
getting compilation error like
`no instance of constructor "crow::json::wvalue::wvalue" matches the argument list`

**Comment by The-EDev** [comment]
Hello @beevatsyu, What version of Crow are you using and on what OS?

**Comment by beevatsyu** [comment]
@The-EDev Thanks for the quick response.
Yes, that's exactly the case. Can you point me to `crow_all.h` from `master` branch?

**Comment by The-EDev** [comment]
You'll have to generate it yourself, you just need to run ` python merge_all.py ../include crow_all.h` inside the `scripts` folder (you'll need to have python installed and replace `/` with `\\` if you're on Windows)

**Comment by beevatsyu** [comment]
That worked! Thanks again for the awesome work you guys are doing! Crow's gonna fly really high someday!
