### ISSUE TITLE
How to get headers' values? 

### ISSUE THREAD

**Issue by mochechan** [CrowCpp/Crow#314]
The following example is to describe the question.

The following command sends a request with uploading a file and a header.
```
curl --verbose -F "file1=@./test.jpg" -H "id: test_id" http://localhost:4041/test
```
Filenames and file contents can be obtained via multipart by using the following code. 
```cpp
CROW_ROUTE(app, "/test").methods(crow::HTTPMethod::POST)([](	const crow::request& req) {

crow::multipart::message msg(req);
//std::cout << msg.dump() << "\n";
for (int i = 0; i < msg.parts.size(); ++i) {
for (int j = 0; j < msg.parts[i].headers.size(); ++j) {
	CROW_LOG_INFO << "header " << j << " "
	<< std::get<0>(msg.parts[i].headers[j].value) << ": "
	<< std::get<1>(msg.parts[i].headers[j].value);
	std::string filename = "";
	std::string name = "";
	for (const auto & [ key, value ] : msg.parts[i].headers[j].params) {
		if (key.compare("filename") == 0){
			filename = value;
		} else if (key.compare("name") == 0){
			name = value;
		} else {
		}
	}
	if (filename.size() < 5) {
		CROW_LOG_INFO << "skipping short filename" << filename << " " << name;
		continue; 
	}

	std::string file_content = msg.parts[i].body;
	std::vector<uchar> binary(file_content.begin(),file_content.end());
	CROW_LOG_INFO << "name:" << name << " filename:" << filename << " size:" << binary.size();
	cv::Mat img = cv::imdecode(binary, cv::IMREAD_UNCHANGED);

}} // end of double for(;;)
crow::response response = crow::response(200, reportjs.dump() + "\n");
response.add_header("Content-Type", "application/json");
return response;
});
```
However, I don't know how to obtain the header "id" with the value "test_id".
I'm trying to use msg.dump(), but no `test_id` is found.
How to get the header with the value "test_id"?

**Comment by The-EDev** [comment]
While multipart messages have headers, they're part of the HTTP request's body. I believe the `-H` option specifies a request header, which can be obtained via `req.get_header_value("id")`.

Please let me know if this answers your question.

**Comment by mochechan** [comment]
Thank you. This is the answer what I need.
So, a request's body/header is not identical to the multipart message's body/header.

**Comment by mochechan** [comment]
The code in this issue can fetch a filename and its name. The code can work with previous version Crow, but the code cannot be compiled with version 1.0. 

```
error: no match for ‘operator[]’ (operand types are ‘crow::multipart::mph_map {aka std::unordered_multimap<std::__cxx11::basic_string<char>, crow::multipart::header, crow::ci_hash, crow::ci_key_eq>}’ and ‘int’)
    CROW_LOG_INFO << "header " << j << " " << std::get<0>(msg.parts[i].headers[j].value) << ": " << std::get<1>(msg.parts[i].headers[j].value);

```
How to fetch the filename and its name for a specific part? Please give a example.

**Comment by The-EDev** [comment]
Part headers are now structured similarly to a request's headers, and can be retrieved from by key using `crow::multipart::get_header_object("header-key")`. In your case the header is `Content-Disposition`. Both `name` and `filename` should be parameters of that header.

**Comment by mochechan** [comment]
Sorry. My unclear question. I mean if I want to enumerate or iterate all header-keys, not just a known header-key. Just like the code in this issue.

**Comment by mochechan** [comment]
I finally found the scheme. Thank you very much.

```
for(auto it=msg.parts[i].headers.begin(); it != msg.parts[i].headers.end(); ++it){
	auto const &key = it->first;
	auto const &value = it->second;
	std::cout << "key " << key << "\n";
	std::cout << "value " << value.value << "\n";
	for (const auto & [ k, v ] : value.params) {
		CROW_LOG_INFO << k << " " << v;
	}
```

This scheme is very useful if client push unknown name and filename.
