### ISSUE TITLE
`json::wvalue` incorrectly outputs NaN or infinite values instead of ignoring them

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#316]
as described in #315, values that are infinite or NaN should not appear in the resulting JSON string and a warning / non fatal error should be logged.

**Comment by Vhuynh25** [comment]
Hi, I want to work on this. What message should I put for the warning?

**Comment by The-EDev** [comment]
Hi @Vhuynh25, something like "invalid JSON value detected (<key name>), Ignoring." would be fine. Thanks

**Comment by The-EDev** [comment]
Update: When reviewing #328 and @epajarre's comment on the matter, it seems that outputting the value as `null` would be the better option, especially when dealing with arrays (since omitting an invalid value in an array would cause an unexpected change in its structure).
