### ISSUE TITLE
Openssl in VCPKG

### ISSUE THREAD

**Issue by Borwe** [CrowCpp/Crow#329]
Is it meant to be windows only dependency? as currently it's possible to even build normal openssl from vcpkg on linux too, and I guess MacOS. If it was meant for Windows only, maybe should consider adding ```"platform": "windows"``` to allow users on linux to build crow without problems, or replace ```"openssl-windows"``` dependency with normal ```"openssl"``` dependency.

**Comment by luca-schlecker** [comment]
I guess you are referring to `vcpkg.json` in the root of Crow's repository. I did not create it, but I think it was meant for installing the dependencies needed for building the examples, it has nothing to do with the dependencies being installed by vcpkg when installing Crow through it. I guess on Linux it shouldn't be needed, but I agree. I think `openssl-windows` shouldn't even be used anymore, it should be replaceable with `openssl`.

**Comment by Borwe** [comment]
Yes, the vcpkg.json file, causes errors when used to build on linux if someone chooses vcpkg route. Because of the ```openssl-windows```
