### ISSUE TITLE
Add sanitizer free loading functions

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#336]
Create versions of `crow::response::set_static_file_info`, `crow::mustache::load_text`, and `crow::mustache::load` that don't sanitize the path, in case the Crow application developer needs to access something otherwise unreachable.

Also include in the documentation explanations and warnings about the usage of these new function (they shouldn't be used anywhere end user input is involved).

This issue was raised through #333.

**Comment by zefrenchy** [comment]
I feel like contributing :) I might look at this tomorrow. Are you stylistically opposed to default arguments instead of additional functions  ... that would make it a very easy patch.

**Comment by The-EDev** [comment]
@zefrenchy Thanks. I'm not opposed to default arguments, but in this particular case it might be best to make running and not running the sanitizer as far apart as possible, the patch is very easy regardless, you just need to remove a single line that runs the sanitizer (and maybe another line that creates a copy of the path string).
