### ISSUE TITLE
`set_static_file_info` sends the wrong content length for 404 errors

### ISSUE THREAD

**Issue by shaiquie-zieye** [CrowCpp/Crow#337]
It is always `Content-Length: 15`, you can easily reproduce this by running the `example_static_file` example program without any `cat.jpg`.

This is particularly annoying because clients hang waiting for those 15 bytes that will never arrive.

**Comment by The-EDev** [comment]
Found the issue, Here's the fix
```diff
--- include/crow/http_response.h
+++ include/crow/http_response.h
@@ -242,8 +242,9 @@ namespace crow
             }
             else
             {
                 code = 404;
+                file_info.path.clear();
                 this->end();
             }
         }
```

Thanks for pointing the Issue out.

**Comment by shaiquie-zieye** [comment]
Thanks for the quick action. :)
