### ISSUE TITLE
Broken Mustache escaping

### ISSUE THREAD

**Issue by shaiquie-zieye** [CrowCpp/Crow#341]
I think semicolons are missing here:

https://github.com/CrowCpp/Crow/blob/5a651b0d0e4b10f8808dd2a180ed36f4f15a413b/include/crow/mustache.h#L149-L150

**Comment by The-EDev** [comment]
@shaiquie-zieye could you elaborate please? Are you saying semicolons need to be escaped as well?

**Comment by shaiquie-zieye** [comment]
I apologise for the cryptic report. I mean entities must end with a `;`, so:

```c++
 case '`': out += "&#x60;"; break; 
 case '=': out += "&#x3D;"; break; 
```

**Comment by The-EDev** [comment]
Ah, I'll fix asap, my bad
