### ISSUE TITLE
revert #334

### ISSUE THREAD

**Issue by bwebb-clarecontrols** [CrowCpp/Crow#343]
This commit breaks set_static_file_info with paths such as /var/www or /srz/www

**Comment by bwebb-clarecontrols** [comment]
Going off the first example of library usage to returning a static home page instead of "hello world". doesn't use user input. nor would I expose something like that.


I don't think setting the define for static directory or endpoint get around return something for /

```
#define CROW_STATIC_DIRECTORY
#define CROW_STATIC_ENDPOINT 
```

```
CROW_ROUTE(app, "/")([]()
     {
         crow::response response {};

         response.set_static_file_info(STATIC_FILE_LOCATION);

         return response;
     });

```

I just saw the commit from 8 hours ago fixing this issue.

**Comment by The-EDev** [comment]
I'm not 100% sure this is what you meant, but I'm guessing you're saying you might want your `CROW_STATIC_DIRECTORY` to be an absolute path rather than a relative one. Which I guess is a valid point. It would make sense that only the user input part of the path is sanitized.

**Comment by bwebb-clarecontrols** [comment]
Sorry I got things jumbled.

For the main purpose of this issue, I see it was fixed in a later commit.

### For the defines for static paths

You can use `CROW_STATIC_DIRECTORY` with a absolute path iff you define the overide for it `CROW_DISABLE_STATIC_DIR`

But since you have to create a endpoint define `CROW_STATIC_ENDPOINT` `/example/<path>` no file lines up with `http://localhost` unless you do a `http://localhost/index.html`. But this would still require you to put a route for "/" to index.html
