### ISSUE TITLE
Change the following project settings:Multiple Headers,Single Headers

### ISSUE THREAD

**Issue by Daviddbalaban** [CrowCpp/Crow#344]
Hello ,

Could you explain how to change these in xcode ? I read on the web that It means to make #include "(path to boost)" but it does not work.

It would be a lot better if you could do a yt video tutorial.

thx in advance

**Comment by The-EDev** [comment]
![image](https://user-images.githubusercontent.com/60552923/153768126-e4931be2-e2b9-4cb4-9da9-002c2a78c98b.png)
I believe this is where you find the `Header Search Paths` and `Linker Flags`.

Let me know if this works for you

**Comment by Daviddbalaban** [comment]
ok ... I did that , but now it keeps showing me the same error as the old files from 4 years ago ... :((

![image](https://user-images.githubusercontent.com/65186634/153774401-92265663-11b6-4747-8ee6-0e99cf043e77.png)

![image](https://user-images.githubusercontent.com/65186634/153774423-ba739f51-10ab-4746-b081-75689c765298.png)

Could you help me please ? 

thx in advance

**Comment by Daviddbalaban** [comment]
update... So i fixed id including my paths to header search paths not lib ones... but now it gives me a lot of errors but not code related .

![image](https://user-images.githubusercontent.com/65186634/153774724-8f253b46-3f35-477e-b4fe-b3ba4f21df0d.png)

any idea ?

**Comment by The-EDev** [comment]
the C++ standard library seems to be fine, but The C Language Dialect probably shouldn't be gnu11 (since Apple uses Clang which doesn't play well with GCC (gnu compiler))

**Comment by Daviddbalaban** [comment]
And what should I do ?

**Comment by The-EDev** [comment]
I don't know what options other than `gnu11` there are, but I would change it to something else

**Comment by Daviddbalaban** [comment]
Ok i will try and come back.

**Comment by Daviddbalaban** [comment]
So , I tried every c compiler ... but still the same.

Any other advice ?

**Comment by The-EDev** [comment]
I don't know, but your problem has to do with something being missing or incorrect in the standard C++ library

**Comment by Daviddbalaban** [comment]
Ok , do you think you could find out what it is or maybe I should try another framework ?

**Comment by Daviddbalaban** [comment]
yup it's clear now , very hard to make a simple thing.

**Comment by The-EDev** [comment]
It's up to you what you want to do, frankly speaking I'm not intimately familiar with xcode or macos but I still did my best to help you with your issue, which ultimately isn't related to Crow itself. I'm sorry that you feel this isn't enough and wish you the best with your work.

**Comment by Daviddbalaban** [comment]
You guys should know how to fix your issues. :)
