### ISSUE TITLE
Compilation Error in VS2019 in Windows using vcpkg 

### ISSUE THREAD

**Issue by mjjackey** [CrowCpp/Crow#353]
I used vcpkg to install **crow** in VS2019 in Windows, the version is **0.3.4** and installed the dependency **boots** whose version is **1.78.0.**
I used `#include "crow_all.h"`, but the error pops up
![image](https://user-images.githubusercontent.com/14541043/155250106-f72ca32e-3a00-4841-aac3-83f3f638415b.png)
When I used `#include "crow.h"`, the linked errors appear.
![image](https://user-images.githubusercontent.com/14541043/155250123-d7ff4f47-e89c-40e3-bcf9-e7de6c1eaa3c.png)
Could someone help me？
I have read the guide of installation [https://crowcpp.org/getting_started/setup/windows/](url). I almost did the installation conforming to this guide. Except 
![image](https://user-images.githubusercontent.com/14541043/155252826-2a86ab59-5bc5-4d15-a7eb-2c067c5b32bd.png)
because it went wrong. Actually, I don't know what the meaning of this step is combined with the **vcpkg.json** in step 7.

**Comment by The-EDev** [comment]
How did you install Crow? was it by running `vcpkg install crow` or did you download the source code manually?

The second error (that appears when using `#include "crow.h"`) seems to be related to not having `#define CROW_MAIN` at the very top of your main source file.

**Comment by mjjackey** [comment]
> How did you install Crow? was it by running `vcpkg install crow` or did you download the source code manually?
> 
> The second error (that appears when using `#include "crow.h"`) seems to be related to not having `#define CROW_MAIN` at the very top of your main source file (Which is a requirement for `v0.3` only).
The installation is
```
vcpkg integrate install
vcpkg install crow:x64-windows
```
I added the `define CROW_MAIN` at the very top of your main source file, the LINK error is still on.

**Comment by The-EDev** [comment]
That's interesting, the second linking error is definitely coming from a missing `CROW_MAIN`, just to make absolutely sure, the ` #define CROW_MAIN` line needs to be specifically above the `#include "crow.h"` line

**Comment by mjjackey** [comment]
> That's interesting, the second linking error is definitely coming from a missing `CROW_MAIN`, just to make absolutely sure, the ` #define CROW_MAIN` line needs to be specifically above the `#include "crow.h"` line, is that the case?

Quite Sorry, I did wrong before! Now it works as you emphasized" **above the `#include "crow.h"` line**"
