### ISSUE TITLE
Post the json file by the curl tool. Why the server cannot parse correctly?

### ISSUE THREAD

**Issue by mjjackey** [CrowCpp/Crow#357]
This is the server code. 
```c++
    CROW_ROUTE(app, "/add_json").methods("POST"_method)
    ([](const crow::request& req){
        auto x = crow::json::load(req.body);  //**
        if (!x)
            return crow::response(400);
        int sum = x["a"].i()+x["b"].i();
        std::ostringstream os;
        os << sum;
        return crow::response{os.str()};
    });
```
This is the result debugging by curl in two methods:
![image](https://user-images.githubusercontent.com/14541043/155966230-25a62e30-9a67-4e43-8117-77cd4dfac525.png)
But it is correct through Postman:
![image](https://user-images.githubusercontent.com/14541043/155966469-e6a64a8e-52a2-4feb-b2c2-e1c2ffac7a2c.png)

**Comment by The-EDev** [comment]
Your curl data should be wrapped with quotation marks (`'`), otherwise curl assumes the string ends at the first whitespace, I'm not sure about the JSON file.

**Comment by The-EDev** [comment]
This is interesting, the `content-length` header for the request should be at least `14`, but it's `11` in this case..

**Comment by mjjackey** [comment]
> This is interesting, the `content-length` header for the request should be at least `14`, but it's `11` in this case..

Thank you for your reply! So I'm confused. And I used curl several days ago, but with the old header files ipkn/crow. It is successful. 
![image](https://user-images.githubusercontent.com/14541043/156093799-6d6ba998-a880-411c-9ba3-ed6259ce969a.png)

**Comment by The-EDev** [comment]
I took another look at the commands, I think the file problem was that you initially used `-data` instead of `--data` or `-d`. Using the inline `' {"a":5, "b":7}'` on this repo's `master` branch worked fine for me (I'm using `example.cpp`). Here's my log:
```
$ curl -w' \n' -v -d ' {"a":5, "b":7}' http://localhost:18080/add_json
*   Trying 127.0.0.1:18080...
* Connected to localhost (127.0.0.1) port 18080 (#0)
> POST /add_json HTTP/1.1
> Host: localhost:18080
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 15
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 2
< Server: Crow/master
< Date: Tue, 01 Mar 2022 02:46:00 GMT
< Connection: Keep-Alive
< 
* Connection #0 to host localhost left intact
12 
```

**Comment by mjjackey** [comment]
> I took another look at the commands, I think the file problem was that you initially used `-data` instead of `--data` or `-d`. Using the inline `' {"a":5, "b":7}'` on this repo's `master` branch worked fine for me (I'm using `example.cpp`). Here's my log:
> 
> ```
> $ curl -w' \n' -v -d ' {"a":5, "b":7}' http://localhost:18080/add_json
> *   Trying 127.0.0.1:18080...
> * Connected to localhost (127.0.0.1) port 18080 (#0)
> > POST /add_json HTTP/1.1
> > Host: localhost:18080
> > User-Agent: curl/7.81.0
> > Accept: */*
> > Content-Length: 15
> > Content-Type: application/x-www-form-urlencoded
> > 
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 200 OK
> < Content-Length: 2
> < Server: Crow/master
> < Date: Tue, 01 Mar 2022 02:46:00 GMT
> < Connection: Keep-Alive
> < 
> * Connection #0 to host localhost left intact
> 12 
> ```

Thank you for your reminder. Now the file is correct.
![image](https://user-images.githubusercontent.com/14541043/156097180-98c02063-a2bd-4e81-8db4-912d4e812f46.png)
the inline is still wrong(interesting)
![image](https://user-images.githubusercontent.com/14541043/156097396-3b819bdd-bcbd-4ec6-8a6c-6f5cdadcf0b9.png)

**Comment by The-EDev** [comment]
I know it's been a while and unfortunately I don't have a windows machine handy, but the `"` (Double quotation mark) doesn't look exactly like one, more like a `〃` (AKA Ditto mark).

**Comment by The-EDev** [comment]
I'll close this for now, please let me know if the problem persists and I'll reopen this issue.
