### ISSUE TITLE
How to send binary data as reponse

### ISSUE THREAD

**Issue by kingster** [CrowCpp/Crow#366]
Hi

In my application, I am creating a dynamic binary payload (zip file) essentially a `std::vector<char>`  and want to serve this via the API handler. How to achieve this?

```cpp
CROW_ROUTE(app, "/download")
    ([](){
        std::vector<char> data_bytes = createdownload();  
        auto response = crow::response(data_bytes); //This doesn't work today
	response.set_header("Content-Type", "application/octet-stream"); 
        return response;
    });
```

In the old `ipkn/crow` variant, I had written a [wrapper](https://github.com/kingster/ipkn-crow/commit/ad1a2e2c463f15d902375ce50ae8047486209064?w=1) to support sending binary payload as the response. What is the right approach here?

PS: converting `std::vector<char>` to `std::string` is not correct, as the handling will fail on first null byte in the sequence. Ref https://github.com/ipkn/crow/issues/191

**Comment by The-EDev** [comment]
Hi, It seems that the problem here is the way `std::string` works. Referencing [this StackOverflow answer]():
> The problem is the std::string constructor that takes a const char* assumes the input is a C-string. C-strings are \0 terminated and thus parsing stops when it reaches the \0 character.

I managed to make an example that works by using constructing the string as follows:
```cpp
CROW_ROUTE(app, "/download")
([](){
    std::vector<char> data_bytes = {'a', 'b', 'c', '\0', 'e', 'f'};
    std::string data_str(data_bytes.begin(), data_bytes.end());
    auto response = crow::response(data_str); //This does work today
    response.set_header("Content-Type", "application/octet-stream");
    return response;
});
```

**Comment by kingster** [comment]
Thanks! This works for me!
