### ISSUE TITLE
Add `template` keyword to `CROW_MIDDLEWARES` macro

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#369]
As mentioned in #365, Allows for `app.route()` to use template arguments. Though should make sure nothing is being messed up by that addition.

**Comment by The-EDev** [comment]
@dranikpg What do you think about this?

**Comment by dranikpg** [comment]
Oh crap, I totally forgot about this issue 😰 (https://github.com/CrowCpp/Crow/issues/365#issuecomment-1073033022).

Giving the compiler a hint that the following function is a template function _should theoretically not_ break anything. [This is a good explanation](https://stackoverflow.com/questions/610245/where-and-why-do-i-have-to-put-the-template-and-typename-keywords) where the template keyword should(can) be used. 

The problem however is a bit more complex. Lets examine the following example:
```c++
template<typename App>
void run() {
    App app;
    CROW_ROUTE(app, "/secret")
      .CROW_MIDDLEWARES(app, SecretContentGuard)([]() {
          return "";
      });
    app.port(18080).run();
}
```
We need to make __3__ changes to make this work:
```c++
#define CROW_ROUTE(app, url) app.template route<crow::black_magic::get_parameter_tag(url)>(url)
#define CROW_MIDDLEWARES(app, ...) template middlewares<typename std::remove_reference<decltype(app)>::type, __VA_ARGS__>()
```
I added two templates and one typename. Again, those changes _should theoretically not_ break anything.

Not sure yet about the websockets. I haven't used them much, so I don't have a lot of examples to quickly test on.
