### ISSUE TITLE
About setting features after Crow is installed

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#380]
@autoantwort wrote [this](https://github.com/CrowCpp/Crow/commit/258e0f50df76717e5a2e90f14c69522316b040e0#commitcomment-69885951). (Below is a copy)

>  Hm I don't know if that is a good idea. If vcpkg installs the package with openssl and zlib enabled the consuming user still have to set `CROW_ENABLE_COMPRESSION` and `CROW_ENABLE_SSL` before the `find_package` call?

@luca-schlecker what's your opinion on this?

**Comment by luca-schlecker** [comment]
Vcpkg has "features", it enables ports to specify different configurations with additional dependencies.
[Microsoft DevBlog about vcpkg "features"](https://devblogs.microsoft.com/cppblog/vcpkg-introducing-installation-options-with-feature-packages/)

My current plan for the vcpkg port of Crow is having two such configurations (`compression` and `ssl`) pulling in the according dependencies (ZLib and OpenSSL). When installed in a specific configuration, these parts of Crow should be automatically available and thus the according flags (e. g. `CROW_ENABLE_SSL`) need to be set automatically.

This is not reflected by the current behavior but it seems like a quick fix.

My proposed change, which I will spin up a PR with if you agree, would make the default feature-set of a Crow installation (basically the default values for `CROW_ENABLE_*` flags) be the one it was installed with. One would still be able to manually enable or disable it.

**Comment by autoantwort** [comment]
Sounds good

**Comment by The-EDev** [comment]
> My proposed change, which I will spin up a PR with if you agree, would make the default feature-set of a Crow installation (basically the default values for CROW_ENABLE_* flags) be the one it was installed with. One would still be able to manually enable or disable it.

The idea is good, but we would probably need to figure out how to do this for all package managers (VCPKG, AUR, and Conan).

**Comment by luca-schlecker** [comment]
I guess you have to specify it somewhere, either in code, in cmake or during install, but maybe `CROW_ENABLE_*` should be hidden by a variable like `CROW_FEATURES` where a possible value could be `"ssl compression"`. Then all features could be set by just one call in cmake.
