### ISSUE TITLE
Error while executing hello world example

### ISSUE THREAD

**Issue by juansebastiani2cat** [CrowCpp/Crow#389]
Dear all,

I have cloned the repository and then executed the file merge_all.py in the scripts folder. This has generated a crow_all.h header which I have included into the project's main file: 

`#include </home/jonnybgood/Downloads/crow/Crow-master/scripts/crow_all.h>`

The issue happens when I build the project. As the following errors appear:

```
./src/Test_API.o: in function `boost::asio::detail::posix_thread::~posix_thread()': Test_API C/C++ Problem

./src/Test_API.o: in function `boost::asio::detail::posix_thread::join()': Test_API C/C++ Problem

make: *** [makefile:60: Test_API] Error 1	Test_API		 	C/C++ Problem

undefined reference to `pthread_detach'	Test_API		line 35, external location: /usr/include/boost/asio/detail/impl/posix_thread.ipp	C/C++ Problem

undefined reference to `pthread_join'	Test_API		line 42, external location: /usr/include/boost/asio/detail/impl/posix_thread.ipp	C/C++ Problem

```
I can see it is related with some boost library but I have already fullfiled all the requirements. I am running the project in Eclipse, but I have also used Visual Studio without any success. The OS is Ubuntu 20.04 LTS. 

I would appreciate any help or hint with this. Thanks in advance.

**Comment by The-EDev** [comment]
Have you linked the `pthread` library? the error seems to indicate that you're compiling without `-lpthread`.

**Comment by juansebastiani2cat** [comment]
No, I haven't linked it. Do I need to include it as a header file ?

**Comment by The-EDev** [comment]
No, it's a library that's part of the operating system. for GCC you'd do `g++ main.cpp -lpthread` to link it. For eclipse you'd go to `project properties->C/C++ build->Settings->GCC C++ Linker->Libraries->[-l section]` and add `pthread` to that.

Let me know if that works.

**Comment by juansebastiani2cat** [comment]
That was amazing, had spent a couple of days trying to figure it out before posting and it the solution was so easy and straightforward. Thanks a lot for your help, it's already working. Thanks again.

**Comment by The-EDev** [comment]
No problem, I'm happy to help.
