### ISSUE TITLE
`wvalue` interprets double as int

### ISSUE THREAD

**Issue by autoantwort** [CrowCpp/Crow#398]
With the following code for a request:
```c++
        std::vector<crow::json::wvalue> result;
        for (int i = 0; i < 4; ++i)
        {
            result.push_back(1.1);
        }
        return crow::json::wvalue(result);
```
I get the following answer `[4607632778762754458,4607632778762754458,4607632778762754458,4607632778762754458]` instead of `[1.1, 1.1, 1.1, 1.1]`

Testet with VS 2015 and the latest release.

**Comment by The-EDev** [comment]
I'm guessing this is because `push_back` doesn't run the constructor for `json::wvalue`, using `emplace_back` instead returns the correct result.

**Comment by autoantwort** [comment]
It runs the constructor and then the copy constructor. I think the copy constructor has an error.

**Comment by The-EDev** [comment]
Well constructing a temporary `wvalue` variable with the `1.1` value before using `push_back` seems to work as well..

**Comment by autoantwort** [comment]
For me the following also gives an error:
```c++
        std::vector<crow::json::wvalue> result;
        for (int i = 0; i < 4; ++i)
        {
            crow::json::wvalue v;
            v = 1.1
            result.push_back(v);
        }
        return crow::json::wvalue(result);
```

**Comment by The-EDev** [comment]
this is weird, it worked for me...

**Comment by The-EDev** [comment]
@autoantwort does this issue still exist? I wasn't able to reproduce the issue
