### ISSUE TITLE
Blueprint support

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#40]
Some way of combining similar requests or modulating the application, with their own prefixes, and maybe even middlewares.

Based on Flask's blueprints

**Comment by vexy** [comment]
Any movement with this ?

**Comment by The-EDev** [comment]
@vexy not gonna lie. I have no idea where to begin implementing this. And from what I know about flasks blueprints. This is likely going to require a lot of changes to Crow's core and a lot of research. So any help with the matter would be very appreciated.
I will post any thoughts or advancements here.

**Comment by vexy** [comment]
True. It's a big topic and may require a lot of changes. Although, it'd be very useful feature to have

**Comment by The-EDev** [comment]
okay, Here's what blueprints do:
1. Give a URL prefix.
2. Give custom templates / static folders.
3 Provide more context for `url_for()` function.
4. Have their own error handlers (for crow this would be `CROW_CATCHALL_ROUTE`)
5. An app can register the blueprint to include its routes.
6. A blueprint can register another blueprint (nested blueprints).

point 5 can and has already been implemented manually. See [Forestpp](https://gitlab.com/The-EDev/forestpp.git) for the implementation.

**Comment by The-EDev** [comment]
If I were to implement this feature, I would start with app (not nested) registration, move on to prefixes, then custom folders, then catchall handlers, then nesting, and ignore `url_for()` until (if ever) that function is implemented in crow.

The order for the points would be 5, 1, 2, 4, 6 ignoring 3.

**Comment by The-EDev** [comment]
5 and 1 are implemented :)

**Comment by The-EDev** [comment]
BPCatchall route will require moving the blueprints and all associated code to the router instead of the app. This should also result in cleaner code and less repetition overall.

Once that's done the idea is to use `Trie` to detect blueprints in a similar fashion to how routes are detected, with the exception that finding a blueprint in any node along the search route should qualify as a route, if multiple blueprints are found, the very last one is taken.

**Comment by The-EDev** [comment]
4 done, only converting to a list is left

**Comment by vexy** [comment]
Awesome work man !!

**Comment by The-EDev** [comment]
Blueprints branch is feature complete. writing unit tests now.
