### ISSUE TITLE
Doubt Using Get

### ISSUE THREAD

**Issue by juansebastiani2cat** [CrowCpp/Crow#400]
Hello,

I'm running a Flask Python API server in Local, with a very easy "Hello World" string response. I have formulated the following Crow Get code to pull the data from the server: 

```
crow::SimpleApp app;
	CROW_ROUTE(app, "http://localhost:5000/").methods(crow::HTTPMethod::GET)([](const crow::request& req){
		return 23.3; // This is based on another Get example that I checked, not really sure why or what it does it. 
	});
```
The program compiles and runs smoothly, but essentially I don't know how to get the answer from the Get. In python I would assign a variable to the Get and use it but when I try to do the same here (using an Auto variable type, cause I don't know the variable type), the compilation fails. I think this is essentially a C++ problem and not a Crow, but I would appreciate if you could show me how to operate with the Get method (Or some for-dummies tutorial for the HTTP methods). 

Thanks in advance.

**Comment by luca-schlecker** [comment]
Hi,
I hope I understood you correctly.
Crow wants to be a replacement for Pythons Flask. Crow is not meant for making requests, it receives them, just like your python/flask server.

If you want to make requests and thus receive the answer string from your python/flask server, you'll have to look at other projects like [cpr](https://github.com/libcpr/cpr).
If you want to replace that python/flask server, then have a look at Crow.

**Comment by juansebastiani2cat** [comment]
Ohhh, I didn't expect that. Well, yeah, as you said, basically I wanted to include the Crow Get as a client in a Client-Server API configuration that I have. Ok, thanks a lot for your answer and I will take a look at your suggestion. 

Thanks.
