### ISSUE TITLE
OPTIONS response without content-length

### ISSUE THREAD

**Issue by jeanbiber** [CrowCpp/Crow#402]
The OPTIONS response doesn't contain a content-length field. I think that the response must include a Content-Length field with a value of 0.

**Comment by jeanbiber** [comment]
If I set "res.manual_length_header = false;" (routing.h Line 1489) it works for me but I am not sure if it's the right solution for this issue.

**Comment by The-EDev** [comment]
Confirmed. According to [RFC2616 section 9.2](https://www.rfc-editor.org/rfc/rfc2616#section-9.2):
>  the response MUST include a Content-Length field with a field-value of "0".

Thank you @jeanbiber for reporting this issue.
