### ISSUE TITLE
Current release doesn't compile in Visual Studio

### ISSUE THREAD

**Issue by fentonscode** [CrowCpp/Crow#407]
Following the instructions at [here](https://crowcpp.org/getting_started/setup/windows/) unfortunately results in compilation errors.

It appears there is a problem in `example_with_all.cpp` on line 38 which generates:

`Error	C2440	'<function-style-cast>': cannot convert from 'initializer list' to 'crow::json::wvalue'`

In addition, it was not possible to get this far without adding the following to the automatically generated `crow_all.h`:

`#pragma warning(disable: 4267)`
`#pragma warning(disable: 4244)`

Which hints at some potential future issues which may arise. It's also worth noting that ReSharper is highlighting all of the `CROW_ROUTE` macros and reporting a substitution failed error.

Are there some more detailed step-by-step instructions to follow to start using this project?

My current use-case is a Windows only server with dependencies included as full source (no binaries).

Happy to contribute back if there's some fixes that are relatively short.

**Comment by The-EDev** [comment]
Hi, sorry for the late response.

>It appears there is a problem in example_with_all.cpp on line 38 which generates:
>
>Error C2440 '<function-style-cast>': cannot convert from 'initializer list' to 'crow::json::wvalue'

This is very weird, `wvalue` should have a constructor for initializer lists. The only other time I encountered this error was when someone was using `v0.3` with one of the examples. I hope by "current release" you mean `v1.0+1` and not `v0.3+4`.

> In addition, it was not possible to get this far without adding the following to the automatically generated crow_all.h:
>
> #pragma warning(disable: 4267)
> #pragma warning(disable: 4244)

This is an issue with `merge_all.py` where `include` line breaks and `#pragma`s aren't removed

>Which hints at some potential future issues which may arise. It's also worth noting that ReSharper is highlighting all of the `CROW_ROUTE` macros and reporting a substitution failed error.

Correct me if I'm wrong but everywhere I went I read "Substitution failure is not an error", in fact Crow relies heavily on SFINAE with regards to routes and route creation.

**Comment by fentonscode** [comment]
Hi, thanks for looking into this!

By current version, I mean a direct clone of the repo as of 9 days ago, which was at least 1.0 + 1 when checked against the tags. As the project was a bit time critical (aren't they all!) I ended up using a different service, but would like to know if this can be resolved as the current one I'm using has issues as well (run-time rather than compile-time unfortunately).

Did you mean that `merge_all.py` should _not_ remove pragmas? As my output file was full of extra breaks, but definitely missing those warning settings.

As I didn't get to compile the source I didn't get to review the design as to whether SFINAE is desirable here or not. I will try again this weekend to see if I can get a bare-bones W10 project to work and report back.

**Comment by The-EDev** [comment]
Closing as stale, if anyone is facing the same issue please let me know and I'll reopen it.
