### ISSUE TITLE
How to set a custome 404 page.

### ISSUE THREAD

**Issue by Avihais12344** [CrowCpp/Crow#412]
Hello everyone,
I am building a web server using crow,
and When I try to get to crow to a invalid route (route I haven't set), it gets me to a 404 page, I want to customize that page (or at least have a custom function to customize it).
How do I do that?
Thanks in ahead

**Comment by The-EDev** [comment]
Hi, Crow has [Catchall routes](https://crowcpp.org/guides/routes/#catchall-routes) which you can use to handle any routes not defined (such as those returning `404` or `405`). you do need to check that `res.code == 404` before redirecting to the `404` page

**Comment by Avihais12344** [comment]
And I am using it the same way as the `CROW_ROUTE` macro?

**Comment by The-EDev** [comment]
pretty much yeah.

**Comment by Avihais12344** [comment]
Ok, thank you very much!
