### ISSUE TITLE
Allow CROW_STATIC_DIRECTORY to be an absolute path, while retaining sanitization

### ISSUE THREAD

**Issue by joelguittet** [CrowCpp/Crow#413]
Hello,

I have notice it is not possible to set CROW_STATIC_DIRECTORY an absolute path because it is sanitized.

In my context (and I'm probably not the only one), my application is automatically started from another place (using systemd). If multiple libraries all require to have a specific run directory to be used then it's totally blocked there is no solution and so defining a absolute path is required.

This was a bit discussed at https://github.com/CrowCpp/Crow/issues/343 but there is no real conclusion.

I would suggest the following lines should be changed to use the `set_static_file_info_unsafe` method instead of `set_static_file_info`:
- https://github.com/CrowCpp/Crow/blob/master/include/crow/app.h#L242
- https://github.com/CrowCpp/Crow/blob/master/include/crow/app.h#L255

What do you think ?

Joel

**Comment by The-EDev** [comment]
Since the static folder allows any user to enter a path, using unsafe functions would allow a malicious user to just add `../` and navigate to wherever they want on your server.

A better approach would be to manually sanitize `file_path_partial`  and then using the unsafe function, this allows the developer to set whatever path they want while still sanitizing any user input.

**Comment by joelguittet** [comment]
Hello @The-EDev 

Good point, we should not allow an user input to go throw the entire file system.

Something like:

```
route<crow::black_magic::get_parameter_tag(CROW_STATIC_ENDPOINT)>(CROW_STATIC_ENDPOINT)([](crow::response& res, std::string file_path_partial) {
    utility::sanitize_filename(file_path_partial);
    res.set_static_file_info_unsafe(CROW_STATIC_DIRECTORY + file_path_partial);
    res.end();
});
```

I can test and submit a PR (with blueprint use case as well).

Joel

**Comment by The-EDev** [comment]
> I can test and submit a PR (with blueprint use case as well).

Thanks, Feel free to :)
