### ISSUE TITLE
An uncaught exception occurred: _Map_base::at (when an extension isn't found in `mime_types.h`)

### ISSUE THREAD

**Issue by joelguittet** [CrowCpp/Crow#415]
Hello,

I'm getting the error in the title while trying to retrieve bootstrap files. Log is bellow:

```
(2022-04-21 21:54:03) [INFO    ] Request: 192.168.1.20:53661 0x18473e0 HTTP/1.1 GET /static/bootstrap/bootstrap.min.css
(2022-04-21 21:54:03) [INFO    ] Response: 0x18473e0 /static/bootstrap/bootstrap.min.css 200 0
(2022-04-21 21:54:03) [INFO    ] Request: 192.168.1.20:53666 0x75805638 HTTP/1.1 GET /static/bootstrap/bootstrap.min.js
(2022-04-21 21:54:03) [INFO    ] Response: 0x75805638 /static/bootstrap/bootstrap.min.js 200 0
(2022-04-21 21:54:03) [INFO    ] Request: 192.168.1.20:53669 0x75801a50 HTTP/1.1 GET /static/bootstrap/bootstrap.min.css.map
(2022-04-21 21:54:03) [ERROR   ] An uncaught exception occurred: _Map_base::at
(2022-04-21 21:54:03) [INFO    ] Response: 0x75801a50 /static/bootstrap/bootstrap.min.css.map 500 0
(2022-04-21 21:54:03) [INFO    ] Request: 192.168.1.20:53669 0x75801a50 HTTP/1.1 GET /static/bootstrap/bootstrap.min.js.map
(2022-04-21 21:54:03) [ERROR   ] An uncaught exception occurred: _Map_base::at
(2022-04-21 21:54:03) [INFO    ] Response: 0x75801a50 /static/bootstrap/bootstrap.min.js.map 500 0
```

This is raised here: https://github.com/CrowCpp/Crow/blob/master/include/crow/routing.h#L1359 and I don't know why at all.

The 2 files are available of course (404 error returned if they are not).

Any help is appreciated :-)

Joel

**Comment by joelguittet** [comment]
Note to myself and to be tested: is it because map extension is not available in https://github.com/CrowCpp/Crow/blob/master/include/crow/mime_types.h ?

`{"map", "application/javascript"},` to be checked :-)

**Comment by joelguittet** [comment]
Tested and working, this was only because the mime type was not defined :-)
Creating a PR now.

**Comment by The-EDev** [comment]
> Tested and working, this was only because the mime type was not defined :-)
Creating a PR now.

@joelguittet please don't create a PR manually updating `mime_types.h`, it's a file automatically generated using `scripts/nginx_mime2cpp.py`

**Comment by joelguittet** [comment]
Yes I just realized that too.
How to handle this issue ?

**Comment by The-EDev** [comment]
I would first go with my suggestion #410, adding an `if` statement for when the extension isn't found, adding a custom mimetype as an argument to `set_static_file_info` (as an overload possibly), and either finding a different source for mime types or seeing if Nginx updated their mime type list.

**Comment by joelguittet** [comment]
@The-EDev I'm looking at https://github.com/CrowCpp/Crow/pull/411, merged in master, but obviously not available in the last release (I'm using). Maybe this PR is also suitable to fix the issue ?

Just looked at nginx, there is no map extension is the latest file used by the python script.

**Comment by joelguittet** [comment]
@The-EDev just tested with the latest commit on master instead of the 1.0+1 release: issue is gone.
We can close this issue.

**Comment by The-EDev** [comment]
I apologize, I didn't look well into #411, it does seem to be fixing the base problem by adding `if (mimeType != mime_types.end())`. Though it still doesn't do anything to address passing a custom mime type as the `Content-Type` without editing `mime_types.h`.

I'll close this issue and create a new one for the things #411 doesn't address.

Sorry again for not being attentive enough.

**Comment by joelguittet** [comment]
@The-EDev no problem, thanks for help :-)
