### ISSUE TITLE
Add headers to OPTIONS/HEAD methods for CORS headers

### ISSUE THREAD

**Issue by samichoulo911** [CrowCpp/Crow#417]
I am currently having issues with some requests due to CORS. I was able to fix my GET/POST methods with the following headers
```
response.add_header("Access-Control-Allow-Origin", "*");
response.add_header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
response.add_header("Access-Control-Allow-Methods", "PUT, POST, GET, DELETE, OPTIONS");
response.add_header("Content-Type", "text/plain");
```

My issue is when I try to make PUT requests, since they make preflight OPTIONS request. I believe this issue (https://github.com/CrowCpp/Crow/pull/117) catches all the OPTIONS/HEAD requests preventing me from adding my own handlers for my routes. Is there a way to configure global headers for all incoming requests? I was thinking of using midleware but I am not sure it is the way to go.

**Comment by The-EDev** [comment]
Hi, does [this guide](https://crowcpp.org/guides/CORS/) address your issue?

**Comment by samichoulo911** [comment]
Yes! This is exactly what I was looking for, I was using an old version so I didn't have the CORS middleware thanks!

**Comment by agribov** [comment]
Hi @The-EDev - I'm having the same issue on the current version of CrowCpp, while using the CORs middleware. The browser sends a preflight OPTIONS request and gets back a 204 without CORs headers, and I'm not sure how to set it up to fix that. The guide you linked above no longer works, and the [current guide](https://crowcpp.org/1.0/guides/CORS/) does not explain this, and also has a broken link to the methods documentation. Do you have any suggestions on how I can get my app to reply to the OPTIONS request correctly?
