### ISSUE TITLE
Conan package doesn't seem to be working

### ISSUE THREAD

**Issue by konradkar2** [CrowCpp/Crow#418]
I've tried to include your package to my project using Conan, and it seems to not work correctly.

I tried it like this
[requires]
crowcpp-crow/1.0+1

with flag --build=missing

Boost 1.77 was correctly installed but the package itself not.
Here's my output from "tree" in .conan/data/crowcpp-crow directory
.
└── 1.0+1
    └── _
        ├── _
        │   ├── dl
        │   │   ├── export
        │   │   │   └── conan_export.tgz
        │   │   └── pkg
        │   │       └── 36dcbc6f6b87a997e9c9a47f12417de719c51d35
        │   │           └── conan_package.tgz
        │   ├── export
        │   │   ├── conandata.yml
        │   │   ├── conanfile.py
        │   │   └── conanmanifest.txt
        │   ├── locks
        │   │   └── 36dcbc6f6b87a997e9c9a47f12417de719c51d35
        │   ├── metadata.json
        │   ├── metadata.json.lock
        │   └── package
        │       └── 36dcbc6f6b87a997e9c9a47f12417de719c51d35
        │           ├── conaninfo.txt
        │           ├── conanmanifest.txt
        │           ├── include
        │           │   ├── crow
        │           │   │   ├── app.h
        │           │   │   ├── ci_map.h
        │           │   │   ├── common.h
        │           │   │   ├── compression.h
        │           │   │   ├── http_connection.h
        │           │   │   ├── http_parser_merged.h
        │           │   │   ├── http_request.h
        │           │   │   ├── http_response.h
        │           │   │   ├── http_server.h
        │           │   │   ├── json.h
        │           │   │   ├── logging.h
        │           │   │   ├── middleware_context.h
        │           │   │   ├── middleware.h
        │           │   │   ├── middlewares
        │           │   │   │   ├── cookie_parser.h
        │           │   │   │   ├── cors.h
        │           │   │   │   └── utf-8.h
        │           │   │   ├── mime_types.h
        │           │   │   ├── multipart.h
        │           │   │   ├── mustache.h
        │           │   │   ├── parser.h
        │           │   │   ├── query_string.h
        │           │   │   ├── returnable.h
        │           │   │   ├── routing.h
        │           │   │   ├── settings.h
        │           │   │   ├── socket_adaptors.h
        │           │   │   ├── task_timer.h
        │           │   │   ├── TinySHA1.hpp
        │           │   │   ├── utility.h
        │           │   │   ├── version.h
        │           │   │   └── websocket.h
        │           │   └── crow.h
        │           └── licenses
        │               └── LICENSE
        ├── _.count
        └── _.count.lock

Obviously something is not working as it should be, there are no binaries.

**Comment by The-EDev** [comment]
The files seem to all be there, Crow is a header only library, meaning there are no binary files. I hope this helps.

**Comment by konradkar2** [comment]
Well my problem is actually cmake, where find_package(Crow REQUIRED) doesn't seem to work because there is no FindCrow.cmake or CrowConfig.cmake(or its variants) installed.

For a different lib e.g fmt there is bunch of them
./home/konrad/.conan/data/fmt/8.1.1/_/_/build/e4d1bd3b01977fcaa1c0cad53092eee13ff17f8f/build_subfolder/source_subfolder/fmt-targets.cmake
./home/konrad/.conan/data/fmt/8.1.1/_/_/build/e4d1bd3b01977fcaa1c0cad53092eee13ff17f8f/build_subfolder/source_subfolder/CMakeFiles/Export/lib/cmake/fmt/fmt-targets.cmake
./home/konrad/.conan/data/fmt/8.1.1/_/_/build/e4d1bd3b01977fcaa1c0cad53092eee13ff17f8f/build_subfolder/source_subfolder/CMakeFiles/Export/lib/cmake/fmt/fmt-targets-release.cmake
./home/konrad/.conan/data/fmt/8.1.1/_/_/build/e4d1bd3b01977fcaa1c0cad53092eee13ff17f8f/build_subfolder/source_subfolder/fmt-config.cmake
./home/konrad/.conan/data/fmt/8.1.1/_/_/build/e4d1bd3b01977fcaa1c0cad53092eee13ff17f8f/build_subfolder/source_subfolder/fmt-config-version.cmake

Now I'm new to Conan and not really familiar with CMake packages, but I'm only guessing that there is a problem with this code being executed by Conan.
https://github.com/CrowCpp/Crow/blob/master/CMakeLists.txt#L124

**Comment by konradkar2** [comment]
Turned out that there is actually no need to use find_package(...) at all.
All I had to do was simply include <crow.h> in my source file - cmake generated by Conan included  lib directory for me.

So, concluding - I'm not sure if package is correctly added to Conan(whether it should generate that FindCrow.cmake somewhere in the files), but definitely works. You could add a note on Setup section, for dummies like me.
