### ISSUE TITLE
`.deb` package should install dependencies (asio)

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#420]
There seems to be an issue with generating the `.deb` file where boost isn't specified as a dependency. thus causing `dpkg` to only install Crow.

@Leon0402 if you can help with this issue I would very much appreciate it, since you mentioned working on something similar before.

**Comment by The-EDev** [comment]
The issue seems to be that `CPACK_DEBIAN_PACKAGE_SHLIBDEPS` doesn't work due to the fact that `shlibdeps` requires an executable.

The fix should be to do something like `set(CPACK_DEBIAN_PACKAGE_DEPENDS "libboost-dev (>= 1.64.0.1)")`

**Comment by Leon0402** [comment]
I wasn't aware that shlipdeps is only working for executables, but it would be possible. If I remember correctly `shlibdeps` wasn't able to pick up my dependencies either except when I explicitly produced them. 

I use something like this to install all runtime dependencies and exclude all system specific stuff
``` 
install(TARGETS MyTarget COMPONENT MyComponent
  RUNTIME_DEPENDENCIES
    PRE_EXCLUDE_REGEXES 
        # Linux
        [[libc\.so\..*]] # libc
        [[libgcc_s\.so\..*]] #libgcc
        [[libm\.so\..*]] # libm
        [[libstdc\+\+\.so\..*]] # libstdc++
        [[libpthread-*\.so]] # libpthread
)
```

I then set a private dir for searching 
``` 
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS_PRIVATE_DIRS "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}")
```

(This is where my libraries go as I set explicitly `CMAKE_RUNTIME_OUTPUT_DIRECTORY` and `CMAKE_LIBRARY_OUTPUT_DIRECTORY`)

I probably will do some more experiments in the future to figure out how exactly all that stuff is working. I would probably recommend just specifying the dependencies manually as you proposed. This is the easiest and most robust solution.

**Comment by The-EDev** [comment]
previous comments mentioning `libboost` need to have it replaced with ASIO
