### ISSUE TITLE
Weird latency on PUT requests

### ISSUE THREAD

**Issue by samichoulo911** [CrowCpp/Crow#426]
I am getting huge latency on PUT requests (around 5seconds running on the same machine).
This issue does not happen when running the request from a client (postman, isomnia, curl) but happens when running on browser (tested on firefox and chrome). I believe the issue is caused by the preflight request as it is the only difference between the client and the browser I could find. 

I am using the CORS middleware.
I tested using a node server (quick setup using NESTJs) and the put request had no peculiar latency.

This is a simple setup for the server to get the endpoint setup
` crow::App<crow::CORSHandler> app;`
` CROW_ROUTE(app, "/").methods("GET"_method)([]() { return "Test"; });`

To run the PUT command in the browser with no previous setup simply run this code in the browser console.The response should be printed to the console right when it resolves and for details check the network tab of the browser.
`fetch("http://localhost:18765/", {method: "PUT", headers: { 'Content-Type': 'application/json' },}).then((r) => console.log(r))`

I believe this might be the same issue as https://github.com/CrowCpp/Crow/issues/401

**Comment by samichoulo911** [comment]
After changing the timeout to 0 based on the linked issue, I am no longer getting the latency. I tried looking in the lib's code but was unable to find an obvious issue.

**Comment by The-EDev** [comment]
Unfortunately similar to #401, this issue is inconsistent, I appreciate the steps to reproduce but it worked flawlessly for me, using both GET and PUT as the only possible method, I was able to process the preflight request and the PUT request within 3ms in Waterfox (firefox based) and Falkon (Chrome based), it's worth mentioning I haven't altered any of the CORS settings..

**Comment by The-EDev** [comment]
I'll close this issue as a duplicate and add your comment to #401
