### ISSUE TITLE
v1.0+2 compile error: operator""_method redefined

### ISSUE THREAD

**Issue by MichaelSB** [CrowCpp/Crow#427]
Using the tag v1.0+2 I get the following error compiling the hello world example:

```
crow/include/crow/common.h:328:28: error: redefinition of 'constexpr crow::HTTPMethod operator""_method(const char*, size_t)'
  328 | constexpr crow::HTTPMethod operator"" _method(const char* str, size_t /*len*/)
```

Using tag v1.0+1 the example compiles just fine. I tracked this down to commit dcbfc3e, which indeed redefines the operator. I think there is an #else missing? Adding the #else makes the program compile

**Comment by MichaelSB** [comment]
Sorry, just realized this is already fixed in master. Ignore the noise please.

**Comment by The-EDev** [comment]
I apologize, I created this issue while solving a merge conflict, and I didn't double check to make sure everything was in order, I'll update the release ASAP

**Comment by The-EDev** [comment]
Release Updated on GH and AUR (it wasn't published elsewhere). @MichaelSB Could you please check that everything is working now?

**Comment by kolomenkin** [comment]
Thanks from me too )))
Very quick fix )))

**Comment by The-EDev** [comment]
That's good to hear, I'll close this issue now
