### ISSUE TITLE
Some resolved bugs are still in the new version v1.0+2

### ISSUE THREAD

**Issue by jeanbiber** [CrowCpp/Crow#428]
1 - "multiple definition" in /middlewares/cors.h (inline is missing)

2 -  ssl connection issue for websocket in http_connection.h (#ifdef CROW_ENABLE_SSL line 132)

**Comment by The-EDev** [comment]
I'll update the release ASAP

**Comment by The-EDev** [comment]
Release Updated on GH and AUR (it wasn't published elsewhere). @jeanbiber Could you please check that everything is working now?

**Comment by The-EDev** [comment]
following the comments in #427, I'll close this issue, please reopen if I missed anything.
