### ISSUE TITLE
Custom status codes handling

### ISSUE THREAD

**Issue by konradkar2** [CrowCpp/Crow#430]
If an endpoint returns a status that does't exist in this map 
https://github.com/CrowCpp/Crow/blob/master/include/crow/http_connection.h#L270

the actual returned code is set to 500 
https://github.com/CrowCpp/Crow/blob/master/include/crow/http_connection.h#L319

This happens without any warning log (I've checked with debug level).
Imo the easiest solution is to add a warning log to the block that sets it to 500, this would help a lot when debugging.

(I've encountered this when writing UTs, using some arbitrary values)

**Comment by The-EDev** [comment]
> Imo the easiest solution is to add a warning log to the block that sets it to 500, this would help a lot when debugging.

I Agree, something like "Status code not defined.", in addition to putting Crow's defined status codes in a documentation page would be ideal.

@konradkar2 let me know if you want to create a PR for this or if you would rather I do it :)

**Comment by The-EDev** [comment]
In the future maybe a compile time check could be added.

**Comment by konradkar2** [comment]
> > Imo the easiest solution is to add a warning log to the block that sets it to 500, this would help a lot when debugging.
> 
> I Agree, something like "Status code not defined, returning 500 instead.", in addition to putting Crow's defined status codes in a documentation page would be ideal.
> 
> @konradkar2 let me know if you want to create a PR for this or if you would rather I do it :)

I can try :)
