### ISSUE TITLE
Crow::remove_websocket: does not erase connection from vector

### ISSUE THREAD

**Issue by MichaelSB** [CrowCpp/Crow#449]
I think this is a bug. `Crow::remove_websocket` only removes the connection from the vector `websockets_`. In `Crow::stop()` `close()` is called for every element in the vector. So imo the connections should actually be erased.
```diff
+++ b/include/crow/app.h
@@ -370,7 +370,7 @@ namespace crow
 
         void remove_websocket(crow::websocket::connection* conn)
         {
-            std::remove(websockets_.begin(), websockets_.end(), conn);
+            websockets_.erase(std::remove(websockets_.begin(), websockets_.end(), conn), websockets_.end());
         }
 
         /// Print the routing paths defined for each HTTP method
```
or probably with `std::erase`

**Comment by The-EDev** [comment]
Looking up the difference it seems like your approach is correct, could you please open a PR to fix this?

Thanks!

**Comment by MichaelSB** [comment]
Sure, will do :)
