### ISSUE TITLE
 Internal error: Trie header should be simple!

### ISSUE THREAD

**Issue by akjt** [CrowCpp/Crow#455]
I am getting the following exception when I invoke .run against a SimpleApp.

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Internal error: Trie header should be simple!
```

I cannot find any docs into what this exception actually means? Any ideas?

**Comment by The-EDev** [comment]
Could you please describe the routes you're trying to use? The error most likely means you have a problematic route endpoint.

**Comment by akjt** [comment]
Ahh thanks. Correct, my url was missing a "/" in the front
