### ISSUE TITLE
Is it possible to pass a variable URL to CROW_ROUTE

### ISSUE THREAD

**Issue by akjt** [CrowCpp/Crow#456]
So I am getting the feeling that no matter what I do I cannot store a `char (& url)[N] `and then pass that url to the `CROW_ROUTE`. 

Is that true and any way to circumvent this:

```cpp
            CROW_ROUTE(m_app, "m_url").method(,,,) ---> this works
    
           template<unsigned N>
           class  RegisterMethod
            const char (& url)[N] ;
         
          RegisterMethod(const char (&url)[N]) : m_url(url) {};
          
          register_(){
              CROW_ROUTE(m_app, m_url).method(...) --> this generates an error: error: no matching member function for call to 'route'
           }
```   
Is that because the route method takes a std::string&& while the paramter_tag takes a const_str

**Comment by The-EDev** [comment]
If you want to use a variable you can use `app.route_dynamic()`. But keep in mind that changing your variable won't change the endpoint, since the route tree is calculated at the start of the program.

**Comment by The-EDev** [comment]
I tried to do something similar for #414 but the issue I ran into was that `route()` uses `crow::black_magic::const_str` which looks quite similar to your `RegisterMethod`. I'm not 100% sure if what you want is possible, but if it is, you would need to look at `const_str`. I hope this helps.

**Comment by The-EDev** [comment]
The difference is that `route_dynamic` doesn't provide compile time errors about the route, all the errors happen during runtime, which is less than ideal..

**Comment by The-EDev** [comment]
Closing this as resolved, @akjt please let me know if you still have more questions regarding this matter.
