### ISSUE TITLE
CORS questions with localhost

### ISSUE THREAD

**Issue by blacktion** [CrowCpp/Crow#458]
Here’s the CORS config I used:
```cpp
        crow::App<crow::CORSHandler> app;
	auto& cors = app.get_middleware<crow::CORSHandler>();
	cors
		.global()
		.origin("*")
		.headers("origin, x-requested-with, accept, access-control-allow-origin, authorization, content-type")
		.methods("POST"_method, "GET"_method, "PUT"_method, "DELETE"_method, "PATCH"_method, "OPTIONS"_method)
		.allow_credentials();
```
When I visit my server with local ip like this from web, everything is ok (http://192.165.152.30:30025/try), but when I visit it with 127.0.0.1(http://127.0.0.1:30025/try), it comes up with the CORS problem. 
I got this:
```
Access to XMLHttpRequest at 'http://127.0.0.1:30025/try' from origin 'http://192.165.152.30:8080' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `local`.
```
And I found that the config such as headers and origin had not added to it.
How could I solve the problem?

**Comment by The-EDev** [comment]
What IP do you have defined in for the app?

**Comment by The-EDev** [comment]
closing for a lack of response, @blacktion please let me know if you're still interested in fixing this issue and I'll reopen it.
