### ISSUE TITLE
Zlib HTTP compression

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/crow#46]
ipkn#144

Should support compression and decompression for http requests.

This could be needed before HTTP/2 could be implemented.

**Comment by The-EDev** [comment]
The first PR seems good, but is a middleware, which might not workout since I believe header compression is part of HTTP/2.

The second is not middleware but only runs on websockets.

**Comment by mrozigor** [comment]
I think that compression should be enabled by default, as a part of framework. Maybe it should be option to disable it from configuration file?
