### ISSUE TITLE
It seems that run_async still blocks the running thread

### ISSUE THREAD

**Issue by akjt** [CrowCpp/Crow#462]
When I am debugging my code I realized that after having ran m_app.run_async() my running thread never returns from the call and the server is opened.
Was the intent with run_async not to **not** block the running thread? 

This is how I run it:
`        m_app.bindaddr(m_bindaddr).port(m_port).run_async();`  

   `   std::cout << "Hello again ;` // this never gets executed `

**Comment by akjt** [comment]
We must save the return value:

` auto runner = m_app.bindaddr(m_bindaddr).port(m_port).run_async();`

**Comment by The-EDev** [comment]
@akjt Thanks for the info, I'll make sure to include it in the documentation.

**Comment by maxdgaa** [comment]
Hi, my run_async call is still blocking, even though I save it in a variable. Additionally, if I make the variable a member of a class, the app segfaults.
