### ISSUE TITLE
what would happen if i request with a large body

### ISSUE THREAD

**Issue by qza2468** [CrowCpp/Crow#468]
i'm dealing with sending large amount of data by the HTTP client. 
i wonder what would happen to this, could i receive the body part by part using a callback.
it's obvious not a good idea to store all them in body and read. 
does `crow` have some internal things to help with this? or how could i write an extension to it.

**Comment by The-EDev** [comment]
Well, if your file exceeds a [certain size limit](https://crowcpp.org/master/reference/classcrow_1_1_crow.html#ae92390d22f6fc99987c41a617be71d64) Crow will automatically split it into smaller chunks before sending them down the socket. If you want to send the client multiple HTTP responses without them making a request for each one, then unfortunately that's not allowed in HTTP/1.1 and was only introduced in HTTP/2.

**Comment by The-EDev** [comment]
Closing as resolved, @qza2468 let me know if you need any more help or if I didn't answer your question adequately.

**Comment by zwliuf** [comment]
@The-EDev the question is about request with large body from client, not response with large body sending from crow. when sending a request with arge amount of data in body to crow server, the server will get a crow::request whose body is very large, and it's all in memory. can the body be streamed into a file part by part?
