### ISSUE TITLE
`set_static_file_info` would cause response never be sent.

### ISSUE THREAD

**Issue by qza2468** [CrowCpp/Crow#469]
i write an example code to prove my thinking.
``` c++

#include <crow.h>

crow::response aaa(const crow::request &req) {
    crow::response resp(200);
    resp.set_static_file_info("/home/qza2468/Downloads/mmmmmApp.txt");

    return resp;
}


int main() {
    crow::SimpleApp app;

    CROW_ROUTE(app, "/aaa").methods(crow::HTTPMethod::POST)(aaa);
    app.port(18000).multithreaded().run();
}
```
There are two main problem.
1. if i use `set_static_file_info` like above, it will stuck(not sending any data to client) even if the path point to an exist file! 
    However, if i change it to `set_static_file_info_unsafe`, it will be ok. but there another problem like below.
2. no matter using `set_static_file_info` or `set_static_file_info_unsafe`. if the path not exist, it will stuck;

could someone tell me something about it, or what should i do to deal with it, if it's a bug:?

i compiled it with `g++` on `Ubuntu20.04`
``` bash
g++ aaa.cpp -lpthread
```

i'm using the most recent version `v1.0+3`

**Comment by qza2468** [comment]
i found the reason, it's all because the call of `response.end()`. it will be stuck after call it. just like below
``` c++
#include <crow.h>

crow::response aaa(const crow::request &req) {
    crow::response resp(200);
    resp.end();

    return resp;
}


int main() {
    crow::SimpleApp app;

    CROW_ROUTE(app, "/aaa").methods(crow::HTTPMethod::POST)(aaa);
    app.port(18000).multithreaded().run();
}
```

**Comment by qza2468** [comment]
you are right!
 i used to thought the handler must be type `response (*) (request &req)`  and need to return an response. i don't know there is another handler type(`void (*) (request req, response&resp)`)  which allows to return `void`! 
i wish you could add an example of the later type. it's really easy to make fault like this as document didn't have any example of the later handler type.

and i used the second handler type rewrite the first example, it's great. could `using both relative and absolute path` and `problem 2` is solved also, it will return 404 soonly if path not existed. code is like below;
``` c++
void aaa(const crow::request &req, crow::response &resp) {

    resp.code = 200;
    resp.set_static_file_info_unsafe("/home/qza2468/CLionProjects/untitl");
    resp.end();
}
```
but new questions coming:)
if path is to a `directory`, client will response like this after about **5 seconds**
    ``` org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 4,096; received: 0)```
    i wonder if it could response with 404. and i afraid it return the data of the dir, **could i config it only return normal file, and for other types, just return 404!**

also i know a little about how to fix `problem 1` finally. maybe we could manually call `resp.end()`, resp is returned by user-provided handler.

**Comment by MichaelSB** [comment]
Glad this helped :) If the path points to a directory, crow attempts to read that as a regular file, which won't work. So there's no way this returns the content of the directory afaict. That being said, I agree it would be better to return a 404 in all cases but regular files. Should be easy to fix, I'll prepare a PR for this.

**Comment by qza2468** [comment]
Thank you! now i can continue programming web with my favorite `c++`.
