### ISSUE TITLE
How do I access second element in an Json Array

### ISSUE THREAD

**Issue by akjt** [CrowCpp/Crow#471]
If have following:

{
  "array":[ 
      "key1" :"hello"
    ,
        "key1" :"hello2"
     ]
}

So far I am doing this:

```
auto json = crow::json::load(request.body);
auto array = json["array"];
auto key1 = array.lo() // this  what seems to be giving me access to the first element of the array
```

First question : Is function `.lo()` the one to be used to get to the array element
Second question: How do I access the next elements in the array. The above snippet seems to only be giving the first element

**Comment by The-EDev** [comment]
`.lo()` gives you access to an `std::vector` of `crow::rvalue`s, you should just be able to call `json["array"].lo()[1]`

**Comment by akjt** [comment]
That does not work. the lo() return a one sized vector

**Comment by The-EDev** [comment]
I'll close this issue as resolved, @akjt let me know if your issue persists

**Comment by DLi7077** [comment]
> That does not work. the lo() return a one sized vector

I was able to extract the entire array by taking each index from
`reqBody[key].lo()` and taking their value like:

`int x = reqBody[key].lo()[idx].i();`

and adding each converted element to the array
