### ISSUE TITLE
Using Code::Blocks IDE

### ISSUE THREAD

**Issue by m1c999** [CrowCpp/Crow#472]
I understand that Visual Studio is supported on Windows using VCPKG.  However, I cannot seem to find any documentation on what is required to be able to build using Code::Blocks.  Is there any documentation or pointers that can be provided?

**Comment by The-EDev** [comment]
@m1c999 I've honestly not used Code::Blocks before. I'll look into how to compile a Crow application on it and get back to you.

**Comment by m1c999** [comment]
Thank you very much. Much appreciated.

**Comment by The-EDev** [comment]
I tried Code::Blocks, All I needed to do was add the crow headers and in the linking options add "pthread". after that it compiled just fine.

Let me know if there's anything you're having a problem with.

**Comment by m1c999** [comment]
So do I just pull the code from the repo and create a new code blocks project in that directory and add the crow headers and change linking options?

**Comment by The-EDev** [comment]
Yeah that's pretty much what I did, although I used `crow_all.h`, although it shouldn't be too different with separate headers.

**Comment by m1c999** [comment]
Thanks will give it whirl and let you know how it went.

**Comment by m1c999** [comment]
I dont seem to be able to get the dependencies to work.  Do I need to include the boost libs using VCPKG or do I add them manually?

||=== Build file: Debug in Crow (compiler: GNU GCC Compiler) ===|
include\crow\query_string.h|9|fatal error: boost/optional.hpp: No such file or directory|
||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|

**Comment by luca-schlecker** [comment]
The Crow `master`-branch just dropped Boost as a dependency, but you will need the `asio` library nonetheless. Vcpkg can be combined with either Visual Studio directly or CMake in general, but it looks like Code::Blocks needs a hint at where these required headers are.

If you'd like to use Vcpkg for managing your dependencies (while still using Code::Blocks), then I'd suggest trying to manually include the headers installed by Vcpkg.
If you want to go that route, then you'll have to start off by following Step 1 & 2 from this [Vcpkg: Getting Started](https://vcpkg.io/en/getting-started.html) page. This will install Vcpkg, which will be used to pull the dependencies.

Then you'll need to execute the following: `./vcpkg install --triplet=x64-windows asio`. (I assume you're on Windows)
This will install the `asio` library, which is a C++ networking library and is required by Crow.

After that, you can go and add the following path to the include directories in Code::Blocks:
`C:\path\to\vcpkg\installed\x64-windows\include`
This will make the necessary headers available to Code::Blocks.

Now you'll need the latest version of Crow (there were some changes 5 hours ago) and then just add it to your project like @The-EDev already described.

This should in theory set you up with everything you need to get started with Crow.

**Comment by m1c999** [comment]
Thanks for your help on this guys, appreciate the patience.  Will try out the above (looks like this will solve my issue) and will let you know how I get on.

**Comment by m1c999** [comment]
An update: 

VCPKG failed in getting and installing the asio dependency.  I need to log an issue, it looks like some kind of path problem.

So I decided to download asio-1.22.1 and add that into Code Blocks and see if I could get it compiled this way.

Unfortunately I got errors which repeated this:

..\asio\asio-1.22.1\include\asio\detail\assert.hpp|29|error: there are no arguments to '_assert' that depend on a template parameter, so a declaration of '_assert' must be available [-fpermissive]|

As you mentioned I am trying to compile this on a Windows platform.  It may be easier to switch to a linux instance and start this process again.

Many thanks for your help guys!

**Comment by luca-schlecker** [comment]
Well, that's very weird... Asio is header-only, it should install without any problems... I am perfectly able to install `asio` with the help of Vcpkg... Maybe you can report the error you are facing.

There's another thing, I checked line 29 of [assert.hpp](https://github.com/chriskohlhoff/asio/blob/f0a1e1c7c0387ad16358c81eb52528f190df625c/asio/include/asio/detail/assert.hpp#L29) (the line your compiler is complaining about) and there is no occurrence of `_assert`, only `assert` from the header `<cassert>`...

**Comment by luca-schlecker** [comment]
Closing as it is not an issue with Crow you're facing.
My E-Mail is on my profile, so feel free to hit me up with the vcpkg error message you're encountering and I may be able to help you out.
