### ISSUE TITLE
can't found boost related file 

### ISSUE THREAD

**Issue by doraemon-hub-art** [CrowCpp/Crow#473]
As the title, i copy the example and compile it,but it return this

"/usr/local/include/crow/socket_adaptors.h:3:10: fatal error: asio.hpp: No such file or directory
    3 | #include <asio.hpp>
      |          ^~~~~~~~~~
compilation terminated.
"
I reinstall my boost library,and test boost , it is normal. but my Crow can't found.
Sorry,i' m a rookie.Please give an advice.Thanks for you.

**Comment by The-EDev** [comment]
@doraemon-hub-art As of yesterday, Crow no longer uses Boost as a dependency, instead it only requires ASIO to be installed.

**Comment by doraemon-hub-art** [comment]
> @doraemon-hub-art昨天，Crow 不再使用 Boost 依赖项，只需要改变 ASIO（独立版本）。

Sorry,I just learned about it.Thank for your reply.My problem is sloved.

**Comment by doraemon-hub-art** [comment]
@The-EDev Sorry,I just learned about it.Thank for your reply.My problem is sloved.
