### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by 0XPW87** [CrowCpp/Crow#487]
Hi,
I am using Crow for a webapp I am working on, together with libquickmail to send emails. Libquickmail works just fine on it's own, but whenever I use it in the Crow app it crashes. 

Respectively, I have a function in a shared library that sends an email. When I link that .so from a non-Crow program, all works fine, but when I link it from the Crow app, it either crashes (if not in a CROW_ROUTE macro; the program jsut returns -1 with no additional errors), or throws an SSL connect error (if used in the CROW_ROUTE macro).

SSL connect error: `OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to [SMTP SERVER ADDRESS]`

The email function itself doesn't change, and neither does the server address/login details. Is there anything in Crow that could be causing this to happen? So far, I've tried testing if it could be multi-threading (doesn't seem to be an issue), and loading from a .so (which also isn't an issue in a non-Crow app), but I am slightly running out of ideas. Libquickmail uses cURL, if that is significant.

I'd be very grateful for any advice, please ask if you need any more details

**Comment by 0XPW87** [comment]
Honestly could be, really not sure. I'll be honest, this is my first time working with ssl in c++, so everything is in the dark for me now. If it was, any suggestions on how to try it/fix it?

**Comment by The-EDev** [comment]
I'm not sure how it is with libquickmail, but with Crow, it is advised that you use it in non SSL mode with an HTTP proxy like Apache or Nginx, at least in production servers.

if you can somehow have Crow and libquickmail connect to an HTTP server application instead of directly to a client, it would be ideal.

**Comment by The-EDev** [comment]
That makes things even weirder.. by default SSL is disabled in Crow..

**Comment by MichaelSB** [comment]
You could try to add the openssl initialisation to the startup code of your app. Something like
```cpp
#include <openssl/ssl.h>

...
SSL_load_error_strings();
SSL_library_init();
...
```
at the beginning of main should do the job.

**Comment by 0XPW87** [comment]
Not sure. I couldn't get it to work. For now I just slapped in a temporary workaround, just to get it working.

**Comment by MichaelSB** [comment]
This was not the problem then likely :D It seems this message is issued by libcurl. Does the other application use the same SMTP-endpoint and is using the same setup as the crow-app? I wasn't able to reproduce this error so far in some experiments I did.

**Comment by MichaelSB** [comment]
Is there code you could share to reproduce the problem? A minimal example would be very appreciated. I have a SMTP-setup, so you don't need to share this :D Being able to debug the issue could help a lot. Other than the init phase of openssl I don't see how crow/asio would interfere with libcurl by just looking at the code :)

**Comment by 0XPW87** [comment]
Unfortunately I can't use the code I run, but I'll try to copy it to a new project, reproduce it, and if it still occurs I will share it with you. Thank you very much for all the help so far

**Comment by The-EDev** [comment]
closing the issue for the time being, @0XPW87 let me know if the issue still occurs and if you're able to reproduce it.
