### ISSUE TITLE
Is there a way to response in async callback?

### ISSUE THREAD

**Issue by Kidsunbo** [CrowCpp/Crow#489]
Hi, I would like to do a request to a database with an asynchronous interface. But the handle function for this request will return immediately because it's non-blocking. How to delay the response and make it work with asynchronous interface with callback?

**Comment by The-EDev** [comment]
What I would do as a workaround is just have a boolean to be set by the callback and block the request until it is set. This should be easier to do once #258 is implemented

**Comment by Kidsunbo** [comment]
> What I would do as a workaround is just have a boolean to be set by the callback and block the request until it is set. Handling async operations should be easier to do once #258 is implemented.

Yes, that looks great. Can't wait to try this feature. Thanks for you reply.
