### ISSUE TITLE
Pass a request to the router as soon as the URL is parsed

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#493]
Currently Crow's operation goes as: 
`establish connection` -> `move connection to worker thread` -> `parse entire request` -> `find the related route` -> `run the handler` -> `send the response string`.

Since finding the route only requires the method and URL (the very first 2 parts of a request), it should be possible to find out which route is being requested before the headers or body are parsed.

Doing this has the advantage of saving time parsing a request that would result in a `404` or a `405`. And paving the way for a per-route implementation of #397.

The primary challenge is getting the functionality in question from the connection and into the parser. The parser already contains callbacks at various points, those are currently being used to process the parsed data into a format that can easily be converted to a request. The easiest solution would be to add other callbacks that are assigned by the connection and are called from within the parser's original callbacks. That way the separation between the connection and parser remains mostly the same.

Another challenge is whether or not the rest of the request should be parsed in the case of a catchall handler. This however can be left up to the user either through a macro or an app function (since the app already gets passed to every connection as `_handler`)

**Comment by t-cadet** [comment]
@The-EDev 

> Another challenge is whether or not the rest of the request should be parsed in the case of a catchall handler. This however can be left up to the user either through a macro or an app function (since the app already gets passed to every connection as _handler)

At the moment the request is not being parsed in the case of a catchall handler (this is also mentioned in https://github.com/CrowCpp/Crow/issues/669). Is there a workaround to get access to the fully parsed request in a catchall handler? I did not find how to do it just from reading the docs and skimming the code. 

(I intend to use the catchall handler for custom routing)

**Comment by gittiver** [comment]
I moved your issue into a new one, to keep old fix and yours separately.
