### ISSUE TITLE
Bugs with c++20? 

### ISSUE THREAD

**Issue by akjt** [CrowCpp/Crow#504]
There are a couple of compile error when using c++20 compiler:

File json.h line: 1288 it should be changed to struct wvalue_reader
File json.h line 1278: Same as above

**Comment by dranikpg** [comment]
Can you leave the errors here? Clang 13 and gcc 11.2 on c++20 work for me (no errors & warnings)

**Comment by The-EDev** [comment]
I'm guessing the errors might occur in MSVC, here's a clangd warning (-Wmismatched-tags):
`json.h:1956:9: 'wvalue_reader' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI (fix available)`

**Comment by dranikpg** [comment]
Oh, my bad. I've overlooked this 😰 Lets collect fixes in https://github.com/CrowCpp/Crow/pull/505
