### ISSUE TITLE
Master branch fails to handle OPTIONS with `CORSHandler` middleware

### ISSUE THREAD

**Issue by DisableAsync** [CrowCpp/Crow#510]
v1.0+4's `CORSHandler` works fine. Haven't tried other versions nor tried to figure out what's wrong.

Just posting the issue here.

**Comment by DisableAsync** [comment]
And on v1.0+4, if `gzip` is enabled, `CORSHandler` will return a gzip'ed empty response (which is 20 bytes). Is this normal?

**Comment by dranikpg** [comment]
Sorry for the wait. I'll look at this today 👀

**Comment by dranikpg** [comment]
I'm using

```c++
#define CROW_ENABLE_COMPRESSION

#include "crow.h"
#include "crow/middlewares/cors.h"
#include "crow/compression.h"

int main()
{
    crow::App<crow::CORSHandler> app;
    app.get_middleware<crow::CORSHandler>().global();

    CROW_ROUTE(app, "/")
    ([](const crow::request& rsp) {
        return "ok";
    });

    app.port(18080)
        .use_compression(crow::compression::algorithm::GZIP)
        .run();
    return 0;
}
```

and then ```curl http://0.0.0.0:18080 -sH 'Accept-encoding: gzip' | gunzip``` to check the result. Works as expected :thinking:

Can you share an example?

Generally, all CORSHandler does, is setting headers. It doesn't prevent a response from being sent and doesn't cancel requests. The bug might be caused by something deep in the http handling chain.

**Comment by DisableAsync** [comment]
Wait, we now need to do that `.global();` thingy on `CORSHandler`? :thinking:

**Comment by The-EDev** [comment]
@DisableAsync a ~strikthrough~ is a single \~ character :).

With that being said, I'm guessing it's safe to close this issue, correct?

**Comment by DisableAsync** [comment]
> And on v1.0+4, if gzip is enabled, CORSHandler will return a gzip'ed empty response (which is 20 bytes).

~There is this minor issue, really minor I guess.~

Sure, safe to close.

**Comment by The-EDev** [comment]
I'll look into that, thanks for letting me know

**Comment by dranikpg** [comment]
> Wait,` we now need to do that .global(); thingy on CORSHandler? 

No, you don't. It'll set default values globally without it. I've just been trying specific header values and didn't remove the line fully

**Comment by DisableAsync** [comment]
> I'll look into that, thanks for letting me know

I wasn't able to reproduce in master, so maybe it was fixed at some point already.
