### ISSUE TITLE
How can I get the matched rule inside a routed handler?

### ISSUE THREAD

**Issue by junekhan** [CrowCpp/Crow#521]
I want to add some conditional routing based on session data. For example, I have a whitelist of route rules that can be only visited by a special group of people. I know I can achieve them one route by another, but I prefer a centric place where I check against a hash set of the rules.

**Comment by dranikpg** [comment]
Hi!

I'm not quite sure what you specifically have in mind. You can access the url/raw_url via 
```c++
struct request
{
  std::string raw_url;     ///< The full URL containing the `?` and URL parameters.
  std::string url;         ///< The endpoint without any parameters.
```

I you have one handler that is invoked by multiple rules, you can always invoke it via wrapper functions and pass the required information yourself.

> I prefer a centric place where I check

Middlewares were designed for such cases. I assume you're implementing something simillar in parallel. Check out 
https://crowcpp.org/master/guides/middleware/ for more info or ask directly here.

**Comment by junekhan** [comment]
@dranikpg Thanks! I mean I want to get something like `/path/<string>/<int>`, literally.

**Comment by The-EDev** [comment]
You could probably do something with route names (routes can have names but it's not really used anywhere in the framework)

**Comment by dranikpg** [comment]
> something like /path/<string>/<int>

There is not, as far as I know. But you can always create your own macro.
