### ISSUE TITLE
convert nlohmann::json to crow::mustache::context

### ISSUE THREAD

**Issue by christk1** [CrowCpp/Crow#526]
Is there any way to convert nlohmann::json to crow::mustache::context?
something like that:
```
// data contains json
        char name[256];
        gethostname(name, 256);
        crow::mustache::context x{data};
        x["servername"] = name;

        auto page = crow::mustache::load("index.html");
        return page.render(x);
```

**Comment by The-EDev** [comment]
The most straightforward way would be to convert your JSON value into a string, load it into json::rvalue then create a json::wvalue from that

**Comment by The-EDev** [comment]
The other way would be to create a wvalue by iterating over all the items and adding them to using `my_wvalue["key"] = value`

**Comment by christk1** [comment]
```
auto rv = crow::json::load(data.dump());
crow::json::wvalue wv{rv};
crow::mustache::context x{wv};
```
@The-EDev thanks a lot for the quick reply

**Comment by The-EDev** [comment]
@christk1 `crow::json::wvalue` and `crow::mustache::context` are one and the same, you can combine steps 2 and 3 in your last comment ;)
