### ISSUE TITLE
Crow/include/crow/middlewares/session.h not in released version 

### ISSUE THREAD

**Issue by sdwarwick** [CrowCpp/Crow#531]
Was interested in looking at crow/middlewares/session.h locally. I downloaded both 1.0-4 and 1.0-5 releases (src) and didn't find it included, even though it shows up in the  directory on github.

**Comment by The-EDev** [comment]
That's because every version after 1.0 (which was released months ago) was a patch that didn't include any features. the documentation for v1.0 is separate from master, master has the latest features but is less stable in comparison
