### ISSUE TITLE
Cannot build tutorial code from "getting started"

### ISSUE THREAD

**Issue by Deoxys0** [CrowCpp/Crow#533]
So I can't get the starter project/tutorial to build. I'm positive it's a CMakeLists issue due to the nature of the error I get (posted below), but I'm not sure specifically what it is. Crow was installed the default way using the getting started tutorial on Linux (not the manual way; the one where you git clone and do make install). 

cmake .. succeeds and even says "Crow found" but when I run make, I get this:
`/usr/bin/ld: cannot find -lCrow:Crow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/my-project-exe.dir/build.make:104: my-project-exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:124: CMakeFiles/my-project-exe.dir/all] Error 2
make: *** [Makefile:103: all] Error 2`

**THE PROJECT:**
main.cpp (in a folder called "src"):
`#include "crow.h"

int main()
{
    crow::SimpleApp app; //define your crow application
    //define your endpoint at the root directory
    CROW_ROUTE(app, "/")([](){
        return "Hello world";
    });

    //set the port, set the app to run on multiple threads, and run the app
    app.port(5000).multithreaded().run();
}`

CMakeLists.txt:
`cmake_minimum_required(VERSION 3.1)
#set(CMAKE_CXX_STANDARD 11)

set(project_name my-project)
project(${project_name})
MESSAGE(STATUS ${project_name})

#set_target_properties(${project_name} PROPERTIES LINKER_LANGUAGE CXX)

add_library(${project_name}
    src/main.cpp
)

target_include_directories(${project_name} PUBLIC src)

find_package(Crow REQUIRED)
IF (${Crow_FOUND})
   MESSAGE(STATUS "Found Crow")
ELSE (${Crow_FOUND})
    MESSAGE(STATUS "Failed to find Crow")
ENDIF (${Crow_FOUND})

target_link_libraries(${project_name}
    PUBLIC Crow:Crow
)

add_executable(${project_name}-exe
    src/main.cpp
)

target_link_libraries(${project_name}-exe ${project_name})
add_dependencies(${project_name}-exe ${project_name})`

Any help is much appreciated; also note that I'm still learning cmake so it's likely I made a mistake there.

EDIT: Sorry for the bad formatting, I'm not sure why some of the code sections aren't working.

**Comment by luca-schlecker** [comment]
In the linking step (`target_link_libraries`) you missed a colon.
It should be `Crow::Crow` instead of `Crow:Crow`.
I hope this helps 👍

**Comment by Deoxys0** [comment]
> In the linking step (`target_link_libraries`) you missed a colon. It should be `Crow::Crow` instead of `Crow:Crow`. I hope this helps 👍

holy shit thank you; it's always something really dumb on my end but I end up going down a rabbit hole trying to figure it out
