### ISSUE TITLE
Handling missing mime types gracefully

### ISSUE THREAD

**Issue by jake-arkinstall** [CrowCpp/Crow#534]
If a key isn't present in the mime_types map, an exception is thrown. This is because mime_types.at() is used at, e.g., https://github.com/CrowCpp/Crow/blob/c0bfaa7709fe9698c0989788ddee6c2cdf254043/include/crow/http_response.h#L104.

I propose that the resolution is to search for the provided mime_type within the map using `mime_types.find`. If it is not found, a warning should be logged, but the content should still be delivered using the following logic:

- Does the provided type [look like a MIME](https://datatracker.ietf.org/doc/html/rfc6838#section-4.2) type already? I.e. is it one of the IANA-registered types (application, audio, example, font, image, model, text, video), followed by a slash, followed by text? If so, send that verbatim.

- Otherwise send text/plain.

Although this approach isn't quite as lightweight as simply sending text/plain, there are some benefits:
- I'd be able, for example, to send content as `text/csv` without modifying the mime types map.
- It would also allow people to use the full mime-type format, including parameters (e.g. `text/plain;charset=UTF-8`)
- Developers coming from other technologies that use full mime types won't be faced with an internal server error for following an old habit.

**Comment by dranikpg** [comment]
I fully agree, the current solution is way to limited. If you need to construct custom mime-types now, you can always set the `Content-Type` header yourself. But this feels like a workaround.

Jake, if you want, you can implement the fix youself and make your first contribution to Crow! 🔥 

Else, I'll handle this in the following week.
