### ISSUE TITLE
Address Sanitizer exception on hello world example 

### ISSUE THREAD

**Issue by lookbusy1344** [CrowCpp/Crow#539]
I was trying the hello world example with VS2022 and Address Sanitizer. When I request 127:0.0.1:18080 in Edge browser, I get an Asan error.

Its caused by the request for “/favicon.ico” which seems to sometimes have whitespace (\x10 or \x13) at the end.
For some reason this causes qs_parse() in query_string.h to cause an asan error on the calls to strcspn().
I bodged a fix by stripping whitespace from the end of url_ in the query_string constructor. Is this just an artefact of Microsoft’s Asan implementation. Any thought?

**Comment by kiner-shah** [comment]
Can you provide details? Which compiler and its version, the trace returned by ASAN showing line numbers, etc.?
