### ISSUE TITLE
crow::mustache::load does not load the .html file no matter what

### ISSUE THREAD

**Issue by jakubcieslak22** [CrowCpp/Crow#542]
I am trying to write a simple HTTP app and cannot get this to work:
```
crow::mustache::set_base(".");
CROW_ROUTE(App, "/")([]()
	{
		crow::mustache::context ctx;
		auto mainPage = crow::mustache::load("C:\\Users\\xxxxx\\html\\sample.html"); //This is DEFINITELY the correct path, I've copied it
		return mainPage.render();
	});
```
The path doesn't originally look like this, I've modified it for privacy reasons, however it is definitely correct.
I've read some SO question which had the same issue as me (page loads, but it's blank) and the solution was to specify the full path to the .html file, so I did as someone wrote, however to no avail. I'm getting this warning in the console:
```
[WARNING ] Template "C_\Users\xxxxx\html\sample.html" not found. 
```
I'm getting a feeling that the underscore after C is supposed to be a colon but is getting substituted for some reason? And one other thing I was wondering about, what does ```crow::mustache::set_base()``` really do if you need to specify the full path to the page anyway?

**Comment by The-EDev** [comment]
The reason is that Crow automatically sanitizes paths to prevent path traversal attacks when calling `load()` with user input, if you aren't using user input you then [`crow::mustache::load_unsafe()`](https://crowcpp.org/master/guides/templating/#returning-a-template) should work for you.

**Comment by The-EDev** [comment]
IIRC `set_base` works only if called inside the route, `set_global_base` should be used if you want to set a default base.

**Comment by The-EDev** [comment]
Please let me know if You have any unanswered questions

**Comment by jakubcieslak22** [comment]
I changed ```set_base``` to ```set_global_base``` and ```load``` to ```load_unsafe``` and it still produces the same result.

**Comment by The-EDev** [comment]
are you using a relative path?

**Comment by jakubcieslak22** [comment]
Nope, still a full path. Shoul I use a relative one regarding where I did ```set_global_base```?

**Comment by The-EDev** [comment]
yes you should, you should also be able to set a full path in `set_global_base` but not in `load`

**Comment by jakubcieslak22** [comment]
Alright, I'll try it in a while and let you know how it came out. Thanks for the help.

**Comment by jakubcieslak22** [comment]
Alright, now it works. Thanks again.
