### ISSUE TITLE
Documentation: Missing `const` in code example

### ISSUE THREAD

**Issue by mobergmann** [CrowCpp/Crow#547]
In the documentation in the [Returning custom classes](https://crowcpp.org/master/guides/routes/#returning-custom-classes) chapter is the `const` keyword missing from the `dump` method declaration, in contrast to the [Source Code](https://crowcpp.org/master/reference/returnable_8h_source.html)
At least in my case a simple copy paste/ removing the const leads to the following compilation error: 
```
Non-virtual member function marked 'override' hides virtual member function
```

**Comment by gittiver** [comment]
fixed by https://github.com/CrowCpp/Crow/pull/659
