### ISSUE TITLE
HttpConnection Leakage

### ISSUE THREAD

**Issue by blippyblips** [CrowCpp/Crow#552]
There's a leaking HttpConnection in http_server.h:224:
`
auto p = new Connection<Adaptor, Handler, Middlewares...>(
                  is, handler_, server_name_, middlewares_,
                  get_cached_date_str_pool_[service_idx], *task_timer_pool_[service_idx], adaptor_ctx_, task_queue_length_pool_[service_idx]);
`

It only gets deleted in case of an error, if the connection is still open or successfully completed it doesn't get deleted on shutdown

**Comment by z16166** [comment]
I just get the same leak report with Visual Leak Detector(for Windows).

If I press CTRL + C to close my program before any successful client connection, it leaks.

If I add "acceptor_.cancel();" as the following, and add a bool flag to prevent it from calling "do_accept()" again on program shutdown,  it crashes when executing "delete p".

```
        void stop()
        {
            stop_ = true;

            acceptor_.cancel();
            io_service_.stop();
            for (auto& io_service : io_service_pool_)
                io_service->stop();
        }

```

```
        void do_accept()
        {
          if (stop_)
            return;

```

**Comment by z16166** [comment]
well, I have added a connection queue in crow::Server to manage all connections.
In crow::Server::stop(), just  call the Stop() method of each connection. 

```
        void crow::Server::CloseConnections() {
          decltype(connections_) conns;
          
          {
              std::lock_guard<std::mutex> guard{lock_};
              conns = std::move(connections_);
          }

          std::for_each(conns.begin(), conns.end(), [](auto &conn) { conn->Stop(); });
        }

```
The Stop() method of  crow::Connection is newly added:
```
        void Stop() {
            cancel_deadline_timer();

            adaptor_.shutdown_readwrite();
            adaptor_.close();
        }

```

also, when a crow::Connection object is created or deleted, just update the above queue/set.
