### ISSUE TITLE
Exception when start if CROW_ROUTE url not starts with /

### ISSUE THREAD

**Issue by xandross389** [CrowCpp/Crow#559]
If character "/" is missed at the begining of URL param in CROW_ROUTE declaration app not starts and throw exception with ambiguous message:

example:

`CROW_ROUTE(app, "api/v1/service/status")`

causes exception:

```
terminate called after throwing an instance of 'std::runtime_error'
 what():   Internal error: Trie header should be simple!
```

I suggest check specific condition and that cause exception and show correspondent message to the user

**Comment by StefanoPetrilli** [comment]
@The-EDev this one can be closed
