### ISSUE TITLE
crow conan package still have boost dependency

### ISSUE THREAD

**Issue by avimalka** [CrowCpp/Crow#563]
Hi,

It seems like CROW does not depend on boost, but on the conan recipe it is still listed as requirement:
https://github.com/conan-io/conan-center-index/blob/master/recipes/crowcpp-crow/all/conanfile.py#L34

**Comment by The-EDev** [comment]
Crow's `master` branch dropped boost, `v1.0` still uses it however. and since Conan does not offer the `master` branch. the latest package there is still boost dependent.

**Comment by LunarWatcher** [comment]
Thank you for dropping Boost though. 

Boost, and especially the Boost conan package, brings an enormous overhead to my build unless I disable the irrelevant components manually. Looking forward to Crow's Conan package eventually updating

**Comment by TheQue42** [comment]
Is there a release in the works for master/non-boost? My few attempts with master/ directly, gives me tons of "declaration of ‘XXXX’ shadows a previous local "?
