### ISSUE TITLE
Crash in optimizeNode on MSVC after commit 323a7cb

### ISSUE THREAD

**Issue by leksiso** [CrowCpp/Crow#567]
Commit 323a7cb48f52fedc056c94e1453a1e21651c3946 seems to make crow crash at startup on MSVC. The crash happens at optimizeNode in routing.h. Possibly something wrong with std::move() on line 762?

**Comment by okaestne** [comment]
Can you give more details about the exact crash cause?

**Comment by okaestne** [comment]
What looks like a likely issue is that `isSimpleNode()` doesn't check that there is ANY child in `children`. That way, we might try to optimize away a non-existing first child.

**Comment by leksiso** [comment]
> Can you give more details about the exact crash cause?

An exception seems to be thrown somewhere deep in the STL implementation (in a file called xmemory).
![image](https://user-images.githubusercontent.com/68514429/204784021-1469e004-12a0-40c6-9dec-a5d24bb94aa1.png)

Here's a stack trace:
![image](https://user-images.githubusercontent.com/68514429/204785875-45561e65-8a3c-4542-8fa4-4840f2c53f21.png)
What I gather from that is that we move some vector (the children?) and the contents end up somehow being invalid.

> Can you change the condition line 756 to if (node.children.size() == 1 && node.IsSimpleNode()) and test again?

This doesn't seem to fix it.

**Comment by leksiso** [comment]
I had a closer look at that. I think the problem has to be somewhat as follows:
When doing `node.children = std::move(child_temp.children);`,
the elements of node.children get destroyed/invalidated as the right-hand side of the assignment is about to replace them.
This invalidates `child_temp`  whose children we try to move next, which causes the exception.

Maybe we should move the children to a temporary variable before moving them back to to the node:
```
auto children_temp = std::move(node.children);
auto& child_temp = children_temp[0];
node.key += child_temp.key;
node.rule_index = child_temp.rule_index;
node.blueprint_index = child_temp.blueprint_index;
node.children = std::move(child_temp.children);
optimizeNode(node);
```

This seems to fix the crash.

**Comment by okaestne** [comment]
> > Can you change the condition line 756 to if (node.children.size() == 1 && node.IsSimpleNode()) and test again?
> 
> This doesn't seem to fix it.

There I had a thinking error. The `if` clause before this one already ensures that there has to be at least one child.


> I had a closer look at that. I think the problem has to be somewhat as follows: When doing `node.children = std::move(child_temp.children);`, the elements of node.children get destroyed/invalidated as the right-hand side of the assignment is about to replace them. This invalidates `child_temp` whose children we try to move next, which causes the exception.
> 
> Maybe we should move the children to a temporary variable before moving them back to to the node:

That makes sense to me and also explains why it worked before my change. Do you want to open a PR?
