### ISSUE TITLE
Crow httpserver blocks subsequent calls (on the same machine) for up to 30 seconds.

### ISSUE THREAD

**Issue by mark081** [CrowCpp/Crow#579]
- I have a C++ application that exposes a POST API 

- On the same machine (MacOS) I have a Electron/Node.js application that makes calls to both my local C++ app and Cloud-based web services

- GET calls made in the Electron app to the cloud are delayed by up to 30 seconds following a POST call to my C++ application (regardless of whether the POST call is made via my Electron app _or_ through PostMan.

**Comment by kiner-shah** [comment]
I think you need to debug this and find what exactly is causing this delay, some blocking call or some deadlock. Once you have found something, please update with that information here.

**Comment by gittiver** [comment]
I would close that issue in two weeks as we got no additional information on it.
