### ISSUE TITLE
Cookies don't work!

### ISSUE THREAD

**Issue by Romiro27** [CrowCpp/Crow#582]
I just copied the example, but it didn't work:
`main.cpp:70:31: ошибка: некорректное использование «void»
   70 |                 ctx.set_cookie("token", "2131").path("/").max_age(120).httponly();
      |                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
make: *** [Makefile:2: all] Ошибка 1
`
It's says "Bad usage to void"
What im doing wrong?

**Comment by mrozigor** [comment]
Hello. Which version of Crow are you using?

**Comment by Romiro27** [comment]
> Which version of Crow are you using?

crow 1.0+5-2

**Comment by mrozigor** [comment]
It is possible that the version you use has no change to cookies middleware (https://github.com/CrowCpp/Crow/commit/cee7f78ec8dd9fb2bfd349e8256d18eaf8124b7f). You can try use version from master.
