### ISSUE TITLE
Question about blueprints and static routes

### ISSUE THREAD

**Issue by xia-stan** [CrowCpp/Crow#585]
I'm serving my OpenAPI specification using the Swagger UI framework. I've got everything working using the SimpleApp object. I'm reworking the code to use blueprints. I am having trouble with the server not finding files in the expected paths. When using a blueprint with no overrides, I expect to need the following directory structure: 

- server.exe
- swagger/
   - static/
     - `all of the static files associated with the blueprint`
- templates/
  - swagger.html

The endpoint should be `http://localhost:18080/swagger/`. Logging (see below) shows that we find the template in the right spot (`templates/`) but it's looking for the static files with the `/swagger/` prefix. The [documentation notes that the final routes should be `<bp prefix>/static/<filename>`](https://crowcpp.org/master/guides/blueprints/#use-a-custom-static-directory), which doesn't seem to be working as expected. 

I've also reviewed #497. In my case, I just want the default behavior.

### Logs
> (2023-01-17 20:41:53) [INFO    ] Crow/1.0 server is running at http://0.0.0.0:18080 using 16 threads
> (2023-01-17 20:41:53) [INFO    ] Call `app.loglevel(crow::LogLevel::Warning)` to hide Info level logs.
> (2023-01-17 20:42:09) [INFO    ] Request: 127.0.0.1:59614 000001492F43A430 HTTP/1.1 GET /swagger/
> (2023-01-17 20:42:09) [INFO    ] Response: 000001492F43A430 /swagger/ 200 0
> (2023-01-17 20:42:09) [INFO    ] Request: 127.0.0.1:59614 000001492F43A430 HTTP/1.1 GET /swagger/swagger-ui.css
> (2023-01-17 20:42:09) [INFO    ] Response: 000001492F43A430 /swagger/swagger-ui.css 404 0
> (2023-01-17 20:42:09) [INFO    ] Request: 127.0.0.1:59614 000001492F43A430 HTTP/1.1 GET /swagger/static/swagger.css
> (2023-01-17 20:42:09) [INFO    ] Response: 000001492F43A430 /swagger/static/swagger.css 404 0

#### C++ Source
```cpp
#include <crow_all.h>

int main(int argc, char **argv) {
    crow::SimpleApp app;
    crow::Blueprint bp("swagger");
    app.register_blueprint(bp);
    CROW_BP_ROUTE(bp, "/")
    ([]() {
        auto page = crow::mustache::load("swagger.html");
        return page.render();
    });
    app.port(18080).multithreaded().run();
}
```
#### swagger.html
```html
<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
    <link rel="stylesheet" type="text/css" href="static/swagger-ui.css" />
    <link rel="stylesheet" type="text/css" href="static/swagger.css" />
    <link rel="icon" type="image/png" href="static/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="static/favicon-16x16.png" sizes="16x16" />
  </head>

  <body>
    <div id="swagger-ui"></div>
    <script src="static/swagger-ui-bundle.js" charset="UTF-8"> </script>
    <script src="static/swagger-ui-standalone-preset.js" charset="UTF-8"> </script>
    <script src="static/swagger-initializer.js" charset="UTF-8"> </script>
  </body>
</html>
```
### Software / System
* Windows 11 Pro 22H2 
* Crow v1.0+5 Security Patch (crow_all.h)
* MSVC 19.29.30146.0

**Comment by mrozigor** [comment]
Hello. First question - have you tried to run this on `master`? There are a few differences between latest release and master, so it should be a good start ;)

**Comment by xia-stan** [comment]
@mrozigor : I haven't tried master yet. I need to use `crow_all.h`, and didn't see one readily available in the directory structure. Is that file generated via CMake?

**Comment by xia-stan** [comment]
I found it in CMake. Trying to deal with the ASIO dependency. Is that necessary for building crow_all.h? Looks like it's only part of the link libraries.

**Comment by mrozigor** [comment]
You can use script from `scripts` dir -> `merge_all.py`. Example: `python3 scripts/merge_all.py include crow_all.h`

**Comment by xia-stan** [comment]
Just did that. Got Cmake working, but Windows doesn't like the wildcard expansion.

**Comment by mrozigor** [comment]
So you generated file properly, but another problem occurred?

**Comment by xia-stan** [comment]
Got `crow_all.h` built from HEAD, and I get an error with `asio.hpp` not being found. It just gets included. Does the header-only implementation work without asio? 

I already had to add the 37 boost dependencies as submodules. I can add asio to the list. What version of asio should I reference my submodule to?

**Comment by mrozigor** [comment]
You can use `Findasio.cmake` from `cmake` dir. Or just manually include/link latest version.

**Comment by xia-stan** [comment]
I know I don't have it installed globally, that's why CMake was balking. Looking at their website it turns out that asio is already included in boost. Crow already depends on the boost/asio header. I updated the namespaces to `boost::asio` and include paths, `boost/asio.hpp`. I'm now getting compilation errors. Here's a snippit of them: 
![image](https://user-images.githubusercontent.com/73365079/213578320-e81c210d-e421-48a4-a6b5-8cce42d6f55f.png)

I'll try the non-boost version of asio now. What's interesting is that some of the errors `detail::task_timer` doesn't seem to belong to either version of asio's namespace.

**Comment by xia-stan** [comment]
Here's the latest setup. I've 
* built the crow_all.h from [a92aee49b96826f40290086502428efc9b55d633](https://github.com/CrowCpp/Crow/commit/a92aee49b96826f40290086502428efc9b55d633),
* installed ASIO at [a71f5232d207b4f3bbd253eb1041e30b5e4ea606](https://github.com/chriskohlhoff/asio/commit/a71f5232d207b4f3bbd253eb1041e30b5e4ea606), and
* dropped all the boost headers from the build. 

I'm still seeing the same behavior as before. The Blueprint is prepending `swagger` to all the URLs before trying to serve them. This finds the HTML template properly, but fails to find the static files. I've kept the Static paths default:
![image](https://user-images.githubusercontent.com/73365079/215863196-bf4a2b4d-c006-4e54-98a8-b908927a7357.png)

Based on this information, I've tried putting the static files in 
* static/
* static/swagger/
* swagger/
* swagger/static/

They always return 404s. I've once again confirmed that the following code works (with templates and static files in the default directories): 
```c++

#include <crow_all.h>

int main(int argc, char **argv) {
    crow::SimpleApp app;
    CROW_ROUTE(app, "/")([]() { return "Hello world"; });
    CROW_ROUTE(app, "/swagger-ui") ([]() {
        auto page = crow::mustache::load("swagger.html");
        return page.render();
    });
    app.port(18080).multithreaded().run();
}
```

**Comment by mrozigor** [comment]
As I understand correctly HTML loads properly and static files not? Have you tried to change `src`/`href` attributes to `swagger/static/swagger-ui-bundle.js`? Or only `swagger-ui-bundle.js`?

**Comment by xia-stan** [comment]
That's correct. I've attempted changing the static paths to match but the blueprint prefix gets added to any route within the context. 
![image](https://user-images.githubusercontent.com/73365079/216018814-faa85b8e-622f-470a-924d-5cb33e613f5d.png)
----
I have managed to get this working, but I needed to explicitly define the static and template paths in the blueprint constructor. Here's the amended code: 
```c++
#include <crow_all.h>

int main(int argc, char **argv) {
    crow::SimpleApp app;
    CROW_ROUTE(app, "/")([]() { return "Hello world"; });
    CROW_ROUTE(app, "/swagger", "swagger/static", "swagger/templates") ([]() {
        auto page = crow::mustache::load("swagger.html");
        return page.render();
    });
    app.port(18080).multithreaded().run();
}
```
Then defining the src refs to `static/swagger-ui-bundle.js` work as expected. With the pathing on disk looking like
* swagger/
   * static
       * swagger-ui-bundle.js
   * templates
       * swagger.html

----
I'm trying to organize my blueprints. I've moved the blueprint definition to a separate function, and return that blueprint to main. I've kept the pathing identical. Again, it finds the HTML without issue but issues 404s for all of the static elements. 
![image](https://user-images.githubusercontent.com/73365079/216026224-089ae17b-9423-4114-8f82-daadea73b072.png)
This seems like it should be doing the same thing as before. I'm wondering if there's some sort of scoping going on in the lambda or class that's causing it to lose context for the static assets?

```c++
#include <crow_all.h>

crow::Blueprint swagger_bp() {
    crow::Blueprint bp("swagger", "swagger/static", "swagger/templates");
    CROW_BP_ROUTE(bp, "/")
    ([]() {
        auto page = crow::mustache::load("swagger.html");
        return page.render();
    });
    return bp;
}

int main(int argc, char **argv) {
    crow::SimpleApp app;
    CROW_ROUTE(app, "/")([]() { return "Hello world"; });
    auto bp = swagger_bp();
    app.register_blueprint(bp);
    app.port(18080).multithreaded().run();
}
```

**Comment by mrozigor** [comment]
I haven't implemented blueprints, so I'd have to check in code. Maybe @The-EDev could help here?

**Comment by xia-stan** [comment]
Inspecting the previous example with the returned Blueprint object shows that we're missing the static or template paths. 
![image](https://user-images.githubusercontent.com/73365079/216041218-9d5c7577-a6aa-43dc-8a1e-85901e79d732.png)
I tracked this down to the implemented assignment operator: 
![image](https://user-images.githubusercontent.com/73365079/216043138-58d89f38-9955-4cec-9bdd-483df3a92155.png)
As you can see, it's missing the assignments for the prefix and template. Adding those fixes this specific issue. Adding the `blueprints_` and `mw_indices_` variables removes a bad allocation error that happens when passing the SimpleApp object to the function and doing the assignment there.
This also explains an issue I was seeing when returning nested blueprints from functions (i.e. segfaults when registering children). The assignments were never happening properly. 

### The proposed fix
![image](https://user-images.githubusercontent.com/73365079/216047749-82e4e9ab-5828-4350-8285-855cad53ba98.png)

If this fix looks good, I'll be happy to put in a PR to fix it.

**Comment by mrozigor** [comment]
Great job! I would be great if you prepare PR ;) Thanks.

**Comment by julianxhokaxhiu** [comment]
Sorry to hijack this issue but I have a question related to Crow and Swagger: may I ask how did you implement/integrate the OpenAPI spec with Crow? is there some kind of automatic provider or has to be done by hand? If you could post a simple tutorial I'd appreciate. Thank you in advance!

**Comment by drizzle042** [comment]
Hi @xia-stan I know this might be unrelated but I gotta say thank you for this. Your code you shared here contains more info about blueprints than the web docs. I could get up and running easily with it. Again thank you.

**Comment by xia-stan** [comment]
As a note for those who might come later. It's more efficient to create the blueprint in main, and then pass by reference to the generator. This will reduce the number of copies being made. 

```c++
#include <crow_all.h>

void swagger_blueprint(crow::Blueprint& bp) {
    CROW_BP_ROUTE(bp, "/")
    ([]() {
        auto page = crow::mustache::load("swagger.html");
        return page.render();
    });
}

int main(int argc, char** argv) {
    crow::SimpleApp app;
    CROW_ROUTE(app, "/")([]() { return "Hello world"; });
    crow::Blueprint swag_bp("swagger", "swagger/static", "swagger/templates");
    swagger_blueprint(swag_bp);
    app.register_blueprint(swag_bp);
    app.port(18080).multithreaded().run();
}
```
