### ISSUE TITLE
Render true and false tags in mustache templates

### ISSUE THREAD

**Issue by queenstdev** [CrowCpp/Crow#587]
Render a template with a boolean value e.g.:
```
auto t = crow::mustache::compile(R"---({{true_value}} and {{false_value}})---");
crow::mustache::context ctx;
ctx["true_value"] = true;
ctx["false_value"] = false;
auto result = t.render_string(ctx);
CHECK("true and false" == result);
```
results in a `std::runtime_error "not implemented tag type..."`

The expected boolean rendering can be seen in the Mustache [demo page](https://mustache.github.io/#demo)

**Comment by mrozigor** [comment]
On the demo page booleans are used with conditional (?) `{{#TAG}}` tag, not with displaying one `{{TAG}}`.

**Comment by queenstdev** [comment]
@mrozigor, you are correct. The default template doesn't have a `{{tag}}` that is a boolean value.
What I meant to say was that if you use the demo page to render a boolean tag e.g. `{{empty}}`, it will render `false`.
