### ISSUE TITLE
curl https://localhost:18080 : SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by bigtang5** [CrowCpp/Crow#589]
curl https://localhost:18080
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:18080

curl http://localhost:18080
Hello world

my work:
OS: centos 8.5    
need asio
yum install -y epel-release    OK!
yum install -y asio-devel       Failed

download asio 1.24 here:  https://think-async.com/Asio/Download.html

g++ crow1.cpp -lpthread -o a2.out -DCROW_ENABLE_COMPRESSION -lz -DCROW_ENABLE_SSL -lssl
/usr/bin/ld: /tmp/cce3a8fN.o: undefined reference to symbol 'BIO_ctrl_pending@@OPENSSL_1_1_0'
//usr/lib64/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

g++ crow1.cpp -lpthread -o a2.out -DCROW_ENABLE_COMPRESSION -lz -DCROW_ENABLE_SSL -lssl -lcrypto
OK!

now run  a2.out:
./a2.out

use curl to test, get the result:
curl https://localhost:18080
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:18080

curl http://localhost:18080
Hello world

Anybody can help?
thanks,
bigtang5

**Comment by kiner-shah** [comment]
What is your curl version?

**Comment by gittiver** [comment]
It seems crow1.cpp does not contain:
  app.port(18080).ssl_file("test.crt", "test.key").run();
  
  instead maybe:
    app.port(18080).run();
    
  This would produce exactly the described behavior.
