### ISSUE TITLE
Can anyone give a complete example of uploading files with Crow?

### ISSUE THREAD

**Issue by bigtang5** [CrowCpp/Crow#591]
Uploading is a difficult point, but uploading  file does not have an example.  why is that?

**Comment by bigtang5** [comment]
attach more: how to use the crow::multipart::header object? how to get the filename uploaded? if the file is huge,  how to upload Sectionally or discontinuously？

**Comment by kiner-shah** [comment]
Yeah, I feel adding an example for uploading files can help many people.

**Comment by drizzle042** [comment]
Will this still work though if the file will not be output in .txt?

**Comment by kiner-shah** [comment]
@drizzle042, I have a more comprehensive example, which may help answer your question:

    CROW_ROUTE(app, "/uploadfile")
       .methods(crow::HTTPMethod::Post)
    ([](const crow::request& req)
    {
        for (auto [headerKey, headerValue] : req.headers)
            std::cout << headerKey << ' ' << headerValue << '\n';
        // std::cout << req.body << '\n';

        crow::multipart::message file_message(req);
        for (auto [part_name, part_value] : file_message.part_map)
        {
            std::cout << "Part: " << part_name;
            if ("InputFile" == part_name)
            {
                // Get file name
                std::string uploaded_file_name = part_value.headers.find("Content-Disposition")->second.params["filename"];
                
                std::ofstream out_file(uploaded_file_name);
                if (!out_file)
                {
                     std::cout << " Write to file failed\n";
                     continue;
                }
                out_file << part_value.body;
                out_file.close();
                std::cout << " Contents written to " << uploaded_file_name << '\n';
            }
            else
            {
                std::cout << " Value: " << part_value.body << '\n';
            }
        }
        return crow::response(200);
    });

**Comment by drizzle042** [comment]
Thanks a lot @kiner-shah 
I’ve been looking for something like this.
I’ll tweak it a little more optimization. I’ll share my code later.
Again, thanks.

**Comment by The-EDev** [comment]
@kiner-shah @drizzle042 it would be great if you could create a PR with this example added!

**Comment by kiner-shah** [comment]
@The-EDev I have raised a PR. Can you please review it?
