### ISSUE TITLE
How to implement a global exception handler with CrowCpp?

### ISSUE THREAD

**Issue by whaliendev** [CrowCpp/Crow#594]
I'm using crowcpp to build a service, but I cannot implement a global exception handler easily like flask and express, or even spring boot. 
In expressjs, the error  uncaught is automatically passed to the following middlewares. Nevertheless, there is no function overloading has the third arguments `next`, so it's almost impossible to implement such a exception handler.
In flask, we can register exception handler to main `app` with decorators or the `register_error_handler` api, but crowcpp doesn't provide a similar api. 
So is there a workaround to implement such a global exception handler?

**Comment by whaliendev** [comment]
After studying the source code for a while, it seems to me that it's hard to implement global exception handling with Crow at this stage in a straightforward manner. In case some of you having the same need as mine, here is a class template I  implemented to achieve fine-grained exception handling. Hope it helps. 😀

```cpp
template <typename Func, typename Response = crow::response>
class ExceptionHandlerAspect {
 private:
  Func func_;
  Response& res_;

 public:
  ExceptionHandlerAspect(Func f, Response& res) : func_(f), res_(res) {}

  template <typename... Args>
  auto operator()(Args&&... args) -> decltype(func_(args...)) {
    static_assert(
        std::is_default_constructible<decltype(func_(args...))>::value,
        "the call result's type of function passed in must be default "
        "constructible");
    decltype(func_(args...)) res;
    try {
      res = func_(args...);
    } catch (const AppBaseException& ex) {
      ex.handle(res_);
    } catch (const std::exception& ex) {
      // some handling logic
    }
    return res;
  }
};
```

**Comment by cschreib** [comment]
I opened a PR to attempt to add this feature; could you confirm if this does what you need?

**Comment by whaliendev** [comment]
> I opened a PR to attempt to add this feature; could you confirm if this does what you need?

Yes, it's exactly what I need.
