### ISSUE TITLE
Example: Implementing Crow with Swagger UI

### ISSUE THREAD

**Issue by xia-stan** [CrowCpp/Crow#603]
To keep #585 's message thread clean, I wanted to make this comment to address the question posed about implementing Crow and Swagger UI. The implementation is pretty straight forward. For a long answer, I've made [an example repository for reference](https://github.com/xia-stan/swaggy-crows/tree/master). 

For the quick and dirty answer, define and register a blueprint

```c++
crow::Blueprint swag("swagger", "docs/swagger/static", "docs/swagger/templates");
CROW_BP_ROUTE(swag, "/")
  ([]() {
    auto page = crow::mustache::load("swagger.html");
    return page.render();
});
```
Then point `swagger-initializer.js` to your OpenAPI yaml file and update Swagger UI's index.html to use the blueprinted paths. Finally, execute your program from the same directory as your blueprint base path definition.

**Comment by xia-stan** [comment]
@julianxhokaxhiu : Here's the answer to the question you posed on #585 .

**Comment by julianxhokaxhiu** [comment]
@xia-stan I have one question on top of your project. I've seen the whole structure and that's super clear to me. The only part I'm missing is how the Swagger template will pick my endpoints, will I have to declare them manually somewhere or are they going to be auto discovered? Also how is documentation of this API endpoints ( and parameters ) are supposed to work? Do I have to type that manually? Thank you in advance.

**Comment by xia-stan** [comment]
That's correct. Crow (v1.0+5) doesn't automatically generate the OpenAPI specification file. You have to generate that yourself.

**Comment by julianxhokaxhiu** [comment]
Thank you @xia-stan I'll see what I can make out of this. Appreciated :)
