### ISSUE TITLE
Example code for serving image from memory buffer

### ISSUE THREAD

**Issue by hrshovon** [CrowCpp/Crow#605]
Hello,
Say for example, I have an image in a memory buffer. It could be from a webcam or video stream being read using opencv. How can I show that stream on a webpage like for example, mjpg streamer? I searched for some example codes but unfortunately found none.

**Comment by kiner-shah** [comment]
You want to stream data, I doubt a HTTP server like Crow can help here. There must be some other protocol which is better suited for streaming, but I am not sure.

**Comment by hrshovon** [comment]
Actually I just want to show webcam stream on a webpage. A flask equivalent would be something like this 
```
from flask import Flask, render_template, Response
import cv2

app = Flask(__name__)

camera = cv2.VideoCapture('rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen03.stream')  # use 0 for web camera
#  for cctv camera use rtsp://username:password@ip_address:554/user=username_password='password'_channel=channel_number_stream=0.sdp' instead of camera
# for local webcam use cv2.VideoCapture(0)

def gen_frames():  # generate frame by frame from camera
    while True:
        # Capture frame-by-frame
        success, frame = camera.read()  # read the camera frame
        if not success:
            break
        else:
            ret, buffer = cv2.imencode('.jpg', frame)
            frame = buffer.tobytes()
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')  # concat frame one by one and show result


@app.route('/video_feed')
def video_feed():
    #Video streaming route. Put this in the src attribute of an img tag
    return Response(gen_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')


@app.route('/')
def index():
    """Video streaming home page."""
    return render_template('index.html')


if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by kiner-shah** [comment]
You can do it like this:

    CROW_ROUTE(app, "/videofeed")
        .methods(crow::HTTPMethod::Get)
    ([](const crow::request& req)
    {
        crow::response response;
        std::ifstream in_file("sample.jpg");
        std::ostringstream oss;
        oss << in_file.rdbuf();
        in_file.close();
        response.body = oss.str();
        // std::cout << response.body << '\n';
        return response;
    });

Instead of reading from a file, you may convert `cv::Mat` to a byte array (`std::vector` of `unsigned char`) and use that to set `response.body`.

**Comment by The-EDev** [comment]
@hrshovon I'm assuming @kiner-shah's answer is adequate, if it is not please let me know so I reopen the issue.
