### ISSUE TITLE
An uncaught exception occurred: bad function call (local middleware)

### ISSUE THREAD

**Issue by mez0ru** [CrowCpp/Crow#608]
Using a local middleware as in the examples, I get this error when the middleware ran successfully. It never reaches the actual route and instead throws the exception as in the title.

I wanted to use visual studio debugger, but I don't know how to turn off the try cache inside crow. I think it would be better if it's turned off automatically if the project is in debug mode for better error tracing.

Using normal routes work, even using the cookie parser is working. The problem is using a local middleware.
if I made the middleware global, it works. But not local middlewares, even though I used crow::ILocalMiddleware in the middleware class.

To be honest, I was using the vcpkg version, however, I needed the new functionalities in the master version, so I cloned it and built it, linked all the built libraries, includes, etc. So maybe it's something related with my setup. However, everything literally works. So I don't know if it's actually my build, or the library.

**Comment by antoine-lombardo** [comment]
Same issue here, how did you solved it?

**Comment by mez0ru** [comment]
I did not solve it, I migrated to restinio, which works great but a bit harder to use. They have a lot of examples too, so you can learn it quickly. But so far no regrets, I'm enjoying it now.
