### ISSUE TITLE
"Late" registration of routes (after server start)

### ISSUE THREAD

**Issue by fmg-andrewlaws** [CrowCpp/Crow#610]
Howdy! 

Is it possible to register routes after calling `run_aync()`?

I can't see anything that specifically prohibits it in the documentation, and the code all compiles just fine.

However, 90% of the time when I run the produced executable it winds up crashing when the "late" route registrations occur. On the occasions it _does_ run, the endpoints registered after `run_aync()` is called result in `404` responses (as if they have not been registered).

Interestingly, when I modify the `helloworld` example to do late endpoint registry, I don't get the crashing behaviour, only the `404` responses, which suggests that there may be some additional factor in my code.

In case it's of use for context, the use case here is a REST service that allows the instantiation of objects which can then register their own route handlers. This means that at the point of the server starting, I can't know what route endpoints and handlers might need to be (or not be) registered.

Also, I'm using the `route_dynamic()` calls rather than the `CROW_ROUTE` macro as I need runtime evaluation for the late registered URLs. I'm aware that this usage is not recommended, as per the docs, but I can't see any other way to register URLs constructed at runtime, and I've never had any issues using it apart from in this late registration context.

That said, using the macros for late registration doesn't work either, so probably the underlying cause is the same.

Thanks for your time!

**Comment by The-EDev** [comment]
The way Crow's router currently works wouldn't allow for adding or modifying routes after the app starts. adding a route would require the route trie to be recreated and reoptimized, which could be quite a heavy operation if it was to be implemented.

**Comment by fmg-andrewlaws** [comment]
Understood - cheers!
