### ISSUE TITLE
Q: Do we have http client included?

### ISSUE THREAD

**Issue by overthetop** [CrowCpp/Crow#613]
I would like to make a http request to another rest service from my crow app. How can I do that?

**Comment by mrozigor** [comment]
There is no client API in crow.

**Comment by Leon0402** [comment]
You can use https://github.com/libcpr/cpr for instance.

**Comment by kiner-shah** [comment]
This question is very similar to #596. 

You can also use Postman for that if you don't want to spend time coding a client.

**Comment by drizzle042** [comment]
@overthetop you probably should close this then.
