### ISSUE TITLE
Change Request Body in middleware

### ISSUE THREAD

**Issue by ahertlcode** [CrowCpp/Crow#627]
```cpp
crow::json::wvalue reqBody(req.body);
reqBody["email"] = val_verify.payload["email"];
reqBody["id"] = val_verify.payload["id"];
reqBody["name"] = val_verify.payload["name"];
req.body = reqBody;
```

I wrote the above code trying to add values into the request object within myb validation middleware but it is not working, How would you advice this should be done with CROW. Thank you.

**Comment by mrozigor** [comment]
What exactly is not working? Some errors during compilation or incorrect behavior in runtime?

**Comment by ahertlcode** [comment]
I am trying to add values into the request object within the middleware. I
wasn't able to get that to work. the code shared compiled but at run time
the route handler could find the data am attempting to add into the request
object from the middleware.

**Comment by junekhan** [comment]
Can you tell us what Crow version you are working on as well as a minimal runnable example?

I wrote a test case and couldn't reproduce this issue. And I also notice that `req.body` is actually `std::string` typed, so `req.body = reqBody;` in your code doesn't compile in the first place.

Test case:
```
struct SimpleRequestModiferMiddleware
{
    struct context
    {};

    void before_handle(request& req, response& /*res*/, context& /*ctx*/) {
        crow::json::wvalue reqBody(req.body);
        reqBody["email"] = "email";
        reqBody["id"] = "id";
        reqBody["name"] = "name";
        req.body = reqBody.dump();
    }

    void after_handle(request& req, response& /*res*/, context& /*ctx*/) {
          CROW_LOG_INFO << "Modified body: " << req.body;
    }
};

TEST_CASE("middleware_request_modifier")
{
    static char buf[2048];
    App<SimpleRequestModiferMiddleware> app;
    CROW_ROUTE(app, "/").methods("POST"_method)
    ([&](const crow::request&) {
        return "";
    });

    auto _ = app.bindaddr(LOCALHOST_ADDRESS).port(45451).run_async();
    app.wait_for_server_start();
    std::string sendmsg =
      "POST / HTTP/1.0\r\nContent-Length:3\r\nX-HeaderTest: 123\r\n\r\nA=B\r\n";
    {
        asio::io_service is;
        asio::ip::tcp::socket c(is);
        c.connect(asio::ip::tcp::endpoint(
          asio::ip::address::from_string(LOCALHOST_ADDRESS), 45451));

        c.send(asio::buffer(sendmsg));

        size_t recved = c.receive(asio::buffer(buf, 2048));
    }
    app.stop();
}

```

**Comment by ahertlcode** [comment]
Oh Thanks, this has been long ago, I have got this to work using
json/json.h from opensource jsoncpp project. Thank you.

**Comment by gittiver** [comment]
OK, seems to be solved.
