### ISSUE TITLE
Build from source with boost/asio

### ISSUE THREAD

**Issue by akjt** [CrowCpp/Crow#628]
There seems to be a problem when building the Crow from source and using asio from boost:

For example:

cmake -DASIO_INCLUDE_DIR=/usr/include/boost/asio .. 

will fail by 

Crow/include/crow/socket_adaptors.h:5:10: fatal error: asio.hpp: No such file or directory
    5 | #include <asio.hpp>

The reason being that the include should be boost/asio.hpp. Anyway to fix it?

**Comment by The-EDev** [comment]
The `master` branch uses Standalone ASIO as opposed to Boost/ASIO. There is already [an open issue for supporting both](#490), but that's yet to be implemented.
