### ISSUE TITLE
Single threaded application

### ISSUE THREAD

**Issue by janetatomas1** [CrowCpp/Crow#629]
Hi, I have a question.

Is it possible to run Crow server using only one thread ?

When I run 
```
    app.port(8000).concurrency(1).run();
```
it uses two threads anyway.

Thanks.

**Comment by mrozigor** [comment]
2 is the minimum numbers of thread. You would have to change behavior in code (`app.h:206`).

**Comment by janetatomas1** [comment]
Thanks.
