### ISSUE TITLE
Handlers with a static signature

### ISSUE THREAD

**Issue by floli** [CrowCpp/Crow#630]
Hello,

I am trying to hide away the crow interface. For that I need to receive the handler functions from user code, together with the path specification and save it. The dynamic signature (depending on the arguments in the path) makes it hard to work (e.g. save in a vector) with the handler functions.

Is it possible to use handler functions that have the same signature for all routes? The arguments would e.g. be extracted from the crow::request object.

Do you know any other approach to save a list of handler functions and pass them to crow?

Best Thanks!

**Comment by The-EDev** [comment]
if you want to use the same endpoint (url) for all routes, you could just have a single route handler and have that call whatever function you need based on request data.

Please let me know if that answered your question or if you need more help.
