### ISSUE TITLE
timeout not action

### ISSUE THREAD

**Issue by phsang198** [CrowCpp/Crow#649]
i have defined : 
crow::App<crow::CORSHandler,SecurityMiddleware> app;
app.get_middleware<SecurityMiddleware>().setTokenManager();
	app.server_name("Token");
	app.port(servicePort)
		.timeout(1)
		.multithreaded()
		.run();
		
when i send a request from client , processing time for request is 10 seconds . with my logic , when processing time > 1s , server return "request fail" , but after 10s , i have respone "resquest successsfully " . 
Do not timeout action ? 
i'm look forward to get replying from everyone ! 
thanks you !!!

**Comment by The-EDev** [comment]
What is your logic exactly, and what is your client sending?

**Comment by phsang198** [comment]
my  exact logic is " server returning "request fail" when processing time > 1s ", but it not  . AND my client send a simple http get request , but it's not a problem , problem is timeout of crow "app.timeout(1)"

**Comment by The-EDev** [comment]
well, if i remember correctly, the timeout function is intended to cut the connection if the client is too slow to respond, and is usually not applied when it's the server processing data.

**Comment by The-EDev** [comment]
to confirm this, you can try using a `while(true)` in your handler and see if it disconnects after the timeout is triggered

**Comment by phsang198** [comment]
> to confirm this, you can try using a `while(true)` in your handler and see if it disconnects after the timeout is triggered

i try it , but it not . After timeout is triggered , while loop is still not break

**Comment by phsang198** [comment]
my application will wait after 2s . i have set timeout for it , after 2s , it close connection . But , on sever , request still keep on being processed
