### ISSUE TITLE
How to cancel requests if they are timeout ? 

### ISSUE THREAD

**Issue by phsang198** [CrowCpp/Crow#650]
hello everyone , 
i have issue :  client send 1000 requests to server and server takes us to 12 threads.  but processing time > timeout , how to cancel some long waiting requests ? 
can you help me ? 
thanks you !

**Comment by kiner-shah** [comment]
What kind of client is it? If it's a web app with JS running, you can look online for how to abort/cancel requests online. Example, see [this](https://www.wisdomgeek.com/development/web-development/javascript/how-to-cancel-http-fetch-request/).
