### ISSUE TITLE
Can Crow be used for production environments?

### ISSUE THREAD

**Issue by MarkupMaster** [CrowCpp/Crow#653]
If Crow supports HTTPS sockets with OpenSSL, can Crow and OpenSSL be used for a production environment altogether? In other words, how do I host C++ on the web for backend processing directly with Crow and OpenSSL?

**Comment by The-EDev** [comment]
you could use Crow with OpenSSL in production, although it is considered best practice to set Crow up in HTTP mode behind a reverse-proxy like Apache or Nginx and have the latter handle SSL.

Please let me know if your question wasn't answered.
