### ISSUE TITLE
Allow extensible returning in handlers

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/crow#66]
we have JSON mode, basically sets the content-type header to application/json, just make the same thing for multipart, instead of converting to string and returning that, something like:
``` cpp
    CROW_ROUTE(app,"/multipart")
    ([](const crow::request& req){
        crow::multipart::message msg(req);
        return msg;
    });
```

**Comment by The-EDev** [comment]
One solution for this issue + support for all other types would be to introduce a `returnable` class containing primarily a `dump()` and `set_mode(crow::response res)` methods, the `dump()` method would simply put the class' content into the response body, and the `set_mode(crow::response res)` would set the headers (specifically `content-type`) to the appropriate ones, then any user/developer can create a wrapper for any library they might want to return directly.

**Comment by The-EDev** [comment]
so I was trying out yesterday's solution. it caused a circular dependency which I should've anticipated..

So I changed the method to just a content type variable, which for some reason didn't work. So I changed it to a method that returned the content type, which worked, here's the code.

```cpp
struct returnable
{
    virtual const std::string dump() = 0;
    virtual const std::string content_type() = 0;
};
```
Implementation for `content_type()` in `multipart::message`:
`const std::string content_type() override {return "multiplart/form-data";}`

The child class would add an implementation to these, allowing it to be returned from a handler.
What I'm not sure of is if there's a better way to go about doing this.

**Comment by The-EDev** [comment]
@mrozigor as I'm not as familiar with C++ as I would like to be, what do you think of this approach?, does it make sense? is there a better way to go about it?

**Comment by mrozigor** [comment]
This looks good - I think it is good to explicitly 'mark' class as returnable.

**Comment by NobodyXu** [comment]
@The-EDev IMHO it is better to use `class` for virtual base class and use `struct` for c-like aggregate.

**Comment by The-EDev** [comment]
Well I'm mainly following the existing code, as far as I understand, the main difference between `struct` and `class` is that one is public by default and the other is private

**Comment by NobodyXu** [comment]
But to new contributers, this code at the first glance look like a C-like structure (aggregate), not a virtual base class since there isn't a constructor or destructor.

Personally I think it is better to use `class` so that the reader immediately knows that this isn't a C-like structure.
