### ISSUE TITLE
Crow web app is crashing

### ISSUE THREAD

**Issue by salah2022-dvg** [CrowCpp/Crow#660]
I have created REST API to handle user web interface requests but it seems like the crow application is suddenly crashing , throwing error "Too many open files: iostream", so i want to make i'm missing something here or it is a hardware issues

**Comment by The-EDev** [comment]
what is your API doing in relation to files?

**Comment by salah2022-dvg** [comment]
Mostly its MySQL connections

**Comment by The-EDev** [comment]
Hmmm, are you serving any static files?

I'm trying to figure out how to reproduce your issue. It could be related to Crow's static file system, but I need some information in order to know what to test.

**Comment by salah2022-dvg** [comment]
@The-EDev   sorry for my lack of information, no i'm using only dynamic shared files

**Comment by gittiver** [comment]
could you check with ulimit -n how many open file descriptors are allowed?

**Comment by salah2022-dvg** [comment]
@gittiver  i have limit=1024 files, even with one connected user to the app it reaches the limit, knowing that the homepage is using ajax refresh

**Comment by gittiver** [comment]
hmm, what opens so many files and leave them open? does lsof gives you some hints?
