### ISSUE TITLE
_CROW_ICD-NOTFOUND

### ISSUE THREAD

**Issue by Rxann** [CrowCpp/Crow#661]
At the top of my visual studio cmake project, this is present. the error is `C++ command-line error: invalid macro definition: _CROW_ICD-NOTFOUND`. Any help would be appreciated.

**Comment by gittiver** [comment]
I found this in build directory, CrowConfig.cmake:  
get_target_property(_CROW_ICD Crow::Crow INTERFACE_COMPILE_DEFINITIONS)

its produced by cmake/CrowConfig.cmake.in 

How did you build your Visual Studio Project, using cmake? 
It would be interesting to see the results of the cmake configure step (cmake -B ...).

**Comment by SpriteOvO** [comment]
Same problem. Using Crow from vcpkg on Windows with MSVC.

1. ```bash
   vcpkg install crow:x64-windows-static
   ```

2. `CMakeLists.txt`
   ```cmake
   find_package(Crow CONFIG REQUIRED)
   target_link_libraries(my-target PRIVATE Crow::Crow)
   ```

4. ```bash
   cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=path/to/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
   cmake --build build --config RelWithDebInfo
   ```

5. See error `command line : warning C5102: ignoring invalid command-line macro definition '_CROW_ICD-NOTFOUND'`

**Comment by SpriteOvO** [comment]
Workaround

```cmake
# Workaround https://github.com/CrowCpp/Crow/issues/661
list(REMOVE_ITEM _CROW_ICD "_CROW_ICD-NOTFOUND")
set_target_properties(Crow::Crow PROPERTIES INTERFACE_COMPILE_DEFINITIONS "${_CROW_ICD}")
```
