### ISSUE TITLE
Log conflict issue between spdlog and crow

### ISSUE THREAD

**Issue by AstroAir** [CrowCpp/Crow#663]
When I try to add an spdlog as a log in the crow server, a large number of errors will appear every time I compile. Even the Header file containing only the spdlog will cause errors. When I delete them, all errors disappear.I don't know how to solve this problem. I hope someone can help me. Thanks!

**Comment by The-EDev** [comment]
what errors are you seeing?

**Comment by MichaelSB** [comment]
FWIW, I use spdlog as custom LogHandler for a crow-App and don't have any issues with it.

**Comment by AstroAir** [comment]
It seems that the problem is not caused by spdlog.I downloaded the latest version of crow (master),and built in msys2.But some errors happened:
[error.txt](https://github.com/CrowCpp/Crow/files/12002522/error.txt)
