### ISSUE TITLE
Asio-related question about Crow/include/crow directory

### ISSUE THREAD

**Issue by MarkupMaster** [CrowCpp/Crow#664]
I have directly installed Crow's master branch from the Windows Command Prompt with a `git clone` command. As it turns out, some of the files inside the **Crow/include/crow/** directory include the asio development headers as a prerequisite, which are mentioned directly in [this page](https://crowcpp.org/master/getting_started/setup/linux/). So, I was wondering, what are the steps to extracting and copy-and-pasting the asio header files into the Crow folder? And also, what if the **Crow/include/crow/** directory was modified to have a Boost asio folder within it? Could you do that so the directory cloning process could be simplified?

**Comment by The-EDev** [comment]
It would be easier to just add ASIO's folder to your compiler's include directories. I'm not sure how to do that for MSVC but for GCC it's something like `g++ myfile.cpp -lpthread -I/path/to/asio`

**Comment by gittiver** [comment]
We could add the asio lib also by cmake, then we could also more easily set it to ASIO_STANDALONE which is not on all platforms the case.
