### ISSUE TITLE
The files in the Crow/include/crow/ directory have include errors that appear when running with G++

### ISSUE THREAD

**Issue by MarkupMaster** [CrowCpp/Crow#665]
I copied the whole Crow repo folder to my project's root folder. I tried to run my .cpp file with G++, which had the following include code:

- `#define CROW_MAIN`, associated with #300 
- `#include <iostream>`, for standard input/outputs
- `#include <fstream>`
- `#include <string>`
- `#include "Crow/include/crow.h"`
- `#include "Crow/include/crow/app.h"`
- `#include "Crow/include/crow/compression.h"`
- And there were a lot more files in the Crow directory, but somehow in the `http_parser_merged.h` file, the `common.h` file was referenced as `crow/common.h`, when the `http_parser_merged.h` file was already inside the `Crow/include/crow` folder. 

- (This had happened with a lot more files in the `Crow/include/crow` directory; the `http_parser_merged.h` file was just an example.)

- Here are the logs:

`g++ -o searchFunction searchfunction.cpp`

`In file included from Crow/include/crow.h:3:0,
                 from searchfunction.cpp:5:   
Crow/include/crow/http_parser_merged.h:40:25: fatal error: crow/common.h: No such file or directory
 #include "crow/common.h"
                         ^
compilation terminated.`

**Does anyone know how to solve this?**

**Comment by gittiver** [comment]
It obviously misses include path and DEFINES. 
These are set when following https://crowcpp.org/master/getting_started/setup/linux/
(Look Section "Install from Source" or "Manually")
