### ISSUE TITLE
Error to compress http response payload in Slackware Current

### ISSUE THREAD

**Issue by esdrasdemorais** [CrowCpp/Crow#667]
After the command:

g++ main.cpp -DCROW_ENABLE_COMPRESSION 

I receive the same error in both algorithms as Deflate as Gzip:

/usr/bin/ld: /tmp/cc0YTjcj.o: in function crow::compression::compress_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, crow::compression::algorithm)': main.cpp:(.text._ZN4crow11compression15compress_stringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_9algorithmE[_ZN4crow11compression15compress_stringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_9algorithmE]+0x76): undefined reference to deflateInit2_'
/usr/bin/ld: main.cpp:(.text._ZN4crow11compression15compress_stringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_9algorithmE[_ZN4crow11compression15compress_stringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_9algorithmE]+0xdf): undefined reference to deflate' /usr/bin/ld: main.cpp:(.text._ZN4crow11compression15compress_stringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_9algorithmE[_ZN4crow11compression15compress_stringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_9algorithmE]+0x153): undefined reference to deflateEnd'
collect2: error: ld returned 1 exit status

I'm using the library CrowCpp/Crow, to be more specific: I'm using crow.compress internal library from CrowCpp/Crow.

**Comment by kiner-shah** [comment]
1. Do you have `libz.so` (Zlib) installed on your system? If not, you may install it using apt package manager `sudo apt install zlib1g-dev`.
2. Have you linked `libz.so`? If not, you should link it something like `g++ -lz -o program.o program.cpp`

**Comment by esdrasdemorais** [comment]
I don't use Debian Based Distributions, but I will try install zlib1g-dev, thanks for feedback.

**Comment by esdrasdemorais** [comment]
I don't use Debian Based Distributions, but I will try install zlib1g-dev, thanks for feedback.

**Comment by gittiver** [comment]
try 
g++ main.cpp -DCROW_ENABLE_COMPRESSION -lz 

this will link also against zlib. If zlib not available on system, it has to be installed or compiled locally.
