### ISSUE TITLE
Enabling SSL leaves http code without any actual use

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#67]
To put it simply, if you want Crow to run SSL (I mean OpenSSL, which includes TLS), you have to enable it using the flag CROW_ENABLE_SSL, which means that a program can either be compiled as SSL or not. Yet when compiling for SSL, Crow retains almost all the non SSL functionality (I'm saying almost because i'm not 100% sure it retains all the classes and methods). All these classes go unused since now all the routes are defined for HTTPS rather than HTTP. This creates 2 main consequences:

1. Crow can still use HTTP when compiled for SSL
2. Crow does not use HTTP

This is a problem primarily because a large portion of the code is just going unused. Either all non SSL classes should be removed if SSL is enabled, or Crow should automatically redirect HTTP requests to HTTPS.

~Thinking about this, it might be possible to have a non SSL crow app only to redirect to the SSL version, although testing is needed to confirm or deny this.~

**Comment by The-EDev** [comment]
Update: The last part doesn't actually work... the solution is to either make it work, or one of the earlier 2 solutions

**Comment by The-EDev** [comment]
Ok so it seems the only difference between http and https (at least in how crow sees it), is whether the client is asking for an ssl socket or a typical socket (I'm not 100% sure on this, I just didn't find any code processing the protocol section of the URL), so the difference is primarily client sided, for all crow cares, you could probably write "thingy://" and it would still work.

 This means that in order to get HTTP and HTTPS working simultaneously all you need is to enable both adaptor types at the same time. Problem is, crow is hard coded NOT to have such functionality, the router, connection, server, app, they all take ONE type of adaptor and are designed around such.

adding redirect support to crow is possible, but it is definitely a rabbit hole that requires a LOT of changes

**Comment by jjmcwill** [comment]
Came here while investigating alternatives to cpprestsdk, which we just learned has deadlock issues when the # of simultaneous clients is > the number of worker threads.  

What if I don't need both HTTP and HTTPS simultaneously?  What if I want either HTTP or HTTPS, depending on how <customer> has configured the product?  Is that possible?

**Comment by The-EDev** [comment]
you can have either HTTP or HTTPS at a time in one Crow application, or both (on separate ports) using 2 executables, you just can't have HTTP and HTTPS in the same Crow executable (as long as this issue is open at least).
