### ISSUE TITLE
how to point CROW_ROUTE to a domain?

### ISSUE THREAD

**Issue by AlexeyRoza** [CrowCpp/Crow#673]
hello
how I can use not just IP (.bindaddr()) but a fully qualified domain?
(or maybe even many domains??)
Or I should use Nginx as proxy-server ?

also I din't saw any mention about DataBases in /guides/
I do need any driver or any other support from Crow ?

Authentication/Authorization MiddleWare - in development?

**Comment by gittiver** [comment]
I would propose to use nginx or apache as proxy server.
Databases are not included in Crow yet, so you are on your own.
Authentication/Authorisation Middleware - nothing known. Actually just Session middleware example there:https://github.com/CrowCpp/Crow/blob/master/examples/middlewares/example_session.cpp

**Comment by AlexeyRoza** [comment]
okay that's sad
how about "get off the terminal" when daemon starts?
I do really need to launch through nohup & ?

**Comment by gittiver** [comment]
I am not sure what you want here. As it is a different problem could you use a separate issue for it?
