### ISSUE TITLE
Is MASTER stable enough?

### ISSUE THREAD

**Issue by patlecat** [CrowCpp/Crow#674]
I noticed that no release was created for a year but development seems active. Can we consider MASTER as stable enough for production? Have you stopped producing release all together?

**Comment by MichaelSB** [comment]
I use master all the time in production, because it has features my app depends on, that are not in the last release. It works for me. Of course I'd feel better, if there were more recent releases including those features :D

**Comment by patlecat** [comment]
@MichaelSB Ok thanks. It's just that there's then also no vcpkg to use, which is super handy nowadays. I don't understand why they never make releases anymore.

**Comment by patlecat** [comment]
No feedback?

**Comment by gittiver** [comment]
I started to prepare a new release from master.

**Comment by gittiver** [comment]
https://github.com/CrowCpp/Crow/releases/tag/v1.1.1 new release is out, 
I have some problems with documentation and packaging, that's why its tagged as pre-release.

Testers are welcome. :)
