### ISSUE TITLE
Serving static files

### ISSUE THREAD

**Issue by Stoyan-Bukovich** [CrowCpp/Crow#689]
How can I include a CSS stylesheet file in my HTML and serve it? I've been searching online and reading documentation and code, but I'm struggling to determine if Crow can serve static files like JPEGs, CSS, and JS from the default folder named "static."

What I want to achieve is to use files from the "static" folder in my HTML, such as: `<img src="/static/images/hello.jpeg" />`.

I would greatly appreciate any comments that could help clarify this issue for me.

**Comment by The-EDev** [comment]
it should be able to serve anything inside "static" as long as the path is the same as the file's

**Comment by Stoyan-Bukovich** [comment]
Thanks for your response @The-EDev I've set this simple starting app (just grasping out of curiosity the CrowCpp). `crow::App<crow::CookieParser, crow::CORSHandler> app;
 11   crow::CORSHandler cors;
 10   cors.global()
  9     .headers("");
  8 
  7   crow::mustache::set_global_base("pages");
  6 
  5   CROW_ROUTE(app, "/")([&](const crow::request& req){
  4 
  3         return "";
  2       });
  1 
27    CROW_ROUTE(app, "/index")([&](const crow::request& req){
  1     handlers::index idx;
  2 
  3     return idx.OnGet(req);
  4   });
  5 
  6   app.catchall_route()([&](const crow::request& req){
  7         return "No route exists for this request.";
  8       });
  9 
 10   auto _a = app
 11     .server_name("test server")
 12     .port(5000)
 13     .loglevel(crow::LogLevel::DEBUG)
 14     .multithreaded()
 15     .run_async();
`
the Index route handler: ` string OnGet(const crow::request& req){
  1         auto page = crow::mustache::load("index.html");
13          crow::mustache::context ctx ({{"", ""}});
  1 
  2         return page.render_string(ctx);
  3       }
`
and the index.html `<img src="/static/images/hello.jpeg" />.` anyways its not getting served. I am missing something? (sorry for the raw example)

Much appreciated your help.

**Comment by gittiver** [comment]
or you can use response from file like in https://github.com/CrowCpp/Crow/blob/master/examples/example_static_file.cpp
