### ISSUE TITLE
Websockets / Ungraceful disconnection -> Worker crash

### ISSUE THREAD

**Issue by hbrock578** [CrowCpp/Crow#690]
Hi,

I'm using the latest master version to test websockets. In case of an ungraceful dicsconnection (eg. I'm just closing the webbrowser which has an open websocket connection) I get the following crow error:

Worker Crash: An uncaught exception occurred: [json.exception.type_error.316] incomplete UTF-8 string; last byte: 0xE9

In this case none of the websocket callbacks onclose or onerror gets executed for the ungraceful closed connection. Is this expected behaviour? Is it somehow possible to get a notification that the websocket connection is closed in this case?

Thanks for your help!

Kind regards,
Holger

**Comment by MichaelSB** [comment]
This is an exception nlohmann json is throwing. Looks like it's trying to process incomplete/bad data. Also, I'm not able to reproduce this issue. onclose is called when the browser window is closed. At least that's the case in my apps. Is it possible, that the json exception is thrown before crow had a chance to call onclose?

**Comment by hbrock578** [comment]
Argh, thanks Michael for pointing this out! Apologies, the problem is not related to Crow and the onclose callback is called even if I just close the browser. The above issue is triggered in my onclose handler code while processing the onclose reason string with nlohmann::json ...

**Comment by gittiver** [comment]
ok, no issue in crow, the one from last comment is already there, so issue will be closed.
