### ISSUE TITLE
How to read values from crow::json::wvalue object?

### ISSUE THREAD

**Issue by akochkarev** [CrowCpp/Crow#724]
I'm a bit confusing. How to read values from crow::json::wvalue object?

Example:

```
crow::json::wvalue::list files_list = get_files_list(); // This is my function 

for(const crow::json::wvalue& file_item : files_list) {
    // How to read string value from file_item?
    log(file_item.s()); // This is not working, since wvalue didn't have s() member function like rvalue.
}
```

I will be grateful for any help.

**Comment by gittiver** [comment]
It will not work with crow::json:wvalue.  crow::json::value_reader could be used or dump value to string and create rvalue by loading it.

**Comment by akochkarev** [comment]
@gittiver, thank you for response!

I am using Crow 1.0-5 from vcpkg repo.
And there is no wvalue_reader struct, like I see in current version in this repo.
So I am ending up with dump solution for a now:

```
namespace json = crow::json;

json::wvalue::list files_list = get_files_list();

for(const auto& file_item : files_list) {
    json::rvalue file_item_rvalue = json::load(file_item.dump());
    string file_path = file_item_rvalue.s();
    // ...
}   
```

**Comment by gittiver** [comment]
On master have a look on https://github.com/CrowCpp/Crow/blob/17034adae5832f88aab0390d1670d268f3944385/include/crow/json.h#L1967

Maybe it was not in the release, I am preparing a new one which will be released soon.

**Comment by akochkarev** [comment]
Yes, the latest release v1.0+5 didn't have this struct.
