### ISSUE TITLE
Dynamic routing/params on websocket route?

### ISSUE THREAD

**Issue by jwlodek** [CrowCpp/Crow#730]
Hi, I'm writing a server that is attached to another process that is responsible for controlling some piece of hardware. The other process represents all hardware functions and monitors with some kind of unique name (string).

The client for this will give the server a list of these unique names, and in response the server is meant to send the client the current values (GET request), attempt to set the specified value (PUT request), or via a websocket constantly transmit live data. I have the GET and PUT functions working fairly easily - I just added a catchall route that gets the url and considers that the unique name - 404s if the hardware doesn't have this, otherwise returns the current value. The PUT is also working in a similar way.

However, I don't know how to do this for the monitoring aspect. What I would like ideally is for there to be a way to pass parameters (i.e. these unique names in a list) to the websocket via the initial request, but I don't see how to get the request object to get the params out of it. Is there a way to do this with `Crow`?

**Comment by gittiver** [comment]
The question is related to your protocol on web sockets not to crow itself.
You could send an initial message containing th list of names over the web socket and then prefix the values with the index in the list in follow up messages containing values.
