### ISSUE TITLE
How to redirect from port 80(http) to 443(https) ?

### ISSUE THREAD

**Issue by writePerfectCode** [CrowCpp/Crow#733]
Should I setup two app, one listen on 80, the other listen on 443.
And when user input url with http, the app on port 80 response redirect the url to https ?

**Comment by gittiver** [comment]
You can use only one of them inside of crow. 
I would add an external proxy for redirecting one to the other. Usually Apache, nginx or haproxy may be used for that purpose.

**Comment by writePerfectCode** [comment]
> You can use only one of them inside of crow. I would add an external proxy for redirecting one to the other. Usually Apache, nginx or haproxy may be used for that purpose.

I know can use proxy, but if not how to redirect?

**Comment by gittiver** [comment]
I would propose to use Http-Status code 301 (Moved permanently, see https://http-statuscode.com/de/code/3XX/301).
So the app on port 80 will return a response with that status code, a "Location" header with the new URI (https://....) and optionally in content a short notice for the new URL.

see: https://crowcpp.org/master/reference/structcrow_1_1response.html

or use that one:
void crow::response::redirect_perm |(const std::string & location) Location can either be a route or a full URL.
