### ISSUE TITLE
what is [147B blob data] ?

### ISSUE THREAD

**Issue by OliverLonghi** [CrowCpp/Crow#745]
I see this line in my logs and I would like to know what is it about. I'm having a segfault issue and I need like to know if it is somehow related. 

```
Jan 20 04:31:25 ip-10-23-20-54 pagetype[1647]: [147B blob data]
```

Thanks!

**Comment by gittiver** [comment]
Sorry, without sources or anything else we can't help here. I searched for page type and for blob in the sources and did not found it. 
So probably the log output is not even from crow.
