### ISSUE TITLE
Using crow with classes

### ISSUE THREAD

**Issue by jacob-02** [CrowCpp/Crow#746]
Hello everyone, 

I am working on using crow for making API calls. I am new to this space so I might be messing up somewhere. But I want to create like functions with the CROW_ROUTE part inside it where if I call the function and pass in the required data it will put it on the designated address. For example :

```
void API::send(app, std::string data)
{
    crow::json::wvalue dataJson;
    std::cout << "Publishing" << std::endl;

    dataJson["data"] = data;

    CROW_ROUTE(app, "/test")([&]()
    { 
        return dataJson; 
    });
}

```
And if I create an object of the API class, and call the send function by passing the app variable and data to send, it should perform the action. Something similar to MQTT type messages publish and subscribe setup.

If anyone could help me understand how to do this or if it is even possible I would be extremely grateful because from examples I see in the web I have not found something similar.

Thank you in advance.

**Comment by gittiver** [comment]
It is not possible that way.
You could extend app with a member variable holding the data and a function to set them.
Or with a variable in main which is handed over to handlers:

   crow::json::wvalue dataJson;

   void API::send(app, std::string data)
  {
      std::cout << "Publishing" << std::endl;
      dataJson["data"] = data;
   }

    CROW_ROUTE(app, "/test")([&dataJson]()
    { 
        return dataJson; 
    });
}
