### ISSUE TITLE
How to deny a response?

### ISSUE THREAD

**Issue by Steeven512** [CrowCpp/Crow#751]
I need to deny or end the call without returning the response

**Comment by MichaelSB** [comment]
Why though? That's usually not how http works.

**Comment by Steeven512** [comment]
I mean, depending on the logic within the route, return a response or not.

**Comment by MichaelSB** [comment]
Return a 404 response or some other status code that indicates why the client does not get the ok response. What's the use case of returning "no response"? How is a client supposed to detect that "no response" is coming?
