### ISSUE TITLE
Auto-restart Server should be available, Adding Cpase might be a good idea

### ISSUE THREAD

**Issue by yahya-mohammed07** [CrowCpp/Crow#752]

**Comment by yahya-mohammed07** [comment]
@gittiver Hi, When i use a third party package called `Cpase` to restart the server by re-compiling and running the server again , an exception rises: `terminate called after throwing an instance of 'boost::wrapexceptboost::system::system_error'
what(): bind: Address already in use [system:98 at /usr/include/boost/asio/detail/reactive_socket_service.hpp:161 in function 'bind']` tho i'm restarting the server, but it says the socket is still in use.

**Comment by gittiver** [comment]
well if the restart fails the previous process/instance was not closed or leaved the server socket open. depending on OS you can find that out with net stat -A or lsof. probably not a bug in crow.

see also here: https://www.cyberciti.biz/faq/how-to-check-open-ports-in-linux-using-the-cli/

Assuming it's from previous instance of crow - check if there are exceptions or error logs on close.
