### ISSUE TITLE
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'

### ISSUE THREAD

**Issue by yahya-mohammed07** [CrowCpp/Crow#753]
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  bind: Address already in use [system:98 at /usr/include/boost/asio/detail/reactive_socket_service.hpp:161 in function 'bind']

**Comment by gittiver** [comment]
There was another process which has opened the server socket. As it can not open the server socket,  crow can only show the exception and exit. so it is intended behavior. 

Question: maybe there was another crow process open?
