### ISSUE TITLE
is crow synchronous only?

### ISSUE THREAD

**Issue by laoshaw** [CrowCpp/Crow#757]
say if the backend processing needs a while to complete, will Crow block on that request?

**Comment by gittiver** [comment]
Crow is the backend, handler is blocking its worker thread, while running.
Input/ output is asynchronous.

**Comment by 21vishnuvinod** [comment]
Does it mean that with other threads have to wait until the current worker thread finishes processing a request and responds to the client?

**Comment by gittiver** [comment]
No.

**Comment by gittiver** [comment]
A thread is only blocked while the handler is running, means it blocks only one request. 
reading other requests and writing responses is in general asynchronous through the use of asio library (see here: https://think-async.com/Asio/).

**Comment by 21vishnuvinod** [comment]
Understood. Thank you
