### ISSUE TITLE
CORS problem in 1.1.0

### ISSUE THREAD

**Issue by witcherofthorns** [CrowCpp/Crow#764]
## Problem

Hello everyone, I tried the new Crow 1.1.0, I know that this is a pre-release, but just in case I’ll leave it here. I'm working on an application, and I've never had any problems except with CORS, **I spent 3-4 days on them - and still no results**. In the end, I came to the conclusion that I decided to try to compare version 1.0.5 and 1.1.0, and here are the results on screenshot

I’ve already tried everything, looked at the Crow sources, read the documentation up and down, in general, I still don’t understand what to do with it. I really like Crow and I hope this information is useful as an issue report. As a result, I’ll probably go back to version 1.0.5v for now

![Screenshot_20240214_132240](https://github.com/CrowCpp/Crow/assets/45733964/bc4571b7-23f9-493b-903f-391b5f7835fa)

## Responses

OPTIONS Crow 1.0.5v response
```text
HTTP/1.1 204 No Content
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST, GET
Access-Control-Allow-Origin: http://localhost:8080
Access-Control-Allow-Headers: *
Allow: OPTIONS, HEAD, GET, POST
Content-Length: 0
Server: Crow/1.0
Date: Wed, 14 Feb 2024 10:16:27 GMT
Connection: Keep-Alive
```

OPTIONS Crow 1.1.0v response
```text
HTTP/1.1 204 No Content
Allow: OPTIONS, HEAD, GET, POST
Content-Length: 0
Server: Crow/1.1.0
Date: Wed, 14 Feb 2024 10:21:22 GMT
```

## Source code
I created an empty separate project and used the same code in both version 1.1.0 and 1.0.5, you can see the results in the screenshot

```cpp

#include <crow.h>
#include <crow/middlewares/cors.h>
#include <nlohmann/json.hpp>
using namespace crow;

int main() {

    App<CORSHandler> app;
    auto &cors = app.get_middleware<CORSHandler>();
    cors.global()
        .origin("http://localhost:8080")               // frontend vue-js host
        .allow_credentials()                           // just in case
        .methods("POST"_method, "GET"_method);
    
    CROW_ROUTE(app, "/user").methods(HTTPMethod::GET)([&](const request &req){
        nlohmann::json json = {
            {"age", 25},
            {"nick", "witcher"},
            {"name", "miroslaw"}
        };
        return response(OK, "application/json", json.dump());
    });

    CROW_ROUTE(app, "/user").methods(HTTPMethod::POST)([&](const request &req) {
        return response(OK);
    });

    app.port(18080).run();

    return 0;
}
```

## Other info
Linux Ubuntu 22.04
I use Conan and CMake, Asio is used exclusively for version 1.1.0 from Conan Center

```python
from conan import ConanFile

class HelloConan(ConanFile):
    name = "***"
    version = "0.1"
    author = "Miroslaw Badurow"
    settings = "os", "arch", "compiler", "build_type"
    generators = "CMakeDeps", "CMakeToolchain"

    def requirements(self):
        self.requires("asio/1.29.0")
        self.requires("mongo-cxx-driver/3.8.1")
        self.requires("nlohmann_json/3.11.3")
        self.requires("jwt-cpp/0.7.0")
        self.requires("boost/1.83.0", override=True)
```

**Comment by witcherofthorns** [comment]
I dug a little into the source code, so far, this is the only crutch option to get CORS to work in v1.1.0. The problem is that the middleware CORSHandler does not work at all, I am still researching this issue and testing

source: [routing.h](https://github.com/CrowCpp/Crow/blob/master/include/crow/routing.h#L1598)
```cpp
if (rules_matched)
{
    allow = allow.substr(0, allow.size() - 2);
    res = response(204);
    res.set_header("Allow", allow);
    res.end();
    found->method = method_actual;
    return found;
}
```
this work (crutch):
```cpp
if (rules_matched)
{
    allow = allow.substr(0, allow.size() - 2);
    res = response(204);
    res.set_header("Allow", allow);
    res.add_header("Access-Control-Allow-Origin", "http://localhost:8080");
    res.add_header("Access-Control-Allow-Headers", "Origin, Content-Type, Accept");
    res.add_header("Access-Control-Allow-Methods", "*");
    res.add_header("Access-Control-Max-Age", "5");
    res.end();
    found->method = method_actual;
    return found;
}
```


I still have a feeling that something is wrong with the CORS middleware, because it doesn’t work at all, perhaps I don’t understand something, correct me if anything

source: [cors.h](https://github.com/CrowCpp/Crow/blob/master/include/crow/middlewares/cors.h#L132)
```cpp
void before_handle(crow::request& /*req*/, crow::response& /*res*/, context& /*ctx*/) {
    CROW_LOG_DEBUG << "[CORS]: before_handle";
}

void after_handle(crow::request& req, crow::response& res, context& /*ctx*/) {
    CROW_LOG_DEBUG << "[CORS]: after_handle";
    auto& rule = find_rule(req.url);
    rule.apply(res);
}
```

But at the same time, any other middleware after a successful OPTIONS CORS request works without problems

source: my main.cpp
```cpp
struct CORSTest {
    struct context{};

    void before_handle(crow::request& req, crow::response& res, context& ctx){
        CROW_LOG_INFO << "CORSTest before_handle";
    }

    void after_handle(crow::request& req, crow::response& res, context& ctx) {
        CROW_LOG_INFO << "CORSTest after_handle";
    }
};
```

I still haven't determined the reason for this behavior yet, but it seems to me that the problem lies somewhere in [routing.h](https://github.com/CrowCpp/Crow/blob/master/include/crow/routing.h), I will try to look into this in more detail as soon as I have less work and more free time. If you know what the reason is, **please reply to this message, thanks in advance**

**Comment by gittiver** [comment]
Thanks for your investigation, I hadn't the time to look deeper into the issue.
unit test TEST_CASE("middleware_cors") checks only GET request.

**Comment by witcherofthorns** [comment]
https://github.com/CrowCpp/Crow/pull/771 This almost completely fixes the problem, but I found a strange anomaly, it feels like the response is limited by the number of headers returned 4

**Comment by junekhan** [comment]
@witcherofthorns It's probably an issue on your side if your CORS configured exactly as 
```C++
App<CORSHandler> app;
    auto &cors = app.get_middleware<CORSHandler>();
    cors.global()
        .origin("http://localhost:8080")               // frontend vue-js host
        .allow_credentials()                           // just in case
        .methods("POST"_method, "GET"_method);
```

you're then supposed to see
```
HTTP/1.1 204 No Content
Access-Control-Allow-Headers: Accept, Origin, Content-Type, Authorization
Access-Control-Allow-Methods: POST, GET
Access-Control-Allow-Origin: http://localhost:8080
Access-Control-Allow-Credentials: true
```
without `Access-Control-Max-Age: 5`.

Is it possible that you touched the Crow code and forgot to revert?

**Comment by witcherofthorns** [comment]
@junekhan Ok, check this and try send POST req

```cpp
App<CORSHandler> app;
auto &cors = app.get_middleware<CORSHandler>();
cors.global()
    .origin("http://localhost:8080")
    .headers(
        "Accept",
        "Origin",
        "Content-Type",
        "Authorization"
    )
    .allow_credentials()
    .max_age(10);
```
Yes, if you don’t specify max_age, then everything is fine

**Comment by witcherofthorns** [comment]
Okay, we can probably consider this problem solved for now, the most important thing is that CORS generally works, i'll try to come back to this problem later. Thank you @junekhan
Hey @gittiver, i think we can close this problem and revision https://github.com/CrowCpp/Crow/pull/771
