### ISSUE TITLE
101 Switching Protocol in json data on the first request

### ISSUE THREAD

**Issue by fliiiix** [CrowCpp/Crow#765]
This might be more of a question than a bug, but im struggling to understand why 
`auto data = crow::json::load(req.body);` contains a wrong value the first time i pass it into a jthread but not the second time.
Im basically doing something like this `std::jthread play{play_stream, data["url"].s()};` and the first time this value inside the `play_stream` function is ` 101 Switching Protocol` and only the second time it contains the value i sent via curl.

I looked at the docs but i still don't really understand why that happens 
https://crowcpp.org/master/reference/classcrow_1_1json_1_1rvalue.html#ad94f27a14e60af841219279f70290858

full minimal example
```
#include <thread>
#include <future>

#include <crow.h>

void play_stream(std::stop_token stoken, std::string stream_url)
{
    CROW_LOG_INFO << "mediaplayer: start for " << stream_url;

    std::promise<void> stop;
    std::stop_callback callBack(stoken, [&stop] {
        CROW_LOG_INFO << "mediaplayer: stop";
        stop.set_value();
    });

    // wait until cancled
    stop.get_future().wait();
}

int main(int /*ac*/, char** /*av*/)
{
    CROW_LOG_INFO << "Playing some music";
    std::jthread current;

    crow::SimpleApp app;

    CROW_ROUTE(app, "/play")
      .methods(crow::HTTPMethod::Post)([&current](const crow::request& req) {
        auto data = crow::json::load(req.body);
        CROW_LOG_INFO << "/play with for: " << data["url"].s();
        std::jthread play{play_stream, data["url"].s()};
        current.swap(play);

        return crow::response{"{}"};
    });

    CROW_ROUTE(app, "/stop")([&current](){
        current.request_stop();
        return "{}";
    });

    app.loglevel(crow::LogLevel::Info);
    app.port(8000).multithreaded().run();
}
```

And I query that with curl like this -> 
```
curl -H "Content-Type: application/json" -d '{"url":"http://fritz.de/livemp3"}' http://localhost:8000/play
```

Which produces a log like this ->
```
(2024-02-17 16:07:24) [INFO    ] Playing some music
(2024-02-17 16:07:24) [INFO    ] Crow/1.1.0 server is running at http://0.0.0.0:8000 using 12 threads
(2024-02-17 16:07:24) [INFO    ] Call `app.loglevel(crow::LogLevel::Warning)` to hide Info level logs.
(2024-02-17 16:07:27) [INFO    ] Request: 127.0.0.1:51990 0x1a46550 HTTP/1.1 POST /play
(2024-02-17 16:07:27) [INFO    ] /play with for: http://fritz.de/livemp3
(2024-02-17 16:07:27) [INFO    ] Response: 0x1a46550 /play 200 0
(2024-02-17 16:07:27) [INFO    ] mediaplayer: start for  101 Switching Protocol
(2024-02-17 16:07:29) [INFO    ] Request: 127.0.0.1:51994 0x7ff708000c30 HTTP/1.1 POST /play
(2024-02-17 16:07:29) [INFO    ] /play with for: http://fritz.de/livemp3
(2024-02-17 16:07:29) [INFO    ] mediaplayer: stop
(2024-02-17 16:07:29) [INFO    ] mediaplayer: start for http://fritz.de/livemp3
(2024-02-17 16:07:29) [INFO    ] Response: 0x7ff708000c30 /play 200 0
```

Notice how the log from the `mediaplayer` is 
```
first request: (unexpected)
(2024-02-17 16:07:27) [INFO    ] mediaplayer: start for  101 Switching Protocol

second request: (expected)
(2024-02-17 16:07:29) [INFO    ] mediaplayer: stop
(2024-02-17 16:07:29) [INFO    ] mediaplayer: start for http://fritz.de/livemp3
```

The solution i used it to fix it was by creating a new string.
```
std::string url = data["url"].s();
```
and then passing `url` into the jthread which works, but i still would like to understand why that is required.

**Comment by gittiver** [comment]
maybe an issue with default constructed tread?

https://en.cppreference.com/w/cpp/thread/jthread/swap
std::jthread objects may also be in the state that does not represent any thread (after default construction, move from, detach, or join), and a thread of execution may be not associated with any jthread objects (after detach).

Maybe having a synchronized list or queue for urls and let the player choose from them? 
Then play thread could run from the beginning and now swap would be needed?

**Comment by fliiiix** [comment]
Interesting creating `std::jthread current{play_stream, ""};` would also work so maybe calling swap on `std::jthread current` is undefined behavior? 

Although i can not get it to fail on a minimal example without crow.

```
void play_stream(std::stop_token stoken, std::string stream_url)
{
    std::cout << "mediaplayer: start for " << stream_url << "\n";

    std::promise<void> stop;
    std::stop_callback callBack(stoken, [&stop] {
        std::cout << "mediaplayer: stop\n";
        stop.set_value();
    });

    // wait until cancled
    stop.get_future().wait();
}

int main(int /*ac*/, char** av)
{   
    std::jthread current;
    
    std::jthread play{play_stream, av[0]};
    current.swap(play);
}
```

And `start for  101 Switching Protocol` looks like some memory for the request/response in crow.

**Comment by gittiver** [comment]
I think its the combination of swapping in a thread while also handing it over to the handlers by reference, 
but not sure if that is the case.
