### ISSUE TITLE
Not found Crow websocket in Conan

### ISSUE THREAD

**Issue by witcherofthorns** [CrowCpp/Crow#775]
Hello everyone, I'm using [Crow 1.0.5v from Conan](https://conan.io/center/recipes/crowcpp-crow), and I have a problem, for some reason in the Crow 1.0.5v package there is no Websocket in the [app.h](https://github.com/CrowCpp/Crow/blob/v1.0/include/crow/app.h) file:
```cpp
#define CROW_WEBSOCKET_ROUTE(app, url) ...
```

Yes, I can, of course, simply clone it as a Crow submodule or download it as an archive, but I would still like to use everything through Conan. Please, if you have some free time, add Websocket to the Conan package. Or, if I don't understand something, please explain to me what’s wrong

**Comment by gittiver** [comment]
It seems, that Conan now has v1.1.0 - at least the site shows it: https://conan.io/center/recipes/crowcpp-crow

**Comment by witcherofthorns** [comment]
Yes, I understand that there is version v1.1.0, but I’m still afraid to switch to v1.1.0, and prefer to use 1.0+5. Ok, apparently I will use version 1.1.0 for the websocket server, since there is no other option left 🤔
