### ISSUE TITLE
Update master to Conan 1.1.0

### ISSUE THREAD

**Issue by witcherofthorns** [CrowCpp/Crow#797]
Hi, could you please update the current state of the Crow master branch in Conan Center? 📦
The thing is that the CORS middleware has been updated in the master but it is not in the Conan repository https://github.com/CrowCpp/Crow/issues/764, this may help many people to fix their CORS problem.
I saw approximately the same request for vcpkg https://github.com/CrowCpp/Crow/issues/793, it that would also not hurt in Conan

**Comment by gittiver** [comment]
1.1.0 is there, see https://github.com/conan-io/conan-center-index/pull/22537

What you want is a new release based on master, right?

**Comment by witcherofthorns** [comment]
@gittiver yes, im talking specifically about version 1.1.0

**Comment by gittiver** [comment]
as 1.1.0 is already on Conan repos, I will close the issue. 

a new release is planned but not sure, when I find the time to prepare it and there is an open issue with the versionated mkdocs documentation.

**Comment by witcherofthorns** [comment]
@gittiver Okay, i understand, when is the release of **version 1.1.1** planned? If it's planned at all
p.s. dont have to open a new issues, just reply to me here

**Comment by gittiver** [comment]
Well, it's not yet planned, as my time currently goes into other things. Hope in the first two weeks of may I can do it.

**Comment by witcherofthorns** [comment]
ok, thx you very much for your answer, im wait updates
