### ISSUE TITLE
Undocummented Macros

### ISSUE THREAD

**Issue by Nabzokek** [CrowCpp/Crow#801]
I have seen that there are undocumented functions, I especially emphasize **Macros** and **Aliases**.

According to the [`crow::Crow` class page of the Reference (and source code)](https://crowcpp.org/master/reference/classcrow_1_1_crow.html), it is recommended to use Macros such as `CROW_ROUTE`, `CROW_BP_ROUTE`, or `CROW_WEBSOCKET_ROUTE` (among others) instead of the methods of the `Crow` class itself.

> ```cpp
> /// Create a dynamic route using a rule (**Use CROW_ROUTE instead**)
> DynamicRule& route_dynamic(const std::string& rule)
> ```

> ```cpp
> /// Create a route using a rule (**Use CROW_ROUTE instead**)
> template<uint64_t Tag>
> #ifdef CROW_GCC83_WORKAROUND
> auto& route(const std::string& rule)
> #else
> auto route(const std::string& rule)
> #endif
> ```
 
There are also two undocummented aliases for `crow::Crow` called `crow::SimpleApp` (`crow::Crow<>`), and `crow::App` (`crow::Crow<Middlewares...>`) which do not appear in the reference.

> ```cpp
> template<typename... Middlewares>
> using App = Crow<Middlewares...>;
> using SimpleApp = Crow<>;
> ```

I'm aware that these members appear repeatedly on the [getting started page](https://crowcpp.org/master/getting_started/setup/linux/), but I think it would be wise to add them in the reference as well.

**Comment by gittiver** [comment]
Feel free to add them there.

**Comment by Nabzokek** [comment]
It seems like I will need to make `Doxyfile` generate a **Namespace list** tree. Is not a problem if I do this?

```sh
# Set the SHOW_NAMESPACES tag to NO to disable the generation of the Namespaces
# page. This will remove the Namespaces entry from the Quick Index and from the
# Folder Tree View (if specified).
# The default value is: YES.
    
SHOW_NAMESPACES        = YES
```

I don't know other way to mention `SimpleApp` or `App` otherwise.
