### ISSUE TITLE
Crow_enable_ssl

### ISSUE THREAD

**Issue by khalimwu** [CrowCpp/Crow#805]
I'm using windows. Have crow implemented and working on a c++ project, however as soon as i enable ssl as preprocessor define (it compile and run fine on my development pc), when i run it on my server i start getting ucrtbased and vcruntime140d errors when launched.
Also, whenever i delete "debug" lib files (such as libssl) inside the debug folder (under vcpkg_installed folder) even if im on release i get linking errors, so it makes sense that it's actually using debug for ssl.
Help is appreciated. Thanks

**Comment by gittiver** [comment]
You have to build it with ssl enabled, means you have to provide the openssl library for linking against it.
Habe a look here: https://crowcpp.org/master/getting_started/setup/windows/

there is the description for windows.
