### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by akarsh-shrivastava** [CrowCpp/Crow#812]
Hi, 
I am trying to install Crow on Ubuntu 18.04 on WLS.
When I try to execute `make install` it fails with the following error message (attached as a file).
I guess some headers are not included and that's causing the issue.

Can someone please help me with this.

Thanks

[error.txt](https://github.com/CrowCpp/Crow/files/15201215/error.txt)

**Comment by gittiver** [comment]
Do you have asio lib package installed? should be named as asio or asio-dev.
It seems the Casio library is missing.

**Comment by akarsh-shrivastava** [comment]
@gittiver I have libasio-dev installed. I can't seem to find Casio.

**Comment by gittiver** [comment]
Casio was a typo I meant asio lib.

**Comment by akarsh-shrivastava** [comment]
@gittiver I just realized I had an older version of asio. I installed 1.28.1 and it worked.
Thanks a lot for your help!
