### ISSUE TITLE
Is it ok to use `#pragma once` instead of `#define CROW_STUFF_H` in crow's header files?

### ISSUE THREAD

**Issue by Nabzokek** [CrowCpp/Crow#814]
This isn't more than a suggestion, but I think that use `#pragma once` isn't the more recommended way to define header files, considering we want to make CrowCpp a cross platform library.

When you search for [`#pragma once` in the project files](https://github.com/search?q=repo%3ACrowCpp%2FCrow%20%23pragma%20once&type=code) you will see **so much files with this line**.

This is not **so bad**, but maybe it would be better if we use `#define CROW_THING_H` in the library header files instead of the [not standard `#pragma once` lines](https://en.cppreference.com/w/cpp/preprocessor/impl#Non-standard_pragmas).

**Comment by gittiver** [comment]
It would make sense to add header guards and to leave pragma in addition in the file.
#pragma once is non standard but supported by most compilers. 

So we should end up with:
#ifdef CROW_THING_H
#define CROW_THING_H
#pragma once
...
#endif /* #ifdef CROW_THING_H */

**Comment by Nabzokek** [comment]
It seems fine to me, but in that case, using the `#pragma once` would no longer make sense, because **header guards** already solve that problem.
We can leave the `#pragma once` as well, but I don't think it would make much sense anymore.

**Comment by gittiver** [comment]
It would only help a little bit on compile times (for some compilers).
