### ISSUE TITLE
Remove unused dependencies from vcpkg

### ISSUE THREAD

**Issue by 33Heisenberg33** [CrowCpp/Crow#825]
With version 1.1.0 boost dependencies have been removed from crow. However in vcpkg only the "boost-asio" dependency was removed and the others are still there.

https://github.com/microsoft/vcpkg/blob/master/ports/crow/vcpkg.json

Please remove the unused dependencies.

**Comment by 33Heisenberg33** [comment]
Thanks!

**Comment by gittiver** [comment]
waits for vcpkg maintainer PR approval ...
