### ISSUE TITLE
SNI Support

### ISSUE THREAD

**Issue by kwach** [CrowCpp/Crow#826]
Hey guys, 

I've got a question about whether is possible to write a server that supports SNI (Server Name Indication)?

Cheers!

**Comment by gittiver** [comment]
I would propose, that you use apache or nginx as Proxy in front of crow as they already support this in a well tested manner.
SSL Support in crow is somehow in experimental status and as far as I know SNI is not supported.
For now I also haven't noticed any feature requests for this.

But in principle it would be possible.
