### ISSUE TITLE
Nested blueprints need static directory

### ISSUE THREAD

**Issue by david072** [CrowCpp/Crow#828]
When using nested blueprints, the app currently throws the following exception when there is no static directory defined for the parent blueprint:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Internal error: Trie header should be simple!
```

Minimal reproducible example (using v1.2.0 `crow_all.h` from Releases):
```cpp
#include "crow_all.h"

int main() {
  crow::SimpleApp app;

  // this works
  // crow::Blueprint bp("bp_prefix", "whatever");

  // this doesn't
  crow::Blueprint bp("bp_prefix");

  crow::Blueprint sub_bp("bp2");

  CROW_BP_ROUTE(sub_bp, "/hello")
  ([]() { return "Hello world!"; });

  bp.register_blueprint(sub_bp);
  app.register_blueprint(bp);
  app.port(18080).run();
}
```

Is this intended behavior? I could not see any info about it on [the website](https://crowcpp.org/master/guides/blueprints/#register-other-blueprints).

**Comment by gittiver** [comment]
Not really intended behavior, it's definitely a bug. 
if the top level blueprints static_dir is empty its simply ignored and not added to routing. 
That causes the bug in the end, as no routes are found then.
