### ISSUE TITLE
Compilation error when including crow in a C++ application

### ISSUE THREAD

**Issue by itz-arnav** [CrowCpp/Crow#836]
Problem:
std::vector<int> signals()
{
    return signals_;
}

This method in crow/app.h causes compilation error, but if i comment out this method, it compiles and works fine.

![crow issue](https://github.com/CrowCpp/Crow/assets/64909912/97a74660-5611-4a07-83a7-aafb2fcc1376)

Here's the error details:
C:\Users\Arnav\vcpkg\installed\x64-windows\include\crow\app.h:302: error: C2059: syntax error: 'public'
C:\Users\Arnav\vcpkg\installed\x64-windows\include\crow/app.h(302): error C2059: syntax error: 'public'
C:\Users\Arnav\vcpkg\installed\x64-windows\include\crow/app.h(766): note: see reference to class template instantiation 'crow::Crow<Middlewares...>' being compiled
C:\Users\Arnav\vcpkg\installed\x64-windows\include\crow\app.h:302: error: C2059: syntax error: ')'
C:\Users\Arnav\vcpkg\installed\x64-windows\include\crow\app.h:303: error: C2334: unexpected token(s) preceding '{'; skipping apparent function body

I've used vcpkg to install Crow and my Crow's version is: crow:x64-windows@1.2.0
I'm using Qt Creator, MSVC x64 compiler and my CMake version is > 3.16

**Comment by gittiver** [comment]
Are you using QT_OBJECT for the class, this defines a macro "signals" which expands to "public:"?

**Comment by itz-arnav** [comment]
Yes! I think that's the issue, I was using Q_OBJECT in my class.

**Comment by gittiver** [comment]
#undefine signals before including crow app

or using the crow include first
