### ISSUE TITLE
Implicit construction of `crow::multipart::message` from `crow::request`

### ISSUE THREAD

**Issue by bgs99** [CrowCpp/Crow#839]
Would you consider marking `crow::multipart::message` constructor from `crow::request` as explicit?

Parsing multipart message is a somewhat computationally expensive process, and currently (#838) leads to excessive memory copying.

I have encountered this problem when writing and using small helpers that extract data from multipart messages - accidentally passing a `crow::request` there instead of a `crow::multipart::message` leads to re-parsing of the request.
Marking the constructor as explicit would make this error easily noticeable and less probable.

**Comment by gittiver** [comment]
Make a PR and make it explicit. If that runs we will take it over.

**Comment by gittiver** [comment]
PR merged, so can be closed.
