### ISSUE TITLE
Can't compile hello word, as soon as crow.h is included nothing works

### ISSUE THREAD

**Issue by philhzss** [CrowCpp/Crow#858]
Hi,

I'm 90% sure this is super silly and just some kind of misconfiguration mistake on my side with Visual Studio but I've been unable to get it to work in 3 days.

I'm working on a Linux program that I write in Visual Studio and then use remote debugging or whatever its called to build and run on my Raspberry Pi. It's been working for a few years, I hadn't updated my program in a few months but I tried to do changes and now it doesn't even compile anymore. I tried to update Crow to the latest version (I was on a 2020 release), still not working, so I created a blank Linux project in MSVC again, it works. As soon as I include "crow.h", it stops working with a bunch of errors.

![image](https://github.com/user-attachments/assets/4b19df89-2d07-42ba-91e2-7cf567de821b)

In this new empty Hello World test, all I did was I switched Visual Studio to use C++14 (because it said Crow had a bug with GCC 8.3 in C++11 or something), but the rest is all default.

I didn't use to have ASIO (I think), because I think Crow in 2020 didn't require that?? I saw somewhere that I should have it, so I downloaded [ASIO from here](https://sourceforge.net/projects/asio/files/asio/1.30.2%20%28Stable%29/), the non-Boost version, and added that to my /usr/local/include on the Linux machine. Which is the same place Crow is installed.

The errors seem to be related to ASIO but I'm really confused with what to do, can anyone point me in the right direction? 

And just to be clear, I know this specific project doesn't do anything with Crow, other than including it. I created this empty project just to remove all other factors from the equation, when I remove the include crow.h line, the project compiles.

Thank you!!

**Comment by gittiver** [comment]
It looks like pthreads headers are missing. Is the pthread library and its headers there?

**Comment by philhzss** [comment]
> It looks like pthreads headers are missing. Is the pthread library and its headers there?

@gittiver 
Thank you, adding -pthread (or -lpthread) to my linker options makes my hello world test program compile and run properly. However it doesn't solve my main program that used to work. The errors are a bit different now though, something in middleware??


```
1>    /usr/local/include/crow/middleware.h:230:27: error: static assertion failed: Handler function cannot have void return type; valid return types: string, int, crow::response, crow::returnable
1>                 static_assert(!std::is_same<void, decltype(f(std::declval<crow::request>(), std::declval<Args>()...))>::value,
1>                               ^~~~
1>    /usr/local/include/crow/middleware.h:233:25: error: invalid use of void expression
1>                 res = crow::response(f(req, std::forward<Args>(args)...));
1>                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```


Thanks for your help and I'm sure that crow isn't the problem here. There is one file from nlohmann json library also giving me this error:
![image](https://github.com/user-attachments/assets/f4ff27ca-72e5-4a99-8b09-315441d11d52)


Let me know if you have any ideas, I'll keep trying stuff. Thank you!\

**Comment by philhzss** [comment]
I fixed it. Sorry for bothering you with this, I had a mistake in one of my Crow routes, I had commented out a line that I didn't mean to comment out.

**Comment by gittiver** [comment]
You are welcome.
