### ISSUE TITLE
Taking over an open connection in request handler

### ISSUE THREAD

**Issue by niansa** [CrowCpp/Crow#872]
Hi, as mentioned in #868 by gittiver it is not possible to send an eventstream.

I would like to instead basically "take over" the existing connection for the request (basically just somehow get the file descriptor from Crow and write to it myself).

Is this possible? If not but you think it's viable to add please label this as a feature request :-)

Thanks!

**Comment by gittiver** [comment]
Maybe you are looking for websockets: https://crowcpp.org/master/guides/websockets/ ?

**Comment by gittiver** [comment]
Its not possible to take over an existing connection.

**Comment by niansa** [comment]
> Its not possible

Yes. that's why I was asking to handle this like a feature request if it's not yet possible, so it might be made possible.
