### ISSUE TITLE
Deb packages not avail.

### ISSUE THREAD

**Issue by SavingCaustic** [CrowCpp/Crow#874]
https://crowcpp.org/1.2/getting_started/setup/linux/ states

> _Using a package Manager[¶](https://crowcpp.org/1.2/getting_started/setup/linux/#using-a-package-manager)
> 
> You can install Crow on GNU/Linux as a pre-made package
> Debian/Ubuntu
> 
> Simply download Crow's .deb file from the [release section](https://github.com/CrowCpp/Crow/releases/latest) and Install it._
> 

which is wrong, right?

Would help newscomers if that text is just deleted. Thanks.

**Comment by gittiver** [comment]
hadn't the time to reactivate the package building (its there but commented out).

**Comment by fliiiix** [comment]
I guess the goal is to have that build automatically by the pipeline? I failed to find how it was done previously
