### ISSUE TITLE
Is there a list of projects that use crow?

### ISSUE THREAD

**Issue by xia-stan** [CrowCpp/Crow#880]
I'm interested to see who's using Crow, their applications, etc. This information would help me, and others, who are evaluating Crow's use in production environments.

**Comment by gittiver** [comment]
As far as I know there is no such list. 
The only thing which goes into that direction is: https://github.com/topics/crow

**Comment by xia-stan** [comment]
Gotcha. What I'm looking for is something along the lines of what Oat++ provides: 
![image](https://github.com/user-attachments/assets/9ac06623-c3ad-4d9d-a1e0-1f57d9a4b505)
Not a huge deal for me or my use-case at the moment, but figured it might broaden the user base. I've found Crow to be the easiest to use C++ implementation.

**Comment by gittiver** [comment]
I've found Crow to be the easiest to use C++ implementation.

That's why I try to maintain it. :)

**Comment by witcherofthorns** [comment]
hi @xia-stan, i have already implemented and launched my service on Crow 1.2.0, everything works fine, including CORS and websockets. In the near future, if everything goes well with the project, I will definitely inform everyone about it. I'm currently planning to implement (hobby project) another platform/app and Crow is a great fit for it 👌
Thanks to everyone for Crow and contributions to the project ✨
