### ISSUE TITLE
Not working with Lets Encrypt SSL certificates?

### ISSUE THREAD

**Issue by timj-code** [CrowCpp/Crow#887]
I'm trying to setup a HTTPS service, using Lets Encrypt certificate. I've set the SSL in CROW code like this:
```
    app.port(17000)
       .ssl_file("path_to_fullchain.pem", "path_to_privkey.pem")
       .multithreaded()
       .run();
```
and compiled with CROW_ENABLE_SSL defined.
 
But then I found I can not establish ssl connection with the server, using openssl at the client side found the certificate chain information was not correct:

> :~$ openssl s_client -connect my.service.url:17000 -showcerts
> CONNECTED(00000003)
> **depth=0** CN = my.service.url
> verify error:num=20:unable to get local issuer certificate
> verify return:1
> **depth=0** CN = my.service.url
> verify error:num=21:unable to verify the first certificate
> verify return:1
> **depth=0** CN = my.service.url
> verify return:1
> 
> 
> Certificate chain
>  0 s:CN = my.service.url
>    i:C = US, O = Let's Encrypt, CN = R11
>    a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
>    v:NotBefore: Sep  3 15:15:17 2024 GMT; NotAfter: Dec  2 15:15:16 2024 GMT
> -----BEGIN CERTIFICATE-----
> MIIFADCCA+igAwIBAgISBGbI6s1pQHstFjYmEDarQ7hqMA0GCSqGSIb3DQEBCwUA
> MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
> 

I noticed a normal connection shows different "depth" at the beginning like this:

> :~$ openssl s_client -connect letsencrypt.org:443 -showcerts
> CONNECTED(00000003)
> **depth=2** C = US, O = Internet Security Research Group, CN = ISRG Root X1
> verify return:1
> **depth=1** C = US, O = Let's Encrypt, CN = E6
> verify return:1
> **depth=0** CN = lencr.org
> verify return:1
> 

If I turn the certificate check off on the client side, the service runs OK so it means the server side CROW code is running.

Also if I use a browser to open the service URL:port, Firefox shows the connection is secure and can show the correct certificate chain generated by Lets Encrypt.

Is this an issue with CROW (I'm using V1.2.0) or I have some settings wrong?

**Comment by mrozigor** [comment]
I look at current implementation and it looks like we handling only one certificate (not a certificate chain). So it is a problem on Crow's side.

**Comment by gittiver** [comment]
As it is a server certificate and therefore the certificate chain can only be checked on the client side (to be cryptographically useful) I would assume there is a problem in your step. 
Another point that speaks fro that is that it works correctly with Firefox - it has the needed certificates in the chain.
