### ISSUE TITLE
How can framework users write tests?

### ISSUE THREAD

**Issue by b-long** [CrowCpp/crow#89]
I'm sorry if this has already been addressed, but I'm wondering about writing a basic unit test.

For example, the [type of test you might write for Flask](https://flask.palletsprojects.com/en/1.1.x/testing/#the-first-test), and simulating a client request:

```python
def test_empty_db(client):
    """Start with a blank database."""

    rv = client.get('/')
    assert b'No entries here so far' in rv.data
```

I thought I might find something [here](https://crowcpp.org/guides/app/), but I haven't.  Can anyone point me in the right direction?

**Comment by The-EDev** [comment]
I guess the best place to look would be Crow's own [unittest.cpp](https://github.com/CrowCpp/crow/blob/master/tests/unittest.cpp). The tests there simulate both a request response generation and a full TCP connection, If you write your tests in a similar fashion, they should work fine.

**Comment by b-long** [comment]
Great, thanks @The-EDev!

I did find some lines that look like a great start: 
https://github.com/CrowCpp/crow/blob/master/tests/unittest.cpp#L100-L109

Shall I close this issue or would it be helpful to leave it open and consider an update to the docs?

**Comment by The-EDev** [comment]
You can close this issue, I'll open another for adding testing instructions to the docs

**Comment by b-long** [comment]
Cool 👍 Thanks again 🙂
