### ISSUE TITLE
Feature request: add a way to set the format of floats and doubles in the JSON output

### ISSUE THREAD

**Issue by t-cadet** [CrowCpp/Crow#894]
The idea is to provide a way for Crow users to set the format of floating-point numbers in the JSON output to best fit their use case.

For example in my case having less significant digits:
 - improves readability
 - makes the output less sensitive to small changes in computations
 - makes diffing outputs for tests more robust

Related: https://github.com/CrowCpp/Crow/pull/891

**Comment by gittiver** [comment]
problem is loss of precision depending on value of the number. An implementation according to should use the maximum possible precision for 64bit double values.

Therefore this feature will not be implemented.

If you need a workaround for tests, store the value as string not as Number.
