### ISSUE TITLE
example HTTP hello_world program takes 192K

### ISSUE THREAD

**Issue by NobodyXu** [CrowCpp/crow#91]
I just compiled the example HTTP hello_world program with `clang-10.0.0-4ubuntu1` and `lld-10.0.0`:

```
clang++ -std=c++17 -Oz -Wall -flto -fno-asynchronous-unwind-tables -fno-unwind-tables -fmerge-all-constants
              -I /path/to/crow/ -fvisibility=hidden
              -s -Wl,-icf=all,--gc-sections,--as-needed -flto -Wl,--plugin-opt=O3 -fuse-ld=lld
              -lpthread -lboost_system
```

and the executable I get is 192K:

```
192K    hello.out
```

The size of executable is much larger than I expected.
As a comparison, `libnghttp2` which fully supports HTTP/2.0 is much smaller:

```
160K    /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.19.0
```

To find out what is taking so much size, I used `bloaty` to analyze the makeup of this program:

```
   FILE SIZE        VM SIZE                       
--------------  --------------                    
 52.8%  99.9Ki  53.0%  99.8Ki    .text            
 14.4%  27.3Ki  14.5%  27.3Ki    .rodata          
 12.0%  22.7Ki  12.0%  22.7Ki    .eh_frame        
  3.9%  7.47Ki   3.9%  7.41Ki    .dynstr          
  3.7%  6.95Ki   3.7%  6.89Ki    .gcc_except_table
  2.9%  5.45Ki   2.9%  5.39Ki    .dynsym          
  2.5%  4.73Ki   2.5%  4.66Ki    .rela.plt        
  1.8%  3.47Ki   1.8%  3.41Ki    .eh_frame_hdr    
  1.7%  3.19Ki   1.7%  3.12Ki    .plt             
  0.9%  1.70Ki   0.8%  1.58Ki    .got.plt         
  0.8%  1.52Ki   0.2%     320    [15 Others]      
  0.0%       0   0.7%  1.30Ki    .bss             
  0.4%     819   0.0%       0    [Unmapped]       
  0.0%       0   0.4%     784    .bss.rel.ro      
  0.4%     759   0.4%     759    [LOAD #2 [R]]    
  0.4%     680   0.3%     616    .data            
  0.3%     616   0.3%     552    .rela.dyn        
  0.3%     544   0.2%     480    .gnu.version_r   
  0.3%     524   0.2%     460    .gnu.version     
  0.3%     512   0.2%     448    .dynamic         
  0.2%     476   0.2%     412    .gnu.hash        
100.0%   189Ki 100.0%   188Ki    TOTAL            
```

and found that there is 99.9KB of assembly for the hello_world program which is suprisingly large, given that crow is header-only library that only supports HTTP/1.0, `clang` should be able to produce much smaller code.

Perhaps `crow` overuse virtual function and should consider use [CRTP], a template techique, to replace these virtual base classes and the size of executable will be much smaller and the performance also will be better.

The `.eh_frame` also takes 22.7KB which makes me want to disable exception all together to make the executable smaller, but `crow` clearly hasn't support `-fno-exceptions` yet.

[CRTP]: https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern

**Comment by mrozigor** [comment]
What is a size of hello world example for `libnghttp2`?

**Comment by NobodyXu** [comment]
I haven’t try it myself, but with LTO and HTTP/1.0 only, I doubt it will be larger than the hello world program I have here.

**Comment by The-EDev** [comment]
It is very unlikely that the current structure of Crow will fundamentally change. I understand this is not a good answer. But I do not believe I am experienced enough to rewrite most of what @ipkn did in a different structure, and until someone who does decides to take this task on, it will remain unresolved.

Closing for now. For anyone still interested in taking this on, Feel free to tag me to reopen this.

**Comment by lemire** [comment]
The current web page (https://github.com/CrowCpp/Crow/issues/91) saved as a web archive (with images and JavaScript) takes up 4.6 MB on my system. Unless Crow targets microcontrollers, 200 kB is tiny by modern standards.
