### ISSUE TITLE
Downloading large file is not possible due to the absence of chunked request

### ISSUE THREAD

**Issue by Rz-Rz** [CrowCpp/Crow#911]
I tried to download huge files using crow webserver but I couldn't as there is no way to chunk the response. Let me know if I'm wrong.

**Comment by gittiver** [comment]
Basically, if a response is larger than 1MB, it gets streamed the same way a static file does, this makes it so large responses don't get the 5 second timeout normal responses get. 
If it is a static file this is done automatically - see https://crowcpp.org/master/guides/static/

Have an eye on the timeout on late responses.

**Comment by Rz-Rz** [comment]
thank you
