### ISSUE TITLE
[Proposal]: Base template to create Crow Application

### ISSUE THREAD

**Issue by seobryn** [CrowCpp/Crow#913]
I'm not sure if any similar to this exists, but I would like to share with you this template to create Crow Application, is an Starter kit that allow you to create an opinionated Crow App. it contains all the basic things necessary to setup a basic Hello World API.

Let me know if it works for you.

https://github.com/seobryn/corax-template

## Features

- `Scripts` to Make, Compile and Clean the build
- `Libs` Folder to store all the external Libs, Crow is set by default.
- Format rules using  `clang-format`

**Comment by gittiver** [comment]
Maybe we can put these kind of template linked in a markdown file, same for crow Applications we know of.

**Comment by seobryn** [comment]
Hi @gittiver  Yes!, it make sense for me, I'll try to make a PR with something like you say.

**Comment by gittiver** [comment]
I already made a PR but wanted to add another sample. https://github.com/CrowCpp/Crow/tree/913-proposal-base-template-to-create-crow-application
