### ISSUE TITLE
Example program crashes

### ISSUE THREAD

**Issue by TooManyDots** [CrowCpp/crow#97]
```cpp
#include "crow_all.hpp"

int main() {
  crow::SimpleApp app;

  CROW_ROUTE(app, "/")([](){
      return "Hello world";
      });

  app.port(18080).multithreaded().run();
}
```

This crashes in the app.port-line with an error in the depths of boost

```cpp
template<class E> BOOST_NORETURN void throw_exception( E const & e )
{
    throw_exception_assert_compatibility( e );
    throw wrapexcept<E>( e );
}
```

Call stack and the exception:
![image](https://user-images.githubusercontent.com/35289254/104297226-e8241700-54c2-11eb-83f4-d9c4e6beb5cc.png)

I am using boost 1.75, windows 10 and clang ( llvm11 ).

**Comment by mrozigor** [comment]
It looks like `WSAEOPNOTSUPP (10045)` error in Windows. Some operation is not permitted. Are you able to find out which method fails?

**Comment by TooManyDots** [comment]
No

**Comment by mrozigor** [comment]
Even with debugger?

**Comment by The-EDev** [comment]
Closing this for lack of response, @TooManyDots feel free to reopen, or anyone else with the same issue can comment and I'll reopen.
